return [[
{
    "Lang": "bg",
    "Name": "Български",


    "Entities.gmod_subway_81-703.Buttons.HelperPanel.R_Program1Set": "Програма 1",
    "Entities.gmod_subway_81-703.Buttons.HelperPanel.R_Program2Set": "Програма 2: Аварийна",
    "Entities.gmod_subway_81-703.Buttons.HelperPanel.VDLSet": "ВДЛ: Включвател леви врати",
    "Entities.gmod_subway_81-703.Buttons.HelperPanel.VUD2Toggle": "ВУД2: Включвател управление на врати (затваряне на врати)",
    "Entities.gmod_subway_81-703.Buttons.Meters.!TotalVoltmeter": "ВН волтметър (kV)",
    "Entities.gmod_subway_81-703.Buttons.Meters.!TotalAmpermeter": "Амперметър (A)",
    "Entities.gmod_subway_81-703.Buttons.AV2.RSTToggle": "РСТ: Радиостанция",
    "Entities.gmod_subway_81-703.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Заден Краищен кран за налягане на метровлака",
    "Entities.gmod_subway_81-703.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Заден Краищен кран за налягане на спирачките",
    "Entities.gmod_subway_81-703.Buttons.Back2.!HVFuses": "Блок с бушони",
    "Entities.gmod_subway_81-703.Buttons.Back2.!DVR": "Кутия с въздухоразпределителните апарати на вратите",
    "Entities.gmod_subway_81-703.Buttons.Main.RK": "Индикатор: Контролерът на реостата се върти",
    "Entities.gmod_subway_81-703.Buttons.Main.GreenRP": "Индикатор: Зелена лампа за пренатоварване на релето",
    "Entities.gmod_subway_81-703.Buttons.Main.RedRP": "Индикатор: Червена лампа за претоварване на релето(схемите не могат да се съберат/активират)",
    "Entities.gmod_subway_81-703.Buttons.Main.Blue": "Индикатор: Синя лампа за състоянието на вратите (вратите са затворени)",
    "Entities.gmod_subway_81-703.Buttons.Main.DIPonSet": "Вкл. Осв.: Включване на осветлението",
    "Entities.gmod_subway_81-703.Buttons.Main.DIPoffSet": "Изкл. Осв.: Изключване на осветлението (активира и звънеца)",
    "Entities.gmod_subway_81-703.Buttons.Main.VozvratRPSet": "ВРП: Рестартиране на релето против претоварване(РП)",
    "Entities.gmod_subway_81-703.Buttons.Main.KSNSet": "КСН:Принудително включване РП на неизправния вагон (Сигнализация за неизправност)",
    "Entities.gmod_subway_81-703.Buttons.Main.KRZDSet": "КРЗД: Копче за резервно затваряне на вратите",
    "Entities.gmod_subway_81-703.Buttons.Main.KSDSet": "КСД: Контролер за състояние на вратите(проверка на сигнализация на вратите)",
    "Entities.gmod_subway_81-703.Buttons.Main.KDPSet": "КДП: Копче за отваряне на десните врати",
    "Entities.gmod_subway_81-703.Buttons.Main.KDLSet": "КДЛ: Копче за отваряне на левите врати",
    "Entities.gmod_subway_81-703.Buttons.Main.KU1Toggle": "МК: Включвател на мотор-компрессора",
    "Entities.gmod_subway_81-703.Buttons.Main.VUD1Toggle": "ВУД: Включвател за затваряне/отваряне на вратите",
    "Entities.gmod_subway_81-703.Buttons.Main.KRPSet": "РРП: Аварииен старт",
    "Entities.gmod_subway_81-703.Buttons.AV1.VU3Toggle": "ВУ3: Осветление на кабината",
    "Entities.gmod_subway_81-703.Buttons.AV1.VU2Toggle": "ВУ2: Аварийно осветление (45V)",
    "Entities.gmod_subway_81-703.Buttons.AV1.VU1Toggle": "ВУ1: Печка за отопление на кабината (3kW)",
    "Entities.gmod_subway_81-703.Buttons.AVMain.AV8BToggle": "АВ-8Б: Автоматичен бушон за схемите (Вспомагателен усилвател на волтажа)",
    "Entities.gmod_subway_81-703.Buttons.Lamp.L_3Toggle": "Лампа: Подсветка на измервателните прибори",
    "Entities.gmod_subway_81-703.Buttons.DriverValveTLDisconnect.DriverValveTLDisconnectToggle": "Двупозиционен кран за разпускането на налягането на влака",
    "Entities.gmod_subway_81-703.Buttons.VU.VUToggle": "ВУ: Превключвател за управление на вагона",
    "Entities.gmod_subway_81-703.Buttons.FrontDoor.FrontDoor": "Предна врата",
    "Entities.gmod_subway_81-703.Buttons.PneumaticManometer.!LinesPressure": "Налягане на пневматиката на метровлака (червена стрелка: спирачна, черна: вагонна)",
    "Entities.gmod_subway_81-703.Buttons.Stopkran.EmergencyBrakeValveToggle": "Аварийна спирачка",
    "Entities.gmod_subway_81-703.Buttons.UAVAPanel.UAVAToggle": "УАБА: Универсален Автоматичен Бушон за Автостоп (изключване на автостопа)",
    "Entities.gmod_subway_81-703.Buttons.UAVAPanel.UAVAContactSet": "УАБА: Универсален Автоматичен Бушон за Автостоп (възтановяване на контактите)",
    "Entities.gmod_subway_81-703.Buttons.PneumaticPanels.!CylinderPressure": "Brake manometer: Манометър на спирачната система",
    "Entities.gmod_subway_81-703.Buttons.Battery.VBToggle": "АБ: Ключ на батериите (помощни с нисък волтаж)",
    "Entities.gmod_subway_81-703.Buttons.Battery.R_RadioToggle": "Захранване на Информатора (+50V)",
    "Entities.gmod_subway_81-703.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Преден Краищен кран за налягане на спирачките",
    "Entities.gmod_subway_81-703.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Преден Краищен кран за налягане на метровлака",
    "Entities.gmod_subway_81-703.Buttons.ASNP.R_ASNPMenuSet": "Информатор: Меню",
    "Entities.gmod_subway_81-703.Buttons.ASNP.R_ASNPUpSet": "Информатор: Нагоре",
    "Entities.gmod_subway_81-703.Buttons.ASNP.R_ASNPDownSet": "Информатор: Надолу",
    "Entities.gmod_subway_81-703.Buttons.ASNP.R_ASNPOnToggle": "Информатор: Копче за включване/изключване",
    "Entities.gmod_subway_81-703.Buttons.GV.GVToggle": "ГВ: Превключвател за високо напрежение",
    "Entities.gmod_subway_81-703.Buttons.PassengerDoor.PassengerDoor": "Пасажерска врата за кабината на машиниста",
    "Entities.gmod_subway_81-703.Buttons.KRR.KRRToggle": "KРР: Копче за включване на реверсора",
    "Entities.gmod_subway_81-703.Buttons.VU4.VUSToggle": "Ключ: Къси фарове(надолу)/Дълги фарове(нагоре)",
    "Entities.gmod_subway_81-703.Buttons.CabinDoor.CabinDoor1": "Врата за кабината на машиниста",
    "Entities.gmod_subway_81-703.Buttons.Tsepi.!BatteryVoltage": "Напрежение на батериите и схемите за контрол",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.IGLA1USet": "ИГЛА: Първо копче: нагоре",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.IGLA1Set": "ИГЛА: Първо копче",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.IGLA1DSet": "ИГЛА: Първо копче: надолу",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.IGLA2USet": "ИГЛА: Второ копче: нагоре",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.IGLA2Set": "ИГЛА: Второ копче",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.IGLA2DSet": "ИГЛА: Второ копче: надолу",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.!IGLASR": "IGLA: SR",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.!IGLARX": "IGLA: RX",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.!IGLAErr": "ИГЛА: Отказ(Неизправност)",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.!IGLAOSP": "ИГЛА: ОСП (Пожарогасителна уредба)",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.!IGLAPI": "ИГЛА: ПИ (Индикатор за пожароопасност)",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.!IGLAOff": "ИГЛА: Изкл.",
    "Entities.gmod_subway_81-703.Buttons.Back1.R_UNchToggle": "УНЧ: Усилвател на ниските честоти (Информатор)",
    "Entities.gmod_subway_81-703.Buttons.Back1.IGLAToggle": "АСОТП: ИГЛА",
    "Entities.gmod_subway_81-703.Buttons.Back1.RezMKSet": "РМК: Резервно пускане на мотор-компрессора",
    "Entities.gmod_subway_81-703.Buttons.ParkingBrake.ParkingBrakeLeft": "Завъртване на колелото за ръчно налягане на накладките(наляво)",
    "Entities.gmod_subway_81-703.Buttons.ParkingBrake.ParkingBrakeRight": "Завъртване на колелото за ръчно налягане на накладките(надясно)",
    "Entities.gmod_subway_81-703.Buttons.DriverValveBLDisconnect.DriverValveBLDisconnectToggle": "Двупозиционен кран за разпускане на налягането на влака",
    "Entities.gmod_subway_81-703.Buttons.Speedometer.!Speedometer": "Скоростомер (км/ч)",
    "Entities.gmod_subway_81-703.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Изключване на вентилационната уредба",



    "Entities.gmod_subway_81-703_2.Buttons.Stopkran.EmergencyBrakeValveToggle": "Аварийна спирачка",
    "Entities.gmod_subway_81-703_2.Buttons.HelperPanel.R_Program1Set": "Програма 1",
    "Entities.gmod_subway_81-703_2.Buttons.HelperPanel.R_Program2Set": "Програма 2: Аварийна",
    "Entities.gmod_subway_81-703_2.Buttons.HelperPanel.VDLSet": "ВДЛ: Включвател леви врати",
    "Entities.gmod_subway_81-703_2.Buttons.HelperPanel.VUD2LToggle": "Тумблер за заключване на ВУД2",
    "Entities.gmod_subway_81-703_2.Buttons.HelperPanel.VUD2Toggle": "ВУД2: Включвател управление на врати (затваряне на врати)",
    "Entities.gmod_subway_81-703_2.Buttons.PneumaticPanels.!CylinderPressure": "Манометър на спирачната система",
    "Entities.gmod_subway_81-703_2.Buttons.Battery.VBToggle": "АБ: Ключ на батериите (помощни с нисък волтаж)",
    "Entities.gmod_subway_81-703_2.Buttons.Battery.R_RadioToggle": "Захранване на Информатора (+50V)",
    "Entities.gmod_subway_81-703_2.Buttons.Meters.!TotalVoltmeter": "ВН волтметър (kV)",
    "Entities.gmod_subway_81-703_2.Buttons.Meters.!TotalAmpermeter": "Амперметър (A)",
    "Entities.gmod_subway_81-703_2.Buttons.AV2.RSTToggle": "РСТ: Радиостанция",
    "Entities.gmod_subway_81-703_2.Buttons.PassengerDoor.PassengerDoor": "Пасажерска врата за кабината на машиниста",
    "Entities.gmod_subway_81-703_2.Buttons.VU4.VUSToggle": "Ключ: Къси фарове(надолу)/Дълги фарове(нагоре)",
    "Entities.gmod_subway_81-703_2.Buttons.AV1.VU3Toggle": "ВУ3: Осветление на кабината",
    "Entities.gmod_subway_81-703_2.Buttons.AV1.VU2Toggle": "ВУ2: Аварийно осветление (45V)",
    "Entities.gmod_subway_81-703_2.Buttons.AV1.VU1Toggle": "ВУ1: Печка за отопление на кабината (3kW)",
    "Entities.gmod_subway_81-703_2.Buttons.UAVAPanel.UAVAToggle": "УАБА: Универсален Автоматичен Бушон за Автостоп (изключване на автостопа)",
    "Entities.gmod_subway_81-703_2.Buttons.UAVAPanel.UAVAContactSet": "УАБА: Универсален Автоматичен Бушон за Автостоп (възтановяване на контактите)",
    "Entities.gmod_subway_81-703_2.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Изключване на вентилационната уредба",
    "Entities.gmod_subway_81-703_2.Buttons.GV.GVToggle": "ГВ: Превключвател на високо напрежение",
    "Entities.gmod_subway_81-703_2.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Преден Краищен кран за налягане на спирачките",
    "Entities.gmod_subway_81-703_2.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Преден Краищен кран за налягане на метровлака",
    "Entities.gmod_subway_81-703_2.Buttons.Tsepi.!BatteryVoltage": "Напрежение на батериите и схемите за контрол",
    "Entities.gmod_subway_81-703_2.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Заден Краищен кран за налягане на метровлака",
    "Entities.gmod_subway_81-703_2.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Заден Краищен кран за налягане на спирачките",
    "Entities.gmod_subway_81-703_2.Buttons.ParkingBrake.ParkingBrakeLeft": "Завъртване на колелото за ръчно налягане на накладките(наляво)",
    "Entities.gmod_subway_81-703_2.Buttons.ParkingBrake.ParkingBrakeRight": "Завъртване на колелото за ръчно налягане на накладките(надясно)",
    "Entities.gmod_subway_81-703_2.Buttons.Back2.!HVFuses": "Блок с бушони",
    "Entities.gmod_subway_81-703_2.Buttons.Back2.!DVR": "Кутия с въздухоразпределителните апарати на вратите",
    "Entities.gmod_subway_81-703_2.Buttons.Main.RK": "Индикатор: Контролерът на реостата се върти",
    "Entities.gmod_subway_81-703_2.Buttons.Main.GreenRP": "Индикатор: Зелена лампа за пренатоварване на релето",
    "Entities.gmod_subway_81-703_2.Buttons.Main.RedRP": "Индикатор: Червена лампа за претоварване на релето(схемите не могат да се съберат/активират)",
    "Entities.gmod_subway_81-703_2.Buttons.Main.Blue": "Индикатор: Синя лампа за състоянието на вратите (вратите са затворени)",
    "Entities.gmod_subway_81-703_2.Buttons.Main.DIPonSet": "Вкл. Осв.: Включване на осветлението",
    "Entities.gmod_subway_81-703_2.Buttons.Main.DIPoffSet": "Изкл. Осв.: Изключване на осветлението (активира и звънеца)",
    "Entities.gmod_subway_81-703_2.Buttons.Main.VozvratRPSet": "ВРП: Рестартиране на релето против претоварване(РП)",
    "Entities.gmod_subway_81-703_2.Buttons.Main.KSNSet": "КСН:Принудително включване РП на неизправния вагон (Сигнализация за неизправност)",
    "Entities.gmod_subway_81-703_2.Buttons.Main.KRZDSet": "КРЗД: Копче за резервно затваряне на вратите",
    "Entities.gmod_subway_81-703_2.Buttons.Main.KSDSet": "КСД: Контролер за състояние на вратите(проверка на сигнализация на вратите)",
    "Entities.gmod_subway_81-703_2.Buttons.Main.KDPSet": "КДП: Копче за отваряне на десните врати",
    "Entities.gmod_subway_81-703_2.Buttons.Main.KDLSet": "КДЛ: Копче за отваряне на левите врати",
    "Entities.gmod_subway_81-703_2.Buttons.Main.KU1Toggle": "МК: Включвател на мотор-компрессора",
    "Entities.gmod_subway_81-703_2.Buttons.Main.VUD1Toggle": "ВУД: Включвател за затваряне/отваряне на вратите",
    "Entities.gmod_subway_81-703_2.Buttons.Main.KRPSet": "РРП: Аварииен старт",
    "Entities.gmod_subway_81-703_2.Buttons.KRR.KRRToggle": "KРР: Копче за включване на реверсора",
    "Entities.gmod_subway_81-703_2.Buttons.Back1.R_ZSToggle": "ЗС: Тумблер за усилвателите във метровлака",
    "Entities.gmod_subway_81-703_2.Buttons.Back1.IGLAToggle": "АСОТП: ИГЛА",
    "Entities.gmod_subway_81-703_2.Buttons.Back1.RezMKSet": "РМК: Резервно пускане на мотор-компрессора",
    "Entities.gmod_subway_81-703_2.Buttons.CabinDoor.CabinDoor1": "Врата за кабината на машиниста",
    "Entities.gmod_subway_81-703_2.Buttons.Lamp.L_3Toggle": "Лампа: Подсветка на измервателните прибори",
    "Entities.gmod_subway_81-703_2.Buttons.DriverValveBLDisconnect.DriverValveBLDisconnectToggle": "Тяга за разпускане на налягането на спирачките",
    "Entities.gmod_subway_81-703_2.Buttons.DriverValveTLDisconnect.DriverValveTLDisconnectToggle": "Тяга за разпускане на налягането на метровлака",
    "Entities.gmod_subway_81-703_2.Buttons.AVMain.AV8BToggle": "АВ-8Б: Автоматичен бушон за схемите (Вспомагателен усилвател на волтажа)",
    "Entities.gmod_subway_81-703_2.Buttons.VU.VUToggle": "ВУ: Превключвател за управление на вагона",
    "Entities.gmod_subway_81-703_2.Buttons.FrontDoor.FrontDoor": "Предна врата",
    "Entities.gmod_subway_81-703_2.Buttons.Speedometer.!Speedometer": "Скоростомер",
"Entities.gmod_subway_81-703_2.Buttons.PneumaticManometer.!LinesPressure": "Налягане на пневматиката на метровлака (червена стрелка: спирачна, черна: вагонна)"
}
]]
