return [[
{
  "Lang": "bg",
  "Name": "Bulgarian",

  "Entities.gmod_subway_81-717_mvm.Buttons.HelperPanel.VUD2Toggle": "ВУД2: Превключвател за управление на вратите (затворете вратите)",
  "Entities.gmod_subway_81-717_mvm.Buttons.HelperPanel.VDLSet": "ВДЛ: Отвори левите врати",
  "Entities.gmod_subway_81-717_mvm.Buttons.HelperPanel.R_Program2Helper": "Програма 2",
  "Entities.gmod_subway_81-717_mvm.Buttons.HelperPanel.R_Program1Helper": "Програма 1",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery_2.1:RC1Toggle": "РЦ1: AСР схемите се изключват",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery_2.1:VBToggle": "ВБ: Батерия включване/изключване",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery_2.1:UOSToggle": "РЦ-УОС: Устройство за ограничение на скоростта",
  "Entities.gmod_subway_81-717_mvm.Buttons.Wiper.WiperToggle": "Чистачки",
  "Entities.gmod_subway_81-717_mvm.Buttons.DriverValveDisconnect.DriverValveDisconnectToggle": "Демонтиращ клапан на спирачния лост",
  "Entities.gmod_subway_81-717_mvm.Buttons.DriverValveDisconnect.DriverValveBLDisconnectToggle": "Демонтиращ вентил на спирачната система",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_UNchToggle": "UNCh: Усилвател с ниска честота",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_ZSToggle": "ЕС: Контрол за аварийна комуникация",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_GToggle": "Високоговорител: Включване на звука в кабината",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_RadioToggle": "Радиоинформатор: говорител (вграден)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_Program1Set": "Програма 1",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_Program2Set": "Програма 2",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.2:KVTSet": "КБ: Бутон за внимание",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.VZ1Set": "ВЗ1: Пневматичен клапан # 1",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.VUD1Toggle": "ВУД: Превключвател за управление на вратите (затворете вратите)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KDLSet": "КДЛ: Отвори левите врати",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KDLKToggle": "Капак на бутона КДЛ",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KDLRSet": "КДЛ: Отвори левите врати",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KDLRKToggle": "КДЛ покривао на копчето",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.DoorSelectToggle": "Изберете страна на вратите",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KRZDSet": "КРЗД: Аварийно затваряне на вратите",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.R_VPRToggle": "ВРП: Включване на радиостанцията",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.VozvratRPSet": "Рестартирайте релето за претоварване",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.GreenRPLight": "РП: Зелена светлина на релето за претоварване (предотвратява претоварване на двигателите)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.AVULight": "АВУ: Автоматично деактивиране на управлението е активно",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.LKVPLight": "ЛКВП: Контрол на високоволтовия преобразувател",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.SPLight": "ЛСП: Пожар (прегряване на реостат)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.ConverterProtectionSet": "Защита на конвертора",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.KSNSet": "КСН: Принудително активиране на РП на дефектния вагон (сигнализация при неизправност)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.DIPoffSet": "Звън",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.ARSToggle": "АРС: Автоматична скоростна регулация",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.ALSToggle": "АЛС: Автоматична локомотивна сигнализация",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.OtklAVUToggle": "Изключване на автоматичното управление за изключване на реле (неизправност на АВУ)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.TormATToggle": "(контейнер) Активиране на аварийната спирачка",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.L_1Toggle": "Осветление във вагона",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.L_2Toggle": "Осветление в кабината",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.L_3Toggle": "Осветителни тела",
  "Entities.gmod_subway_81-717_mvm.Buttons.Main.ALSFreqToggle": "Декодер: АЛС честотен превключвател (надолу - 1/5, нагоре - 2/6)",
  "Entities.gmod_subway_81-717_mvm.Buttons.ParkingBrake.ParkingBrakeToggle": "Ръчна спирачка",
  "Entities.gmod_subway_81-717_mvm.Buttons.ParkingBrake.DriverValveTLDisconnectToggle": "Вентил за изключване на влака",
  "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.IGLA1Set": "ИГЛА: Първи бутон",
  "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.IGLA2Set": "ИГЛА: Втори бутон",
  "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.IGLA3Set": "ИГЛА: Трети бутон",
  "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.IGLA4Set": "ИГЛА: Четвърти бутон",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.!Voltage": "Волтаж на батерията",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.VMKToggle": "Включете двигателния компресор",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.BPSNonToggle": "БПСН: Електрическо захранване на влака",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.RezMKSet": "Аварийно стартиране на двигателния компресор",
  "Entities.gmod_subway_81-717_mvm.Buttons.BPSNFront.ARS13Set": "АРС 13V: АРС стабилизира проверката на напрежението",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!RouteNum": "М №\nНомер на маршрута",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!PathNum": "П №\nНомер на патеката",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchTime": "ВРЕМЯ ХОДА\nОбщо време на графика",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchInterval": "ИНТ\nИнтервал между влаковете",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchHour": "ЧАС\nЧас",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchMin": "МИН\nМинута",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchSec": "СЕК\nСекунда",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchArrival": "Времена на пристигане",
  "Entities.gmod_subway_81-717_mvm.Buttons.Schedule.!SchStations": "Име на станцията",
  "Entities.gmod_subway_81-717_mvm.Buttons.PneumaticPanels.!CylinderPressure": "Налягане на спирачния цилиндър",
  "Entities.gmod_subway_81-717_mvm.Buttons.PneumaticPanels.!LinePressure": "Налягане в пневматични линии (червено: спирачна линия, черна: влакова линия)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery.RC1Toggle": "РЦ-1: АРС схемите се изключват",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery.UOSToggle": "РЦ-УОС: Устройство за лимитиране на скоростта",
  "Entities.gmod_subway_81-717_mvm.Buttons.Battery.VBToggle": "ВБ: Батерия включване/изключване",
  "Entities.gmod_subway_81-717_mvm.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Изолационен вентил на спирачната система",
  "Entities.gmod_subway_81-717_mvm.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Вентил за изолация на влаковата линия",
  "Entities.gmod_subway_81-717_mvm.Buttons.ASNP.R_ASNPMenuSet": "АСНП: Меню",
  "Entities.gmod_subway_81-717_mvm.Buttons.ASNP.R_ASNPUpSet": "АСНП: Горе",
  "Entities.gmod_subway_81-717_mvm.Buttons.ASNP.R_ASNPDownSet": "АСНП: Долу",
  "Entities.gmod_subway_81-717_mvm.Buttons.ASNP.R_ASNPOnToggle": "АСНП: Включи",
  "Entities.gmod_subway_81-717_mvm.Buttons.RearDoor.RearDoor": "Задна врата",
  "Entities.gmod_subway_81-717_mvm.Buttons.Meters.!TotalVoltmeter": "ПВН волтметър (kV)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Meters.!TotalAmpermeter": "Общ амперметър (A)",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A61Toggle": "A61 Контрол на влаков проводник 6",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A55Toggle": "A55 Контрол на влаков проводник 10АС",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A54Toggle": "A54 Контрол на влаков проводник 10АК",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A56Toggle": "A56 Включете захранването на батерията, за да управлявате веригите",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A27Toggle": "A27 Бушон ДИП и осветление",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A21Toggle": "A21 Управление на вратите",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A10Toggle": "A10 Контрол на двигателя-компресор",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A53Toggle": "A53 KVC захранване",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A43Toggle": "A43 АРС 12V захранване",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A45Toggle": "A45 АРС влаков проводник 10AU",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A42Toggle": "A42 АРС 75V захранване",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A41Toggle": "A41 АРС спиране",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.VUToggle": "ВУ  Управление на влака",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A64Toggle": "A64 Осветление на кабината",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A63Toggle": "A63 ИГЛА/БИС",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A50Toggle": "A50 Включвател ДИП и осветление",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A51Toggle": "A51 Изключвател ДИП и осветление",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A23Toggle": "A23 Аварийно пускане на мотор-компресора",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A14Toggle": "A14 Влаков проводник 18",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A75Toggle": "A75 Отопление на кабината",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A1Toggle": "A1  X-1",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A2Toggle": "A2  X-2",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A3Toggle": "A3  X-3",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A17Toggle": "A17 Рестартиране релето за претоварване",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A62Toggle": "A62 Радиосъобщения",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A29Toggle": "A29 Радиопредаване",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A5Toggle": "A5 ",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A6Toggle": "A6  T-1",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A8Toggle": "A8  Пневматични клапани # 1, # 2",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A20Toggle": "A20 Управление на задвижващата / спиращата схема, влаков проводник 20",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A25Toggle": "A25 Ръчно електрическо спиране",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A22Toggle": "A22 Включи KK",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A30Toggle": "A30 Мощност на мотора на регулатора на реостата",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A39Toggle": "A39 Авариен контрол",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A44Toggle": "A44 Аварийно управление на влака",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A80Toggle": "A80 Мощност на мотора на превключвателя на режима на мощност",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A65Toggle": "A65 Осветление във вагона",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.L_5Toggle": "А49 Аварийно осветление",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A24Toggle": "A24 Зареждане на батерията",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A32Toggle": "A32 Отваряне десните врати",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A31Toggle": "A31 Отваряне левите врати",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A16Toggle": "A16 Затвори вратите",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A13Toggle": "A13 Сигнализация за вратите",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A12Toggle": "A12 Аварийно затваряне на вратите",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A7Toggle": "A7  Червена лампа",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A9Toggle": "A9  Червена лампа",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A46Toggle": "A46 Бяла лампа",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV.A47Toggle": "A47 Бяла лампа",
  "Entities.gmod_subway_81-717_mvm.Buttons.PassengerDoor.PassengerDoor": "Вратата на пътниците",
  "Entities.gmod_subway_81-717_mvm.Buttons.GV.GVToggle": "Превключвател за високо напрежение",
  "Entities.gmod_subway_81-717_mvm.Buttons.Stopkran.EmergencyBrakeValveToggle": "Аварийна спирачка",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.L_4Toggle": "Включване на фаровете",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.VUSToggle": "ВУС: Светлина на фаровете дълги / къси",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.VAHToggle": "ВАХ: Режим на аварийно шофиране (отказ на РБП реле)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.VADToggle": "ВАД: Аварийно затваряне на вратите (отказ на КД реле)",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KRPSet": "КРП: Бутон за аварийно стартиране",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KAHSet": "КАХ: Бутон за аварийно задвижване",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KAHKToggle": "Капак на бутона КАХ",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KUP": "Контрол на нагревателя",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KDPSet": "KDP: Отвори десните врати",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.KDPKToggle": "Капак на бутона КДП",
  "Entities.gmod_subway_81-717_mvm.Buttons.Front.PN": "Контрол на пневматичната спирачка",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A61Toggle": "A61 Контрол на влаков проводник 6",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A55Toggle": "A55 Контрол на влаков проводник 10АС",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A54Toggle": "A54 Контрол на влаков проводник 10АК",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A56Toggle": "A56 Включвател захранването на батерията",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A27Toggle": "A27 Бушон ДИП и осветление",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A21Toggle": "A21 Управление на вратите",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A10Toggle": "A10 Контрол на двигателния-компресор",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A53Toggle": "A53 KVC захранване",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A43Toggle": "A43 АРС 12V захранване",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A45Toggle": "A45 АРС влаков проводник 10АУ",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A42Toggle": "A42 АРС 75V захранване",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A41Toggle": "A41 АРС спиране",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:VUToggle": "VU  Управление на влака",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A64Toggle": "A64 Осветление на кабината",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A63Toggle": "A63 ИГЛА/БИС",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A50Toggle": "A50 Включвател ДИП и осветление",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A51Toggle": "A51 Изключвател ДИП и осветление",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A23Toggle": "A23 Включвател на аварийния моторен компресор",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A14Toggle": "A14 влаков проводник 18",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A75Toggle": "A75 Отпление на кабината",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A1Toggle": "A1  X-1",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A2Toggle": "A2  X-2",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A3Toggle": "A3  X-3",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A17Toggle": "A17 Рестартиране релето за претоварване",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A62Toggle": "A62 Радиосъобщения",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A29Toggle": "A29 Радиопредаване",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A5Toggle": "A5 ",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A6Toggle": "A6  T-1",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A8Toggle": "A8  Пневматични клапани #1, #2",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A20Toggle": "A20 Управление на задвижващата / спиращата схема, влаков проводник 20",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A25Toggle": "A25 Ръчно електрическо спиране",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A22Toggle": "A22 Включване на KK",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A30Toggle": "A30 Мощност на мотора на регулатора на реостата",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A39Toggle": "A39 Авариен контрол",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A44Toggle": "A44 Аварийно управление на влака",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A80Toggle": "A80 Мощност на мотора на превключвателя на режима на мощност",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A65Toggle": "A65 Осветление във вагона",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:L_5Toggle": "А49 Аварийно осветление",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A24Toggle": "A24 Зареждане на батерията",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A32Toggle": "A32 Отваряне на десните врати",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A31Toggle": "A31 Отваряне на левите врати",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A16Toggle": "A16 Затвори вратите",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A13Toggle": "A13 Аларма за вратите",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A12Toggle": "A12 Аварийно затваряне на вратите",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A7Toggle": "A7  Червена лампа",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A9Toggle": "A9  Червена лампа",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A46Toggle": "A46 Бяла лампа",
  "Entities.gmod_subway_81-717_mvm.Buttons.AV_1.1:A47Toggle": "A47 Бяла лампа",
  "Entities.gmod_subway_81-717_mvm.Buttons.CabinDoor.CabinDoor": "Врата на кабината",
  "Entities.gmod_subway_81-717_mvm.Buttons.Reverser.KVReverserDown": "Реверсор назад",
  "Entities.gmod_subway_81-717_mvm.Buttons.Reverser.KVReverserUp": "Реверсор напред",
  "Entities.gmod_subway_81-717_mvm.Buttons.PassengerDoor1.PassengerDoor": "Врата на пътниците",
  "Entities.gmod_subway_81-717_mvm.Buttons.UAVAPanel.UAVAToggle": "УАВА: Универсално деактивиране на автостоп (деактивиране на автостоп)",
  "Entities.gmod_subway_81-717_mvm.Buttons.UAVAPanel.UAVAContactSet": "УАВА: Универсално деактивиране на автостоп (нулиране на контактите)",
  "Entities.gmod_subway_81-717_mvm.Buttons.EPKDisconnect.EPKToggle": "ЕПВ изключващ вентил",
  "Entities.gmod_subway_81-717_mvm.Buttons.Help.ShowHelp": "Покажи помощ при управлението на влака",
  "Entities.gmod_subway_81-717_mvm.Buttons.ParkingBrake2.1:ParkingBrakeToggle": "Ръчна спирачка",
  "Entities.gmod_subway_81-717_mvm.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Изолационен вентил на спирачната система",
  "Entities.gmod_subway_81-717_mvm.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Вентил за изолация на влаковата линия",
  "Entities.gmod_subway_81-717_mvm.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Деактивиране разпределителя на въздуха",

  "Entities.gmod_subway_81-714_mvm.Buttons.GV.GVToggle": "Превключвател за високо напрежение",
  "Entities.gmod_subway_81-714_mvm.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Изолационен вентил на спирачната система",
  "Entities.gmod_subway_81-714_mvm.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Вентил за изолация на влаковата линия",
  "Entities.gmod_subway_81-714_mvm.Buttons.RearDoor.RearDoor": "Задна врата",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.DriverValveBLDisconnectToggle": "Демонтиращ вентил на спирачната система",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.DriverValveTLDisconnectToggle": "Вентил за изключване на влака",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A65Toggle": "A65 Осветление във вагона",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A56Toggle": "A56 Включване захранването на батерията",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A63Toggle": "A63 ИГЛА/БИС",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A10Toggle": "A10 Контрол на двигателния компресор",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A30Toggle": "A30 Мощност на мотора на регулатора на реостата",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Left.A80Toggle": "A80 Мощност на мотора на превключвателя на режима на мощност",
  "Entities.gmod_subway_81-714_mvm.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Изолационен вентил на спирачната система",
  "Entities.gmod_subway_81-714_mvm.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Вентил за изолация на влаковата линия",
  "Entities.gmod_subway_81-714_mvm.Buttons.FrontPneumatic.ParkingBrakeToggle": "Ръчна спирачка",
  "Entities.gmod_subway_81-714_mvm.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Деактивиране разпределителя на въздуха",
  "Entities.gmod_subway_81-714_mvm.Buttons.FrontDoor.FrontDoor": "Предна врата",
  "Entities.gmod_subway_81-714_mvm.Buttons.Battery.VBToggle": "VB: Батерия включване/изключване",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A54Toggle": "A54 Контрол на влаков проводник 10AK",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A27Toggle": "A27 Бушон ДИП и осветление",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A24Toggle": "A24 Зареждане на батерията",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A53Toggle": "A53 КВЦ захранване",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A13Toggle": "A13 Аларма за вратите",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A32Toggle": "A32 Отваряне на десните врати",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A31Toggle": "A31 Отваряне на левите врати",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A16Toggle": "A16 Затваряне на вратите",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A12Toggle": "A12 Аварийно затваряне на вратите",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A50Toggle": "A50 Включвател ДИП и осветление",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A51Toggle": "A51 Изключвател ДИП и осветление",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A1Toggle": "A1  X-1",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.KRPSet": "СТАРТ: Бутон за аварийно стартиране",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.VozvratRPSet": "Рестартиране релето за претоварване",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.RezMKSet": "Аварийно стартиране на двигателния компресор",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.VMKToggle": "Включвател двигателния компресор",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.BPSNonToggle": "БПСН: Електрическо захранване на влака",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A2Toggle": "A2  X-2",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A3Toggle": "A3  X-3",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A17Toggle": "A17 Рестартиране релето за претоварване",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A5Toggle": "A5  ",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A6Toggle": "A6  T-1",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A8Toggle": "A8  Пневматични клапани #1, #2",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A20Toggle": "A20 Управление на задвижващата / спиращата схема, влаков проводник 20",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A25Toggle": "A25 Ръчно електрическо спиране",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A22Toggle": "A22 Включвател КК",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A23Toggle": "A23 Аварийно пускане на мотор-компресора",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A39Toggle": "A39 Авариен контрол",
  "Entities.gmod_subway_81-714_mvm.Buttons.AV_Right.A14Toggle": "A14 Влаков проводник 18",


  "Entities.gmod_subway_81-717_mvm.Buttons.KiyvARS.!Speedometer1": "Индикатор за скоростта",
  "Entities.gmod_subway_81-717_mvm.Buttons.KiyvARS.!Speedometer2": "Индикатор за скоростта",
  "Entities.gmod_subway_81-717_mvm.Buttons.KiyvARS.!ARSOch": "ОЧ: Отсъства честота на АРС",
  "Entities.gmod_subway_81-717_mvm.Buttons.KiyvARS.!ARS0": "0: Сигнал за спиране на АРС",
  "Entities.gmod_subway_81-717_mvm.Buttons.KiyvARS.!ARS40": "Ограничение на скоростта 40 км/ч",
  "Entities.gmod_subway_81-717_mvm.Buttons.KiyvARS.!ARS60": "Ограничение на скоростта 60 км/ч",
  "Entities.gmod_subway_81-717_mvm.Buttons.KiyvARS.!ARS70": "Ограничение на скоростта 70 км/ч",
  "Entities.gmod_subway_81-717_mvm.Buttons.KiyvARS.!ARS80": "Ограничение на скоростта 80 км/ч",
  "Entities.gmod_subway_81-717_mvm.Buttons.KiyvARS.!LampLSD1": "ЛСД: Светлина за състоянието на вратите (вратите са затворени)",
  "Entities.gmod_subway_81-717_mvm.Buttons.KiyvARS.!LampLSD2": "ЛСД: Светлина за състоянието на вратите (вратите са затворени)",
  "Entities.gmod_subway_81-717_mvm.Buttons.KiyvARS.!LampLVD": "1: Двигателите работят",
  "Entities.gmod_subway_81-717_mvm.Buttons.KiyvARS.!LampLHRK": "2: Реостатна контролна лампа за движение",
  "Entities.gmod_subway_81-717_mvm.Buttons.KiyvARS.!LampLST": "6: Спирачките са пуснати",
  "Entities.gmod_subway_81-717_mvm.Buttons.KiyvARS.!LampLRD": "ДВ: Дефект в сензора на въртене",
  "Entities.gmod_subway_81-717_mvm.Buttons.KiyvARS.!LampRP": "РП: Червена светлина на релето за претоварване (схемите на захранването не можаха да се монтират)",
  "Entities.gmod_subway_81-717_mvm.Buttons.KiyvARS.!LampLSN": "ЛСН: Индикатор за неизправност (схемите за мощност не са могли да се съберат/активират)",
  "Entities.gmod_subway_81-717_mvm.Buttons.KiyvARS.!LampLKVD": "ЛКВД: Индикатор за изключване на двигателя АРС",
  "Entities.gmod_subway_81-717_mvm.Buttons.KiyvARS.!LampLKT": "ЛКТ: АРС спирачен индикатор",
  "Entities.gmod_subway_81-717_mvm.Buttons.KiyvARS.!LampDV": "ДВ: Дефект в сензора на въртене",
  "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.IGLA23": "ИГЛА: Втори и трети бутони",
  "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.!IGLAFire": "ИГЛА: Пожар",
  "Entities.gmod_subway_81-717_mvm.Buttons.IGLAButtons.!IGLAErr": "ИГЛА: Неизправност",
  "Entities.gmod_subway_81-717_mvm.Buttons.RoundARS.!Speedometer1": "Индикатор за скорост",
  "Entities.gmod_subway_81-717_mvm.Buttons.RoundARS.!Speedometer2": "Индикатор за скорост",
  "Entities.gmod_subway_81-717_mvm.Buttons.RoundARS.!ARSOch": "ОЧ: Няма АРС честота",
  "Entities.gmod_subway_81-717_mvm.Buttons.RoundARS.!ARS0": "0: АРС сигнал за спиране",
  "Entities.gmod_subway_81-717_mvm.Buttons.RoundARS.!ARS40": "Ограничение на скоростта 40 км/ч",
  "Entities.gmod_subway_81-717_mvm.Buttons.RoundARS.!ARS60": "Ограничение на скоростта 60 км/ч",
  "Entities.gmod_subway_81-717_mvm.Buttons.RoundARS.!ARS70": "Ограничение на скоростта 70 км/ч",
  "Entities.gmod_subway_81-717_mvm.Buttons.RoundARS.!ARS80": "Ограничение на скоростта 80 км/ч",
  "Entities.gmod_subway_81-717_mvm.Buttons.RoundARS.!LampLSD1": "ЛСД: светлина за състоянието на вратите (вратите са затворени)",
  "Entities.gmod_subway_81-717_mvm.Buttons.RoundARS.!LampLSD2": "ЛСД: светлина за състоянието на вратите (вратите са затворени)",
  "Entities.gmod_subway_81-717_mvm.Buttons.RoundARS.!LampLHRK": "ЛхРК: Реостатна контролна лампа за движение",
  "Entities.gmod_subway_81-717_mvm.Buttons.RoundARS.!LampRP": "РП: Червена светлина на релето за претоварване (схемите на захранването не можаха да се съберат/активират)",
  "Entities.gmod_subway_81-717_mvm.Buttons.RoundARS.!LampLSN": "ЛСН: Индикатор за неизправност (схемите за мощност не са могли да се съберат/активират)",
  "Entities.gmod_subway_81-717_mvm.Buttons.RoundARS.!LampLN": "ЛН: Сигнал за посока",
  "Entities.gmod_subway_81-717_mvm.Buttons.RoundARS.!LampLKVD": "ЛКВД: Индикатор за изключване на двигателя АРС",
  "Entities.gmod_subway_81-717_mvm.Buttons.RoundARS.!LampLKT": "ЛКТ: АРС спирачен индикатор",
  "Entities.gmod_subway_81-717_mvm.Buttons.RoundARS.!LampLKVC": "ЛКВЦ: Не е налице високо напрежение",
  "Entities.gmod_subway_81-717_mvm.Buttons.RoundARS.!LampLRS": "ЛРС: Светлинен индикатор за скорост (следваща сегментна скорост, равна или по-голяма от сегашната)",
  "Entities.gmod_subway_81-717_mvm.Buttons.RoundARS.!LampLVD": "ЛВД: Двигателите работят",
  "Entities.gmod_subway_81-717_mvm.Buttons.RoundARS.!LampLST": "ЛСТ: Спирачките са пуснати",
  "Entities.gmod_subway_81-717_mvm.Buttons.SquareARS.!Speedometer1": "Индикатор за скорост",
  "Entities.gmod_subway_81-717_mvm.Buttons.SquareARS.!Speedometer2": "Индикатор за скорост",
  "Entities.gmod_subway_81-717_mvm.Buttons.SquareARS.!ARSOch": "ОЧ: Няма АРС честота",
  "Entities.gmod_subway_81-717_mvm.Buttons.SquareARS.!ARS0": "0: Сигнал за спиране на АРС",
  "Entities.gmod_subway_81-717_mvm.Buttons.SquareARS.!ARS40": "Ограничение на скоростта 40 kph",
  "Entities.gmod_subway_81-717_mvm.Buttons.SquareARS.!ARS60": "Ограничение на скоростта 60 kph",
  "Entities.gmod_subway_81-717_mvm.Buttons.SquareARS.!ARS70": "Ограничение на скоростта 70 kph",
  "Entities.gmod_subway_81-717_mvm.Buttons.SquareARS.!ARS80": "Ограничение на скоростта 80 kph",
  "Entities.gmod_subway_81-717_mvm.Buttons.SquareARS.!LampLSD1": "ЛСД: светлина за състоянието на вратите (вратите са затворени)",
  "Entities.gmod_subway_81-717_mvm.Buttons.SquareARS.!LampLSD2": "ЛСД: светлина за състоянието на вратите (вратите са затворени)",
  "Entities.gmod_subway_81-717_mvm.Buttons.SquareARS.!LampLVD": "ЛВД: Двигателите работят",
  "Entities.gmod_subway_81-717_mvm.Buttons.SquareARS.!LampLHRK": "ЛхРК: Реостатна контролна лампа за движение",
  "Entities.gmod_subway_81-717_mvm.Buttons.SquareARS.!LampLST": "ЛСТ: Спирачките са пуснати",
  "Entities.gmod_subway_81-717_mvm.Buttons.SquareARS.!LampRP": "РП: Червена светлина на релето за претоварване (схемите на захранването не можаха да се съберат/активират)",
  "Entities.gmod_subway_81-717_mvm.Buttons.SquareARS.!LampLSN": "ЛСН: Индикатор за неизправност (схемите за мощност не са могли да се съберат/активират)",
  "Entities.gmod_subway_81-717_mvm.Buttons.SquareARS.!LampLKVD": "ЛКВД: Индикатор за изключване на двигателя АРС",
  "Entities.gmod_subway_81-717_mvm.Buttons.SquareARS.!LampLKVC": "ЛКВЦ: Не е налице високо напрежение",
  "Entities.gmod_subway_81-717_mvm.Buttons.SquareARS.!LampLKT": "ЛКТ: АРС спирачен индикатор",
  "Entities.gmod_subway_81-717_mvm.Buttons.SquareARS.!LampLEKK": "ГЛЕБ: Работна лампа Gleb",
  "Entities.gmod_subway_81-717_mvm.Buttons.SquareARS.!LampLN": "ЛН: Сигна за посока",
  "Entities.gmod_subway_81-717_mvm.Buttons.SquareARS.!LampLRS": "ЛРС: Светлинен индикатор за скорост (следваща сегментна скорост, равна или по-голяма от сегашната)"
}
]]
