return [[
{
    "Lang": "bg",
    "Name": "Български",


    "Entities.gmod_subway_em508.Buttons.Back.BackDoor": "Задна врата",
    "Entities.gmod_subway_em508.Buttons.HelperPanel.R_Program1Set": "Програма 1",
    "Entities.gmod_subway_em508.Buttons.HelperPanel.R_Program2Set": "Програма 2: Аварийна",
    "Entities.gmod_subway_em508.Buttons.HelperPanel.VDLSet": "ВДЛ: Включвател леви врати",
    "Entities.gmod_subway_em508.Buttons.HelperPanel.VUD2Toggle": "ВУД2: Включвател управление на врати (затваряне на врати)",
    "Entities.gmod_subway_em508.Buttons.AV2.RSTToggle": "РСТ: Радиостанция",
    "Entities.gmod_subway_em508.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Заден Краищен кран за налягане на метровлака",
    "Entities.gmod_subway_em508.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Заден Краищен кран за налягане на спирачките",
    "Entities.gmod_subway_em508.Buttons.AVU.AVULight": "Лампа:Включен АВУ (Автоматичен прекъсвач на управлението)",
    "Entities.gmod_subway_em508.Buttons.AVU.OtklAVUToggle": "Принудително изключване на Автоматичния прекъсвач на управлението (неисправност на АВУ)",
    "Entities.gmod_subway_em508.Buttons.Back2.!HVFuses": "Блок с бушони",
    "Entities.gmod_subway_em508.Buttons.Back2.!Relays": "Кутия с апарати за зареждане на батериите и въздохоразпределители на вратите",
    "Entities.gmod_subway_em508.Buttons.Back2.!Heater": "Печка",
    "Entities.gmod_subway_em508.Buttons.Main.DoorSelectToggle": "Превключвател: Избор за посока на отваряне на вратите",
    "Entities.gmod_subway_em508.Buttons.Main.DIPonSet": "Вкл. Осв.: Включване на освтелението",
    "Entities.gmod_subway_em508.Buttons.Main.DIPoffSet": "Изкл. Осв.: Изключване на осветлението",
    "Entities.gmod_subway_em508.Buttons.Main.VozvratRPSet": "ВРП: Рестартиране на релето против претоварване(РП)",
    "Entities.gmod_subway_em508.Buttons.Main.KSNSet": "КСН:Принудително включване РП на неизправния вагон (Сигнализация за неизправност)",
    "Entities.gmod_subway_em508.Buttons.Main.KRZDSet": "КРЗД: Копче за резервно затваряне на вратите",
    "Entities.gmod_subway_em508.Buttons.Main.KSDSet": "КСД: Контролер за състояние на вратите(проверка на сигнализация на вратите)",
    "Entities.gmod_subway_em508.Buttons.Main.KDPSet": "КДП: Дясни врати",
    "Entities.gmod_subway_em508.Buttons.Main.KDLSet": "КДЛ: Копче за левите врати",
    "Entities.gmod_subway_em508.Buttons.Main.RezMKSet": "РМК: Резервно пускане на мотор-компрессора",
    "Entities.gmod_subway_em508.Buttons.Main.KU1Toggle": "МК: Включвател на мотор-компрессора",
    "Entities.gmod_subway_em508.Buttons.Main.VUD1Toggle": "ВУД: Включвател за затваряне на вратите",
    "Entities.gmod_subway_em508.Buttons.AV1.VU3Toggle": "ВУ3: Осветление на кабината",
    "Entities.gmod_subway_em508.Buttons.AV1.VU2Toggle": "ВУ2: Аварийно осветление",
    "Entities.gmod_subway_em508.Buttons.AV1.VU1Toggle": "ВУ1: Печка за отопление на кабината",
    "Entities.gmod_subway_em508.Buttons.Back1.!ULSPM": "УАСПМ (Устройство за аварийно свръзване Пасажер-Машинист )",
    "Entities.gmod_subway_em508.Buttons.Back1.!TonalARS": "Звънец",
    "Entities.gmod_subway_em508.Buttons.Back1.!PressureRelay": "Регулатор на налягането",
    "Entities.gmod_subway_em508.Buttons.Back1.!Reproductor": "Високоговорител",
    "Entities.gmod_subway_em508.Buttons.Back1.!LVFuses": "Предпазител с бушони на нисък волтаж",
    "Entities.gmod_subway_em508.Buttons.Back1.R_UNchToggle": "Захранване на Информатор",
    "Entities.gmod_subway_em508.Buttons.Lamp.L_3Toggle": "Лампа: Подсветка на измервателните прибори",
    "Entities.gmod_subway_em508.Buttons.DriverValveTLDisconnect.DriverValveTLDisconnectToggle": "Двупозиционен кран за налягането на влака",
    "Entities.gmod_subway_em508.Buttons.VU.VUToggle": "ВУ: Превключвател за управление на вагона",
    "Entities.gmod_subway_em508.Buttons.PneumaticManometer.!LinesPressure": "Налягане на метровлака (червена стрелка: спирачна, черна: вагонна)",
    "Entities.gmod_subway_em508.Buttons.Stopkran.EmergencyBrakeValveToggle": "Стопкран",
    "Entities.gmod_subway_em508.Buttons.LAMPS.SN": "Индикатор: Cигнализация за неисправност",
    "Entities.gmod_subway_em508.Buttons.LAMPS.RedRP": "Индикатор: Червена лампа за претоварване на релето",
    "Entities.gmod_subway_em508.Buttons.LAMPS.SD": "Индикатор: Сигнализация за вратите",
    "Entities.gmod_subway_em508.Buttons.LAMPS.GreenRP": "Индикатор: Зелена лампа за пренатоварване на релето",
    "Entities.gmod_subway_em508.Buttons.LAMPS.UKS": "Индикатор: Устройство за контрол на скоростта УКС-20М",
    "Entities.gmod_subway_em508.Buttons.LAMPS.Red": "Индикатор: Нагревател на кабината",
    "Entities.gmod_subway_em508.Buttons.LAMPS.AGS": "Лампа: Работа на АГС (Автоматически смаслител на коловоза)",
    "Entities.gmod_subway_em508.Buttons.UAVAPanel.UAVAToggle": "УАБА: Универсален Автоматичен Бушон за Автостоп (изключване на автостопа)",
    "Entities.gmod_subway_em508.Buttons.UAVAPanel.UAVAContactSet": "УАБА: Универсален Автоматичен Бушон за Автостоп (възтановяване на контактите)",
    "Entities.gmod_subway_em508.Buttons.PneumaticPanels.!CylinderPressure": "Манометър на спирачната система(ТЦ)",
    "Entities.gmod_subway_em508.Buttons.Battery.VBToggle": "АБ: Ключ на батериите (помощни с нисък волтаж)",
    "Entities.gmod_subway_em508.Buttons.Battery.R_RadioToggle": "Захранване на Информатора +50В",
    "Entities.gmod_subway_em508.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Преден Краищен кран за налягане на спирачките",
    "Entities.gmod_subway_em508.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Преден Краищен кран за налягане на метровлака",
    "Entities.gmod_subway_em508.Buttons.ASNP.R_ASNPMenuSet": "Информатор: Меню",
    "Entities.gmod_subway_em508.Buttons.ASNP.R_ASNPUpSet": "Информатор: Нагоре",
    "Entities.gmod_subway_em508.Buttons.ASNP.R_ASNPDownSet": "Информатор: Надолу",
    "Entities.gmod_subway_em508.Buttons.ASNP.R_ASNPOnToggle": "Информатор: Копче за включване/изключване",
    "Entities.gmod_subway_em508.Buttons.VU1.KRPSet": "РРП: Аварииен старт ",
    "Entities.gmod_subway_em508.Buttons.GV.GVToggle": "Превключвател за високо напрежение",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.IGLA1USet": "ИГЛА: Първо копче: нагоре",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.IGLA1Set": "ИГЛА: Първо копче",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.IGLA1DSet": "ИГЛА: Първо копче: надолу",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.IGLA2USet": "ИГЛА: Второ копче: нагоре",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.IGLA2Set": "ИГЛА: Второ копче",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.IGLA2DSet": "ИГЛА: Второ копче: надолу",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.!IGLASR": "ИГЛА: SR",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.!IGLARX": "ИГЛА: RX",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.!IGLAErr": "ИГЛА: Отказ",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.!IGLAOSP": "ИГЛА: ОСП (пожарогасителна уредба)",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.!IGLAPI": "ИГЛА: ПИ (индикатор за пожароопасност)",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.!IGLAOff": "ИГЛА: Изкл.",
    "Entities.gmod_subway_em508.Buttons.PassengerDoor.PassengerDoor": "Пасажерска врата за кабината на машиниста",
    "Entities.gmod_subway_em508.Buttons.InfoTableSelect.PrevSign": "Предишна табелка",
    "Entities.gmod_subway_em508.Buttons.InfoTableSelect.NextSign": "Следваща табелка",
    "Entities.gmod_subway_em508.Buttons.InfoTableSelect.Num2P": "Маршрутен номер: Увеличи 2-рото число",
    "Entities.gmod_subway_em508.Buttons.InfoTableSelect.Num2M": "Маршрутен номер: Намали 2-рото число",
    "Entities.gmod_subway_em508.Buttons.InfoTableSelect.Num1P": "Маршрутен номер: Увеличи 1-вото число",
    "Entities.gmod_subway_em508.Buttons.InfoTableSelect.Num1M": "Маршрутен номер: Намали 1-вото число",
    "Entities.gmod_subway_em508.Buttons.Front.FrontDoor": "Предна врата",
    "Entities.gmod_subway_em508.Buttons.KRR.KRRSet": "KРР: Копче за включване на реверсора",
    "Entities.gmod_subway_em508.Buttons.AGS.VUSToggle": "Ключ: Къси фарове(надолу)/Дълги фарове(нагоре)",
    "Entities.gmod_subway_em508.Buttons.CabinDoor.CabinDoor": "Врата за кабината на машиниста",
    "Entities.gmod_subway_em508.Buttons.PassengerDoor1.PassengerDoor": "Врата за кабината машиниста от салона",
    "Entities.gmod_subway_em508.Buttons.ParkingBrake.ParkingBrakeLeft": "Завъртване на колелото за ръчно налягане на накладките(наляво)",
    "Entities.gmod_subway_em508.Buttons.ParkingBrake.ParkingBrakeRight": "Завъртване на колелото за ръчно налягане на накладките(надясно)",
    "Entities.gmod_subway_em508.Buttons.AVMain.AV8BToggle": "АВ-8Б: Автоматичен бушон за схемите (Вспомагателен усилвател на волтажа)",
    "Entities.gmod_subway_em508.Buttons.Back3.!RTM": "Радиостанция за свързване с диспетчера",
    "Entities.gmod_subway_em508.Buttons.Back3.!ULSPMSpeaker": "Блок на високоговорителя за аварийно свързване Пасажер-Машинист",
    "Entities.gmod_subway_em508.Buttons.Back3.!Amplifier": "Блок усилителя поездной радиостанции",
    "Entities.gmod_subway_em508.Buttons.DriverValveBLDisconnect.DriverValveBLDisconnectToggle": "Двупозиционен кран за налягането на влака",
    "Entities.gmod_subway_em508.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Изключване на вентилационната уредба",



    "Entities.gmod_subway_em508_int.Buttons.Stopkran.EmergencyBrakeValveToggle": "Стопкран",
    "Entities.gmod_subway_em508_int.Buttons.Back.BackDoor": "Задна врата",
    "Entities.gmod_subway_em508_int.Buttons.HelperPanel.R_Program1Set": "Програма 1",
    "Entities.gmod_subway_em508_int.Buttons.HelperPanel.R_Program2Set": "Програма 2:Аварийна",
    "Entities.gmod_subway_em508_int.Buttons.HelperPanel.VDLSet": "ВДЛ: Включвател леви врати",
    "Entities.gmod_subway_em508_int.Buttons.HelperPanel.VUD2Toggle": "ВУД2: Включвател управление на врати (затваряне на врати)",
    "Entities.gmod_subway_em508_int.Buttons.DriverValveBLDisconnect.DriverValveBLDisconnectToggle": "Двупозиционен кран за налягането на влака",
    "Entities.gmod_subway_em508_int.Buttons.Battery.VBToggle": "АБ: АБ: Ключ на батериите (помощни с нисък волтаж)",
    "Entities.gmod_subway_em508_int.Buttons.Battery.R_RadioToggle": "Захранване на Информатора +50В",
    "Entities.gmod_subway_em508_int.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "Преден Краищен кран за налягане на спирачките",
    "Entities.gmod_subway_em508_int.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Преден Краищен кран за налягане на метровлака",
    "Entities.gmod_subway_em508_int.Buttons.AirDistributor.AirDistributorDisconnectToggle": "Изключване на вентилационната уредба",
    "Entities.gmod_subway_em508_int.Buttons.PassengerDoor.PassengerDoor": "Пасажерска врата за кабината на машиниста",
    "Entities.gmod_subway_em508_int.Buttons.VU1.KRPSet": "РРП: Аварииен старт ",
    "Entities.gmod_subway_em508_int.Buttons.UAVAPanel.UAVAToggle": "УАБА: Универсален Автоматичен Бушон за Автостоп (изключване на автостопа)",
    "Entities.gmod_subway_em508_int.Buttons.UAVAPanel.UAVAContactSet": "УАБА: Универсальный Автоматический Выключатель Автостопа (восстановление контактов)",
    "Entities.gmod_subway_em508_int.Buttons.Front.FrontDoor": "Предна врата",
    "Entities.gmod_subway_em508_int.Buttons.Tsepi.!BatteryVoltage": "Напрежение на батериите",
    "Entities.gmod_subway_em508_int.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "Заден Краищен кран за налягане на метровлака",
    "Entities.gmod_subway_em508_int.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "Заден Краищен кран за налягане на спирачките",
    "Entities.gmod_subway_em508_int.Buttons.InfoTableSelect.PrevSign": "Предишна табелка",
    "Entities.gmod_subway_em508_int.Buttons.InfoTableSelect.NextSign": "Следваща табелка",
    "Entities.gmod_subway_em508_int.Buttons.InfoTableSelect.Num2P": "Маршрутен номер: Увеличи 2-рото число",
    "Entities.gmod_subway_em508_int.Buttons.InfoTableSelect.Num2M": "Маршрутен номер: Намали 2-рото число",
    "Entities.gmod_subway_em508_int.Buttons.InfoTableSelect.Num1P": "Маршрутен номер: Увеличи 1-вото число",
    "Entities.gmod_subway_em508_int.Buttons.InfoTableSelect.Num1M": "Маршрутен номер: Намали 1-вото число",
    "Entities.gmod_subway_em508_int.Buttons.Back2.!HVFuses": "Блок с бушони",
    "Entities.gmod_subway_em508_int.Buttons.Back2.!Relays": "Кутия с апарати за зареждане на батериите и въздохоразпределители на вратите",
    "Entities.gmod_subway_em508_int.Buttons.Back2.!Heater": "Печка",
    "Entities.gmod_subway_em508_int.Buttons.Main.GreenRP": "Индикатор: Зелена лампа за пренатоварване на релето",
    "Entities.gmod_subway_em508_int.Buttons.Main.RedRP": "Индикатор: Червена лампа за претоварване на релето",
    "Entities.gmod_subway_em508_int.Buttons.Main.SD": "Индикатор: Сигнализация за вратите",
    "Entities.gmod_subway_em508_int.Buttons.Main.DIPonSet": "Вкл. Осв.: Включване на осветлението",
    "Entities.gmod_subway_em508_int.Buttons.Main.DIPoffSet": "Изкл. Осв.: Изключване на осветлението",
    "Entities.gmod_subway_em508_int.Buttons.Main.VozvratRPSet": "ВРП: Рестартиране на релето против претоварване(РП)",
    "Entities.gmod_subway_em508_int.Buttons.Main.KSNSet": "КСН:Принудително включване РП на неизправния вагон (Сигнализация за неизправност)",
    "Entities.gmod_subway_em508_int.Buttons.Main.KRZDSet": "КРЗД: Копче за резервно затваряне на вратите",
    "Entities.gmod_subway_em508_int.Buttons.Main.KDPSet": "КДП: Дясни врати",
    "Entities.gmod_subway_em508_int.Buttons.Main.KDLSet": "КДЛ: Копче за левите врати",
    "Entities.gmod_subway_em508_int.Buttons.Main.KU1Toggle": "МК: Включвател на мотор-компрессора",
    "Entities.gmod_subway_em508_int.Buttons.Main.VUD1Toggle": "ВУД: Включвател за затваряне на вратите",
    "Entities.gmod_subway_em508_int.Buttons.AV1.VU3Toggle": "ВУ3: Осветление на кабината",
    "Entities.gmod_subway_em508_int.Buttons.AV1.VU2Toggle": "ВУ2: Аварийно осветление",
    "Entities.gmod_subway_em508_int.Buttons.AV1.VU1Toggle": "ВУ1: Печка за отопление на кабината",
    "Entities.gmod_subway_em508_int.Buttons.AVMain.AV8BToggle": "АВ-8Б: Автоматичен бушон за схемите (Вспомагателен усилвател на волтажа)",
    "Entities.gmod_subway_em508_int.Buttons.CabinDoor.CabinDoor": "Врата за кабината на машиниста",
    "Entities.gmod_subway_em508_int.Buttons.Lamp.L_3Toggle": "Лампа: Подсветка на измервателните прибори",
    "Entities.gmod_subway_em508_int.Buttons.PassengerDoor1.PassengerDoor": "Врата за кабината машиниста от салона",
    "Entities.gmod_subway_em508_int.Buttons.DriverValveTLDisconnect.DriverValveTLDisconnectToggle": "Двупозиционен кран за налягането на влака",
    "Entities.gmod_subway_em508_int.Buttons.GV.GVToggle": "Превключвател за високо напрежение",
    "Entities.gmod_subway_em508_int.Buttons.VU.VUToggle": "ВУ: Превключвател за управление на вагона",
    "Entities.gmod_subway_em508_int.Buttons.PneumaticPanels.!CylinderPressure": "Манометър на спирачната система(ТЦ)",
    "Entities.gmod_subway_em508_int.Buttons.ParkingBrake.ParkingBrakeLeft": "Завъртване на колелото за ръчно налягане на накладките(наляво)",
    "Entities.gmod_subway_em508_int.Buttons.ParkingBrake.ParkingBrakeRight": "Завъртване на колелото за ръчно налягане на накладките(надясно)",
    "Entities.gmod_subway_em508_int.Buttons.PneumaticManometer.!LinesPressure": "Налягане на метровлака (червена стрелка: спирачна, черна: вагонна)"
}
]]
