return [[
{
	"Lang": "bg",
	"Name": "Български",

	"Spawner.Title": "Spawner на влак",
	"Spawner.Trains1": "Влакове",
	"Spawner.Trains2": "Максимално за теб",
	"Spawner.WagNum": "Вагони",
	"Spawner.AutoCouple": "Автоматична двойка вагони",

	"Entities.gmod_subway_81-717_mvm.Spawner.Texture.Name": "Облик",
	"Entities.gmod_subway_81-717_mvm.Spawner.PassTexture.Name": "Текстура на интериор",
	"Entities.gmod_subway_81-717_mvm.Spawner.CabTexture.Name": "Текстура на кабина",
	"Entities.gmod_subway_81-717_mvm.Spawner.Announcer.Name": "Информатор",
	"Entities.gmod_subway_81-717_mvm.Spawner.Lighter.Name": "Lighter",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.Name": "Тип панел АРС",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.1": "Стандартно(квадратни индикатори)",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.2": "Стандартно(кръгли индикатори)",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.3": "Киев/СПБ",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.4": "Стар АРС",
	"Entities.gmod_subway_81-717_mvm.Spawner.Cran.Name": "Тип спирачна ръчка",
	"Entities.gmod_subway_81-717_mvm.Spawner.Cran.1": "334",
	"Entities.gmod_subway_81-717_mvm.Spawner.Cran.2": "013",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.Name": "Тип маска",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.1": "2-2",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.2": "2-2-2",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.3": "1-4-1 бъмпър 1",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.4": "1-4-1 бъмпър 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.5": "1-1",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.6": "Ретро",
	"Entities.gmod_subway_81-717_mvm.Spawner.LED.Name": "ЛЕД осветление на фаровете",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.Name": "Тип БПСН",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.1": "Стар звук висок тон",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.2": "Стар звук среден тон",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.3": "Стандартно(от СПБ)",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.4": "Стандартно(ТКЛ)",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.5": "Стандартно",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.6": "Киев",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.7": "Стар",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.8": "Стандартно 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.9": "Стандартно 3",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.10": "Без звук(БПН-115)",
	"Entities.gmod_subway_81-717_mvm.Spawner.NewKV.Name": "Нов модел на контролера",
	"Entities.gmod_subway_81-717_mvm.Spawner.HornType.Name": "СПБ клаксон",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.Name": "Звънец",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.1": "Стар",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.2": "Стандартно с нисък тон",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.3": "Стандартно с висок тон",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.4": "Стандартно прекъсващ с нисък  тон",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.5": "Стандартно прекъсващ с висок  тон",
	"Entities.gmod_subway_81-717_mvm.Spawner.NM.Name": "Налягане на влака",
	"Entities.gmod_subway_81-717_mvm.Spawner.Battery.Name": "Захранване",
	"Entities.gmod_subway_81-717_mvm.Spawner.Switches.Name": "Прекъсвачи на схеми на",
	"Entities.gmod_subway_81-717_mvm.Spawner.SwitchesR.Name": "Произволни прекъсвачи на схеми",
	"Entities.gmod_subway_81-717_mvm.Spawner.DoorsL.Name": "Отваряне на леви врати",
	"Entities.gmod_subway_81-717_mvm.Spawner.DoorsR.Name": "Отваряне на десни врати",
	"Entities.gmod_subway_81-717_mvm.Spawner.GV.Name": "ВН ключ",
	"Entities.gmod_subway_81-717_mvm.Spawner.PB.Name": "Ръчна спирачка",
	"Entities.gmod_subway_81-717_mvm.Spawner.BortLampType.Name": "Тип стационарни лампи",
	"Entities.gmod_subway_81-717_mvm.Spawner.BortLampType.1": "Хоризонтални",
	"Entities.gmod_subway_81-717_mvm.Spawner.BortLampType.2": "Вертикални",
	"Entities.gmod_subway_81-717_mvm.Spawner.MVM.Name": "МВМ табела",
	"Entities.gmod_subway_81-717_mvm.Spawner.HandRail.Name": "Тип парапети",
	"Entities.gmod_subway_81-717_mvm.Spawner.HandRail.1": "Стари",
	"Entities.gmod_subway_81-717_mvm.Spawner.HandRail.2": "Нови",
	"Entities.gmod_subway_81-717_mvm.Spawner.SeatType.Name": "Тип седалки",
	"Entities.gmod_subway_81-717_mvm.Spawner.SeatType.1": "Стари",
	"Entities.gmod_subway_81-717_mvm.Spawner.SeatType.2": "Нови",
	"Entities.gmod_subway_81-717_mvm.Spawner.LampType.Name": "Тип осветление в мотрисата",
	"Entities.gmod_subway_81-717_mvm.Spawner.LampType.1": "Тип 1",
	"Entities.gmod_subway_81-717_mvm.Spawner.LampType.2": "Тип 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.LampType.3": "Тип 3",
	"Entities.gmod_subway_81-717_mvm.Spawner.Breakers.Name": "Десни прекъсвачи на схеми",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.Name": "Тип рекламни табла в мотрисата",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.1": "Тип 1",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.2": "Тип 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.3": "Тип 3",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.4": "Без рекламни табла",

	"Entities.gmod_subway_81-720.Spawner.Texture.Name": "Облик",
	"Entities.gmod_subway_81-720.Spawner.PassTexture.Name": "Текстура на интериор",
	"Entities.gmod_subway_81-720.Spawner.CabTexture.Name": "Текстура на кабина",
	"Entities.gmod_subway_81-720.Spawner.Announcer.Name": "Информатор",
	"Entities.gmod_subway_81-720.Spawner.Scheme.Name": "Схема на линията",
	"Entities.gmod_subway_81-720.Spawner.PassSchemesInvert.Name": "Обърната схема",
	"Entities.gmod_subway_81-720.Spawner.NM.Name": "Налягане на влака",
	"Entities.gmod_subway_81-720.Spawner.Battery.Name": "Захранване",
	"Entities.gmod_subway_81-720.Spawner.BRU.Name": "ВН ключ",
	"Entities.gmod_subway_81-720.Spawner.PVZR.Name": "Прекъсвачи на схеми на панела за произволна защита на влака",
	"Entities.gmod_subway_81-720.Spawner.PPZ.Name": "Включи всички прекъсвачи на схеми на влака",
	"Entities.gmod_subway_81-720.Spawner.PPZDepot.Name": "Забрани всички прекъсвачи на схеми като в депо",
	"Entities.gmod_subway_81-720.Spawner.PPZR.Name": "Прекъсвачи на схеми на панела за произволна зашита на вагоните",
	"Entities.gmod_subway_81-720.Spawner.DoorsL.Name": "Отваряне на леви врати",
	"Entities.gmod_subway_81-720.Spawner.DoorsR.Name": "Отваряне на десни врати",

	"Entities.gmod_subway_81-722.Spawner.Texture.Name": "Облик",
	"Entities.gmod_subway_81-722.Spawner.PassTexture.Name": "Текстура на интериор",
	"Entities.gmod_subway_81-722.Spawner.CabTexture.Name": "Текстура на кабина",
	"Entities.gmod_subway_81-722.Spawner.Announcer.Name": "Информатор",
	"Entities.gmod_subway_81-722.Spawner.Scheme.Name": "Схема на линията",
	"Entities.gmod_subway_81-722.Spawner.SarmatInvert.Name": "Обърната схема",
	"Entities.gmod_subway_81-722.Spawner.NM.Name": "Налягане на влака",
	"Entities.gmod_subway_81-722.Spawner.Battery.Name": "Захранване",
	"Entities.gmod_subway_81-722.Spawner.Switches.Name": "Включи всички прекъсвачи на схеми на влака",
	"Entities.gmod_subway_81-722.Spawner.SwitchesR.Name": "Произволни прекъсвачи на схеми",
	"Entities.gmod_subway_81-722.Spawner.DoorsL.Name": "Отваряне на леви врати",
	"Entities.gmod_subway_81-722.Spawner.DoorsR.Name": "Отваряне на десни врати",

	"Entities.gmod_subway_ezh.Spawner.Texture.Name": "Облик",
	"Entities.gmod_subway_ezh.Spawner.PassTexture.Name": "Текстура на интериор",
	"Entities.gmod_subway_ezh.Spawner.CabTexture.Name": "Текстура на кабина",
	"Entities.gmod_subway_ezh.Spawner.Announcer.Name": "Информатор",
	"Entities.gmod_subway_ezh.Spawner.HornType.Name": "СПБ клаксон",
	"Entities.gmod_subway_ezh.Spawner.NM.Name": "Налягане на влака",
	"Entities.gmod_subway_ezh.Spawner.Battery.Name": "Включи захранването",
	"Entities.gmod_subway_ezh.Spawner.AV8B.Name": "Включи AV8B",
	"Entities.gmod_subway_ezh.Spawner.DoorsL.Name": "Отваряне на леви врати",
	"Entities.gmod_subway_ezh.Spawner.DoorsR.Name": "Отваряне на десни врати",
	"Entities.gmod_subway_ezh.Spawner.GV.Name": "Включи ВН ключ",

	"Entities.gmod_subway_em508.Spawner.Texture.Name": "Облик",
	"Entities.gmod_subway_em508.Spawner.PassTexture.Name": "Текстура на интериор",
	"Entities.gmod_subway_em508.Spawner.CabTexture.Name": "Текстура на кабина",
	"Entities.gmod_subway_em508.Spawner.Announcer.Name": "Информатор",
	"Entities.gmod_subway_em508.Spawner.HornType.Name": "СПБ клаксон",
	"Entities.gmod_subway_em508.Spawner.NM.Name": "Налягане на влака",
	"Entities.gmod_subway_em508.Spawner.Battery.Name": "Включи захранването",
	"Entities.gmod_subway_em508.Spawner.AV8B.Name": "Включи AV8B",
	"Entities.gmod_subway_em508.Spawner.DoorsL.Name": "Отваряне на леви врати",
	"Entities.gmod_subway_em508.Spawner.DoorsR.Name": "Отваряне на десни врати",
	"Entities.gmod_subway_em508.Spawner.GV.Name": "Включи ВН ключ",

	"Entities.gmod_subway_ezh3.Spawner.Texture.Name": "Облик",
	"Entities.gmod_subway_ezh3.Spawner.PassTexture.Name": "Текстура на интериор",
	"Entities.gmod_subway_ezh3.Spawner.CabTexture.Name": "Текстура на кабина",
	"Entities.gmod_subway_ezh3.Spawner.Announcer.Name": "Информатор",
	"Entities.gmod_subway_ezh3.Spawner.HornType.Name": "СПБ клаксон",
	"Entities.gmod_subway_ezh3.Spawner.NM.Name": "Налягане на влака",
	"Entities.gmod_subway_ezh3.Spawner.Battery.Name": "Включи захранването",
	"Entities.gmod_subway_ezh3.Spawner.AV8B.Name": "Включи AV8B",
	"Entities.gmod_subway_ezh3.Spawner.DoorsL.Name": "Отваряне на леви врати",
	"Entities.gmod_subway_ezh3.Spawner.DoorsR.Name": "Отваряне на десни врати",
	"Entities.gmod_subway_ezh3.Spawner.GV.Name": "Включи ВН ключ",

	"Entities.gmod_subway_81-717_lvz.Spawner.Texture.Name": "Облик",
	"Entities.gmod_subway_81-717_lvz.Spawner.PassTexture.Name": "Текстура на интериор",
	"Entities.gmod_subway_81-717_lvz.Spawner.CabTexture.Name": "Текстура на кабина",
	"Entities.gmod_subway_81-717_lvz.Spawner.Announcer.Name": "Информатор",
	"Entities.gmod_subway_81-717_lvz.Spawner.Lighter.Name": "Запалка",
	"Entities.gmod_subway_81-717_lvz.Spawner.Cran.Name": "Тип спирачна ръчка",
	"Entities.gmod_subway_81-717_lvz.Spawner.Cran.1": "334",
	"Entities.gmod_subway_81-717_lvz.Spawner.Cran.2": "013",
	"Entities.gmod_subway_81-717_lvz.Spawner.MaskType.Name": "Тип маска",
	"Entities.gmod_subway_81-717_lvz.Spawner.MaskType.1": "1-4-1",
	"Entities.gmod_subway_81-717_lvz.Spawner.MaskType.2": "2-2(надолу)-2",
	"Entities.gmod_subway_81-717_lvz.Spawner.MaskType.3": "2-2",
	"Entities.gmod_subway_81-717_lvz.Spawner.MaskType.4": "2-2-2",
	"Entities.gmod_subway_81-717_lvz.Spawner.MaskType.5": "1-3-1",
	"Entities.gmod_subway_81-717_lvz.Spawner.LED.Name": "ЛЕД осветление на мотрисата",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.Name": "Тип БПСН",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.1": "Стар звук висок тон",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.2": "Стар звук среден тон",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.3": "Стандартно(от СПБ)",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.4": "Стандартно(ТКЛ)",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.5": "Стандартно",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.6": "Киев",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.7": "Стар",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.8": "Стандартно 2",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.9": "Стандартно 3",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.10": "Без звук(БПН-115)",
    "Entities.gmod_subway_81-717_lvz.Spawner.NewKV.Name": "Нов модел на контролера",
    "Entities.gmod_subway_81-717_lvz.Spawner.HornType.Name": "СПБ клаксон",
    "Entities.gmod_subway_81-717_lvz.Spawner.RingType.Name": "Звънец",
    "Entities.gmod_subway_81-717_lvz.Spawner.RingType.1": "Стар",
    "Entities.gmod_subway_81-717_lvz.Spawner.RingType.2": "Стандартно с нисък тон",
    "Entities.gmod_subway_81-717_lvz.Spawner.RingType.3": "Стандартно с висок тон",
    "Entities.gmod_subway_81-717_lvz.Spawner.RingType.4": "Стандартно прекъсващ с нисък тон",
    "Entities.gmod_subway_81-717_lvz.Spawner.RingType.5": "Стандартно прекъсващ с висок тон",
    "Entities.gmod_subway_81-717_lvz.Spawner.NM.Name": "Налягане на влака",
    "Entities.gmod_subway_81-717_lvz.Spawner.Battery.Name": "Включи захранването",
    "Entities.gmod_subway_81-717_lvz.Spawner.Switches.Name": "Прекъсвачи на схеми на",
    "Entities.gmod_subway_81-717_lvz.Spawner.SwitchesR.Name": "Произволни прекъсвачи на схеми",
    "Entities.gmod_subway_81-717_lvz.Spawner.DoorsL.Name": "Отваряне на леви врати",
    "Entities.gmod_subway_81-717_lvz.Spawner.DoorsR.Name": "Отваряне на десни врати",
    "Entities.gmod_subway_81-717_lvz.Spawner.GV.Name": "Включи ВН ключ",
    "Entities.gmod_subway_81-717_lvz.Spawner.PB.Name": "Включи ръчна спирачка",
    "Entities.gmod_subway_81-717_lvz.Spawner.BortLampType.Name": "Тип стационарни лампи",
    "Entities.gmod_subway_81-717_lvz.Spawner.BortLampType.1": "Хоризонтални",
    "Entities.gmod_subway_81-717_lvz.Spawner.BortLampType.2": "Вертикални",
    "Entities.gmod_subway_81-717_lvz.Spawner.HandRail.Name": "Тип парапети",
    "Entities.gmod_subway_81-717_lvz.Spawner.HandRail.1": "Стари",
    "Entities.gmod_subway_81-717_lvz.Spawner.HandRail.2": "Нови",
    "Entities.gmod_subway_81-717_lvz.Spawner.SeatType.Name": "Тип седалки",
    "Entities.gmod_subway_81-717_lvz.Spawner.SeatType.1": "Стари",
    "Entities.gmod_subway_81-717_lvz.Spawner.SeatType.2": "Нови",
    "Entities.gmod_subway_81-717_lvz.Spawner.LampType.Name": "Тип лампи",
    "Entities.gmod_subway_81-717_lvz.Spawner.LampType.1": "Тип 1",
    "Entities.gmod_subway_81-717_lvz.Spawner.LampType.2": "Тип 2",
    "Entities.gmod_subway_81-717_lvz.Spawner.LampType.3": "Тип 3",
    "Entities.gmod_subway_81-717_lvz.Spawner.Breakers.Name": "Десни прекъсвачи на схеми",
    "Entities.gmod_subway_81-717_lvz.Spawner.Adverts.Name": "Тип рекламни табла в мотрисата",
    "Entities.gmod_subway_81-717_lvz.Spawner.Adverts.1": "Тип 1",
    "Entities.gmod_subway_81-717_lvz.Spawner.Adverts.2": "Тип 2",
    "Entities.gmod_subway_81-717_lvz.Spawner.Adverts.3": "Тип 3",
    "Entities.gmod_subway_81-717_lvz.Spawner.Adverts.4": "Без рекламни табла",

	"Entities.gmod_subway_81-703.Spawner.Texture.Name": "Облик",
	"Entities.gmod_subway_81-703.Spawner.PassTexture.Name": "Текстура на интериор",
	"Entities.gmod_subway_81-703.Spawner.CabTexture.Name": "Текстура на кабина",
	"Entities.gmod_subway_81-703.Spawner.Announcer.Name": "Информатор",
	"Entities.gmod_subway_81-703.Spawner.HornType.Name": "СПБ клаксон",
	"Entities.gmod_subway_81-703.Spawner.NM.Name": "Налягане на влака",
	"Entities.gmod_subway_81-703.Spawner.Battery.Name": "Включи захранването",
	"Entities.gmod_subway_81-703.Spawner.AV8B.Name": "Включи AV8B",
	"Entities.gmod_subway_81-703.Spawner.DoorsL.Name": "Отваряне на леви врати",
	"Entities.gmod_subway_81-703.Spawner.DoorsR.Name": "Отваряне на десни врати",
	"Entities.gmod_subway_81-703.Spawner.GV.Name": "Включи ВН ключ",

	"Spawner.Close": "Затвори",
	"Spawner.Spawn": "Готово"
}
]]
