return [[
{
	"Lang": "de",
	"Name": "Deutsch",
	
	"Panel.Admin": "Admin",
	"Panel.Client": "Client",
	"Panel.DrawDebugInfo": "Entwickler Info",
	"Panel.DisableCamAccel": "Deaktivere Bewegende Camera",
	"Panel.DisableHoverText": "Deaktivere Info Text",
	"Panel.DrawCams": "Render Kameras",
	"Panel.FOV": "Sichtfeld",

	"Train.Common.Camera0": "Fahrersitz",

	"Train.Buttons.Sealed": "Geschlossen",

	"Entities.gmod_subway_base.Name": "U-Bahn Basis",
	"Entities.gmod_subway_81-703.Name": "E (Triebkopf)",
	"Entities.gmod_subway_81-703_2.Name": "E (Zwischenwagen)",
	"Entities.gmod_subway_81-717_mvm.Name": "81-717(MVM)",
	"Entities.gmod_subway_81-717_lvz.Name": "81-717(LVZ)",
	"Entities.gmod_subway_81-714_mvm.Name": "81-714(MVM)",
	"Entities.gmod_subway_81-714_lvz.Name": "81-714(LVZ)",
	"Entities.gmod_subway_81-7036.Name": "81-7036 (Dummy)",
	"Entities.gmod_subway_81-7037.Name": "81-7037 (Dummy)",
	"Entities.gmod_subway_81-720.Name": "81-720 (Triebkopf)",
	"Entities.gmod_subway_81-721.Name": "81-721 (Zwischenwagen)",
	"Entities.gmod_subway_81-722.Name": "81-722 (Triebkopf)",
	"Entities.gmod_subway_81-723.Name": "81-723 (Zwischenwagen mit Motor)",
	"Entities.gmod_subway_81-724.Name": "81-724 (Zwischenwagen ohne Motor)",
	"Entities.gmod_subway_e.Name": "E",
	"Entities.gmod_subway_em.Name": "Em",
	"Entities.gmod_subway_ema.Name": "Ema",
	"Entities.gmod_subway_ezh.Name": "Ezh",
	"Entities.gmod_subway_ezh1.Name": "Ezh1",
	"Entities.gmod_subway_em508.Name": "Em-508",
	"Entities.gmod_subway_em508_int.Name": "Em-508 (Zwischenwagen)",
	"Entities.gmod_subway_ezh3.Name": "Ezh3",
	"Entities.gmod_subway_ezh3ru1.Name": "Ezh3 RU1",
	"Entities.gmod_subway_ema508t.Name": "Em-508t",
	"Entities.gmod_subway_tatra_t3.Name": "Tatra T3",
	"Entities.gmod_subway_ai.Name": "KI Zug",

	"Entities.gmod_train_bogey.Name": "Drehgestell",
	"Entities.gmod_train_couple.Name": "Kupplung",

	"Entities.gmod_track_pui.Name": "PUI Uhr",
	"Entities.gmod_track_mus_elektronika7.Name": "Digitale Uhr",
	"Entities.gmod_mus_clock_analog.Name": "Analoge Uhr",
	"Entities.gmod_track_clock_time.Name": "Grosse Uhr",
	"Entities.gmod_track_clock_small.Name": "Kleiner Intervallanzeiger",
	"Entities.gmod_track_clock_interval.Name": "Grosser Intervallanzeiger",
	"Entities.gmod_track_switch.Name": "Weichenbox",
	"Entities.gmod_track_powermeter.Name": "Messgeraet",
	"Entities.gmod_track_controller.Name": "Gleis Kontroller",
	"Entities.gmod_track_udochka.Name": "Elektrischer Kontakt",
	"Entities.gmod_train_spawner.Name": "Zug Spawner",
	
	"Train.703.VU": "Zug Kontrolle",
	"Train.703.Breakers1" : "Batterien",
	"Train.703.Breakers2" : "Relays",
	"Train.703.RCARS" : "RC-ARS",
	"Train.703.Left" : "Hilfsanzeige",
	"Train.703.Parking" : "UAVA und Parkbremse",
	"Train.703.ASNP" : "ASNP",
	"Train.703.IGLA" : "IGLA",
	"Train.717.Breakers1": "Mittlere Relay",
	"Train.717.VB1": "Anzeige mit RC",
	"Train.717.Breakers2": "Rechte Relays",
	"Train.717.VB2": "Untere Anzeige mit RC",
	"Train.717.UAVA": "UAVA",
	"Train.717.Pneumo": "Luftdruck Ventil",
	"Train.717.Helpers": "Hilfsanzeige",
	"Train.717.Block4": "4er Block",
	"Train.717.IGLA": "IGLA",
	"Train.717.ASNP" : "ASNP",
	"Train.720.CameraCond": "Klimaanzeige",
	"Train.720.CameraPPZ": "Zugsicherungsanzeige",
	"Train.720.CameraPV": "Hilfsschalter",
	"Train.720.CameraASNP": "ASNP",
	"Train.720.CameraVityaz": "SAU Vityaz",
	"Train.720.CameraKRMH": "KRMSH Ventil",
	"Train.720.CameraPVZ": "Wagenschutzanzeige",
	"Train.722.Breakers": "Zugsicherungsrelays",
	"Train.722.PU2_1": "Schalterplatte",
	"Train.722.PU2_2": "Deaktivieranzeiger",
	"Train.722.Vityaz": "SAU Vityaz-SP Bildschirm",
	"Train.722.SARMAT": "BM CIK SARMAT Bildschirm",
	"Train.722.CabLights": "Fuehrerstandsbeleuchtung",
	"Train.722.Route": "Setze Zugnummer",
	"Train.722.Disconnects": "Isolierventile",
	"Train.722.KRMH": "Deaktiviere KRMSH & RVTB"
}
]]