--@Translation author: Ron Thunderr
--@Version: 


return[[
{
	"Lang": "de",
	"Name": "Deutsch",

	"Spawner.Title": "Zug spawner",
	"Spawner.Trains1": "Zuege",
	"Spawner.Trains2": "Maximale Anzahl fuer dich",
	"Spawner.WagNum": "Wagen",
	"Spawner.AutoCouple": "Automatisches kuppeln der Wagons",

	"Entities.gmod_subway_81-717_mvm.Spawner.Texture.Name": "Ausfuehrung",
	"Entities.gmod_subway_81-717_mvm.Spawner.PassTexture.Name": "Passagiertextur",
	"Entities.gmod_subway_81-717_mvm.Spawner.CabTexture.Name": "Fuehrerstandstextur",
	"Entities.gmod_subway_81-717_mvm.Spawner.Announcer.Name": "Ansagegeraet",
	"Entities.gmod_subway_81-717_mvm.Spawner.Lighter.Name": "Feuerzeug",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.Name": "ARS Konsolentyp",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.1": "Normal(eckige lampen)",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.2": "Normal(runde lampen)",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.3": "Kiev/St.Petersburg",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.4": "Alte ARS Ausfuehrung",
	"Entities.gmod_subway_81-717_mvm.Spawner.Cran.Name": "Bremshebel",
	"Entities.gmod_subway_81-717_mvm.Spawner.Cran.1": "334",
	"Entities.gmod_subway_81-717_mvm.Spawner.Cran.2": "013",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.Name": "Front",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.1": "2-2",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.2": "2-2-2",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.3": "1-4-1 Stossstange 1",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.4": "1-4-1 Stossstange 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.5": "1-1",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.6": "Retro",
	"Entities.gmod_subway_81-717_mvm.Spawner.LED.Name": "LED",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.Name": "BPSN typ",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.1": "Alter hoher ton",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.2": "Alter mittlerer ton",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.3": "Normal(aus St.Petersburg)",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.4": "Normal(TKL)",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.5": "Normal",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.6": "Kiew",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.7": "Alt",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.8": "Normal 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.9": "Normal 3",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.10": "Kein Ton(BPN-115)",
	"Entities.gmod_subway_81-717_mvm.Spawner.NewKV.Name": "Neues Kontroller Modell",
	"Entities.gmod_subway_81-717_mvm.Spawner.HornType.Name": "St.Petersburg Warnsignal",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.Name": "Pfeifton",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.1": "Alt",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.2": "Normal tiefer ton",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.3": "Normal hoher ton",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.4": "Normal alternierender tiefer ton",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.5": "Normal alternierender hoher ton",
	"Entities.gmod_subway_81-717_mvm.Spawner.NM.Name": "Zug Luftdruck",
	"Entities.gmod_subway_81-717_mvm.Spawner.Battery.Name": "Batterie",
	"Entities.gmod_subway_81-717_mvm.Spawner.Switches.Name": "Relays eingeschaltet",
	"Entities.gmod_subway_81-717_mvm.Spawner.SwitchesR.Name": "Zufaellige Relays einschalten",
	"Entities.gmod_subway_81-717_mvm.Spawner.DoorsL.Name": "Oeffne Tueren links",
	"Entities.gmod_subway_81-717_mvm.Spawner.DoorsR.Name": "Oeffne Tueren rechts",
	"Entities.gmod_subway_81-717_mvm.Spawner.GV.Name": "Hochspannungs Schalter",
	"Entities.gmod_subway_81-717_mvm.Spawner.PB.Name": "Parkbremse",
	"Entities.gmod_subway_81-717_mvm.Spawner.BortLampType.Name": "Tuersignal lampen",
	"Entities.gmod_subway_81-717_mvm.Spawner.BortLampType.1": "Horizontal",
	"Entities.gmod_subway_81-717_mvm.Spawner.BortLampType.2": "Vertikal",
	"Entities.gmod_subway_81-717_mvm.Spawner.MVM.Name": "MVM Schild",
	"Entities.gmod_subway_81-717_mvm.Spawner.HandRail.Name": "Haltestangen style",
	"Entities.gmod_subway_81-717_mvm.Spawner.HandRail.1": "Alt",
	"Entities.gmod_subway_81-717_mvm.Spawner.HandRail.2": "Neu",
	"Entities.gmod_subway_81-717_mvm.Spawner.SeatType.Name": "Sitz style",
	"Entities.gmod_subway_81-717_mvm.Spawner.SeatType.1": "Alt",
	"Entities.gmod_subway_81-717_mvm.Spawner.SeatType.2": "Neu",
	"Entities.gmod_subway_81-717_mvm.Spawner.LampType.Name": "Lampen style",
	"Entities.gmod_subway_81-717_mvm.Spawner.LampType.1": "Typ 1",
	"Entities.gmod_subway_81-717_mvm.Spawner.LampType.2": "Typ 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.LampType.3": "Typ 3",
	"Entities.gmod_subway_81-717_mvm.Spawner.Breakers.Name": "Relays Rechts",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.Name": "Werbung",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.1": "Werbung 1",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.2": "Werbung 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.3": "Werbung 3",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.4": "Keine Werbung",

	"Entities.gmod_subway_81-720.Spawner.Texture.Name": "Ausfuehrung",
	"Entities.gmod_subway_81-720.Spawner.PassTexture.Name": "Passagiertextur",
	"Entities.gmod_subway_81-720.Spawner.CabTexture.Name": "Fuehrerstandstextur",
	"Entities.gmod_subway_81-720.Spawner.Announcer.Name": "Ansagegeraet",
	"Entities.gmod_subway_81-720.Spawner.Scheme.Name": "Linien schema",
	"Entities.gmod_subway_81-720.Spawner.PassSchemesInvert.Name": "Tausche schema",
	"Entities.gmod_subway_81-720.Spawner.NM.Name": "Zug Luftdruck",
	"Entities.gmod_subway_81-720.Spawner.Battery.Name": "Batterie",
	"Entities.gmod_subway_81-720.Spawner.BRU.Name": "Hochspannungschalter",
	"Entities.gmod_subway_81-720.Spawner.PVZR.Name": "Schalte zufaellige Zugsicherungrelays ein",
	"Entities.gmod_subway_81-720.Spawner.PPZ.Name": "Schalte alle Zugsicherungrelays ein",
	"Entities.gmod_subway_81-720.Spawner.PPZDepot.Name": "Schalte alle Zugsicherungs Relays aus",
	"Entities.gmod_subway_81-720.Spawner.PPZR.Name": "Zufaellige Relays in Mittelwagen",
	"Entities.gmod_subway_81-720.Spawner.DoorsL.Name": "Oeffne Tueren links",
	"Entities.gmod_subway_81-720.Spawner.DoorsR.Name": "Oeffne Tueren rechts",

	"Entities.gmod_subway_81-722.Spawner.Texture.Name": "Ausfuehrung",
	"Entities.gmod_subway_81-722.Spawner.PassTexture.Name": "Passagiertextur",
	"Entities.gmod_subway_81-722.Spawner.CabTexture.Name": "Fuehrerstandstextur",
	"Entities.gmod_subway_81-722.Spawner.Announcer.Name": "Ansagegeraet",
	"Entities.gmod_subway_81-722.Spawner.Scheme.Name": "Linien schema",
	"Entities.gmod_subway_81-722.Spawner.SarmatInvert.Name": "Tausche schema",
	"Entities.gmod_subway_81-722.Spawner.NM.Name": "Zug Luftdruck",
	"Entities.gmod_subway_81-722.Spawner.Battery.Name": "Batterie",
	"Entities.gmod_subway_81-722.Spawner.Switches.Name": "Schalte zufaellige Zugsrelays ein",
	"Entities.gmod_subway_81-722.Spawner.SwitchesR.Name": "Schalte zufaellige Relays ein",
	"Entities.gmod_subway_81-722.Spawner.DoorsL.Name": "Oeffne Tueren links",
	"Entities.gmod_subway_81-722.Spawner.DoorsR.Name": "Oeffne Tueren rechts",

	"Entities.gmod_subway_ezh.Spawner.Texture.Name": "Ausfuehrung",
	"Entities.gmod_subway_ezh.Spawner.PassTexture.Name": "Passagiertextur",
	"Entities.gmod_subway_ezh.Spawner.CabTexture.Name": "Fuehrerstandstextur",
	"Entities.gmod_subway_ezh.Spawner.Announcer.Name": "Ansagegeraet",
	"Entities.gmod_subway_ezh.Spawner.HornType.Name": "St. Petersburg Signalhorn",
	"Entities.gmod_subway_ezh.Spawner.NM.Name": "Zug Luftdruck",
	"Entities.gmod_subway_ezh.Spawner.Battery.Name": "Batterie",
	"Entities.gmod_subway_ezh.Spawner.AV8B.Name": "Aktiviere AV8B",
	"Entities.gmod_subway_ezh.Spawner.DoorsL.Name": "Oeffne Tueren links",
	"Entities.gmod_subway_ezh.Spawner.DoorsR.Name": "Oeffne Tueren rechts",
	"Entities.gmod_subway_ezh.Spawner.GV.Name": "Hochspannungschalter",

	"Entities.gmod_subway_em508.Spawner.Texture.Name": "Ausfuehrung",
	"Entities.gmod_subway_em508.Spawner.PassTexture.Name": "Passagiertextur",
	"Entities.gmod_subway_em508.Spawner.CabTexture.Name": "Fuehrerstandstextur",
	"Entities.gmod_subway_em508.Spawner.Announcer.Name": "Ansagegeraet",
	"Entities.gmod_subway_em508.Spawner.HornType.Name": "St. Petersburg Signalhorn",
	"Entities.gmod_subway_em508.Spawner.NM.Name": "Zug Luftdruck",
	"Entities.gmod_subway_em508.Spawner.Battery.Name": "Batterie",
	"Entities.gmod_subway_em508.Spawner.AV8B.Name": "Aktiviere AV8B",
	"Entities.gmod_subway_em508.Spawner.DoorsL.Name": "Oeffne Tueren links",
	"Entities.gmod_subway_em508.Spawner.DoorsR.Name": "Oeffne Tueren rechts",
	"Entities.gmod_subway_em508.Spawner.GV.Name": "Hochspannungschalter",

	"Entities.gmod_subway_ezh3.Spawner.Texture.Name": "Ausfuehrung",
	"Entities.gmod_subway_ezh3.Spawner.PassTexture.Name": "Passagiertextur",
	"Entities.gmod_subway_ezh3.Spawner.CabTexture.Name": "Fuehrerstandstextur",
	"Entities.gmod_subway_ezh3.Spawner.Announcer.Name": "Ansagegeraet",
	"Entities.gmod_subway_ezh3.Spawner.HornType.Name": "St. Petersburg Signalhorn",
	"Entities.gmod_subway_ezh3.Spawner.NM.Name": "Zug Luftdruck",
	"Entities.gmod_subway_ezh3.Spawner.Battery.Name": "Batterie",
	"Entities.gmod_subway_ezh3.Spawner.AV8B.Name": "Aktiviere AV8B",
	"Entities.gmod_subway_ezh3.Spawner.DoorsL.Name": "Oeffne Tueren links",
	"Entities.gmod_subway_ezh3.Spawner.DoorsR.Name": "Oeffne Tueren rechts",
	"Entities.gmod_subway_ezh3.Spawner.GV.Name": "Hochspannungschalter",

	"Entities.gmod_subway_81-717_lvz.Spawner.Texture.Name": "Ausfuehrung",
	"Entities.gmod_subway_81-717_lvz.Spawner.PassTexture.Name": "Passagiertextur",
	"Entities.gmod_subway_81-717_lvz.Spawner.CabTexture.Name": "Fuehrerstandstextur",
	"Entities.gmod_subway_81-717_lvz.Spawner.Announcer.Name": "Ansagegeraet",
	"Entities.gmod_subway_81-717_lvz.Spawner.Lighter.Name": "Feuerzeug",
	"Entities.gmod_subway_81-717_lvz.Spawner.Cran.Name": "Bremshebel",
	"Entities.gmod_subway_81-717_lvz.Spawner.Cran.1": "334",
	"Entities.gmod_subway_81-717_lvz.Spawner.Cran.2": "013",
	"Entities.gmod_subway_81-717_lvz.Spawner.MaskType.Name": "Front",
	"Entities.gmod_subway_81-717_lvz.Spawner.MaskType.1": "1-4-1",
	"Entities.gmod_subway_81-717_lvz.Spawner.MaskType.2": "2-2(tiefe)-2",
	"Entities.gmod_subway_81-717_lvz.Spawner.MaskType.3": "2-2",
	"Entities.gmod_subway_81-717_lvz.Spawner.MaskType.4": "2-2-2",
	"Entities.gmod_subway_81-717_lvz.Spawner.MaskType.5": "1-3-1",
	"Entities.gmod_subway_81-717_lvz.Spawner.LED.Name": "LED",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.Name": "BPSN Typ",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.1": "Alter hoher ton",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.2": "Alter mittlerer ton",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.3": "Normal(aus St.Petersburg)",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.4": "Normal(TKL)",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.5": "Normal",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.6": "Kiew",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.7": "Alt",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.8": "Normal 2",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.9": "Normal 3",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.10": "Kein Ton(BPN-115)",
    "Entities.gmod_subway_81-717_lvz.Spawner.NewKV.Name": "Neues Kontroller Modell",
    "Entities.gmod_subway_81-717_lvz.Spawner.HornType.Name": "St. Petersburg Signalhorn",
    "Entities.gmod_subway_81-717_lvz.Spawner.RingType.Name": "Pfeifton",
	"Entities.gmod_subway_81-717_lvz.Spawner.RingType.1": "Alt",
	"Entities.gmod_subway_81-717_lvz.Spawner.RingType.2": "Normal tiefer ton",
	"Entities.gmod_subway_81-717_lvz.Spawner.RingType.3": "Normal hoher ton",
	"Entities.gmod_subway_81-717_lvz.Spawner.RingType.4": "Normal alternierender tiefer ton",
	"Entities.gmod_subway_81-717_lvz.Spawner.RingType.5": "Normal alternierender hoher ton",
	"Entities.gmod_subway_81-717_lvz.Spawner.NM.Name": "Zug Luftdruck",
	"Entities.gmod_subway_81-717_lvz.Spawner.Battery.Name": "Batterie",
	"Entities.gmod_subway_81-717_lvz.Spawner.Switches.Name": "Relays eingeschaltet",
	"Entities.gmod_subway_81-717_lvz.Spawner.SwitchesR.Name": "Zufaellige Relays einschalten",
	"Entities.gmod_subway_81-717_lvz.Spawner.DoorsL.Name": "Oeffne Tueren links",
	"Entities.gmod_subway_81-717_lvz.Spawner.DoorsR.Name": "Oeffne Tueren rechts",
	"Entities.gmod_subway_81-717_lvz.Spawner.GV.Name": "Hochspannungs Schalter",
	"Entities.gmod_subway_81-717_lvz.Spawner.PB.Name": "Parkbremse",
	"Entities.gmod_subway_81-717_lvz.Spawner.BortLampType.Name": "Tuersignal lampen",	
    "Entities.gmod_subway_81-717_lvz.Spawner.BortLampType.1": "Horizontal",
	"Entities.gmod_subway_81-717_lvz.Spawner.BortLampType.2": "Vertikal",
	"Entities.gmod_subway_81-717_lvz.Spawner.HandRail.Name": "Haltestangen style",
	"Entities.gmod_subway_81-717_lvz.Spawner.HandRail.1": "Alt",
	"Entities.gmod_subway_81-717_lvz.Spawner.HandRail.2": "Neu",
	"Entities.gmod_subway_81-717_lvz.Spawner.SeatType.Name": "Sitz style",
	"Entities.gmod_subway_81-717_lvz.Spawner.SeatType.1": "Alt",
	"Entities.gmod_subway_81-717_lvz.Spawner.SeatType.2": "Neu",
	"Entities.gmod_subway_81-717_lvz.Spawner.LampType.Name": "Lampen style",
	"Entities.gmod_subway_81-717_lvz.Spawner.LampType.1": "Typ 1",
	"Entities.gmod_subway_81-717_lvz.Spawner.LampType.2": "Typ 2",
	"Entities.gmod_subway_81-717_lvz.Spawner.LampType.3": "Typ 3",
	"Entities.gmod_subway_81-717_lvz.Spawner.Breakers.Name": "Relays Rechts",
	"Entities.gmod_subway_81-717_lvz.Spawner.Adverts.Name": "Werbung",
	"Entities.gmod_subway_81-717_lvz.Spawner.Adverts.1": "Werbung 1",
	"Entities.gmod_subway_81-717_lvz.Spawner.Adverts.2": "Werbung 2",
	"Entities.gmod_subway_81-717_lvz.Spawner.Adverts.3": "Werbung 3",
	"Entities.gmod_subway_81-717_lvz.Spawner.Adverts.4": "Keine Werbung",	

	"Entities.gmod_subway_81-703.Spawner.Texture.Name": "Ausfuehrung",
	"Entities.gmod_subway_81-703.Spawner.PassTexture.Name": "Passagiertextur",
	"Entities.gmod_subway_81-703.Spawner.CabTexture.Name": "Fuehrerstandstextur",
	"Entities.gmod_subway_81-703.Spawner.Announcer.Name": "Ansagegeraet",
	"Entities.gmod_subway_81-703.Spawner.HornType.Name": "St. Petersburg Signalhorn",
	"Entities.gmod_subway_81-703.Spawner.NM.Name": "Zug Luftdruck",
	"Entities.gmod_subway_81-703.Spawner.Battery.Name": "Batterie",
	"Entities.gmod_subway_81-703.Spawner.AV8B.Name": "Aktiviere AV8B",
	"Entities.gmod_subway_81-703.Spawner.DoorsL.Name": "Oeffne Tueren links",
	"Entities.gmod_subway_81-703.Spawner.DoorsR.Name": "Oeffne Tueren rechts",
	"Entities.gmod_subway_81-703.Spawner.GV.Name": "Hochspannungschalter",

	"Spawner.Close": "Schliessen",
	"Spawner.Spawn": "Fertig"
}
]]