return [[
{
  "Lang": "geo",
  "Name": "Georgian",

  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF1Set": "Витязь: F1",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF2Set": "Витязь: შემდეგი გვერდი",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF3Set": "Витязь: წინა გვერდი",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF4Set": "Витязь: ჩვეულებრივი რეჟიმი",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz1Set": "Витязь: 1",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz4Set": "Витязь: 4",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz7Set": "Витязь: 7",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz2Set": "Витязь: 2",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz5Set": "Витязь: 5",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz8Set": "Витязь: 8",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz0Set": "Витязь: 0",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz3Set": "Витязь: 3",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz6Set": "Витязь: 6",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.Vityaz9Set": "Витязь: 9",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF5Set": "Витязь: ЗВ",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF6Set": "Витязь: ზემოთ\\სიჩქარე",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF7Set": "Витязь: ქვემოთ\\ძაბვა",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF8Set": "Витязь: შესვლა\\ვაგონის აღჭურვილობა",
  "Entities.gmod_subway_81-720.Buttons.VityazButtons.VityazF9Set": "Витязь: არჩევა\\ვაგონის აღჭურვილობის მართვა",
  "Entities.gmod_subway_81-720.Buttons.RV.EmerX1Set": "სვლა 1 საავარიო",
  "Entities.gmod_subway_81-720.Buttons.RV.EmerX2Set": "სვლა 2 საავარიო",
  "Entities.gmod_subway_81-720.Buttons.RV.EmerCloseDoorsSet": "ავარიული კარების დაკეტვა",
  "Entities.gmod_subway_81-720.Buttons.RV.EmergencyDoorsToggle": "კარები ავარიული",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentCondMode-": "ვენტილიატორის მუშამობის რეჟიმი: +",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentCondMode+": "ვენტილიატორის მუშამობის რეჟიმი: -",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentHeatMode+": "+",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentHeatMode-": "-",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentStrengthMode-": "ვენტილიატორის ძალა: +",
  "Entities.gmod_subway_81-720.Buttons.BackVent.VentStrengthMode+": "Сვენტილიატორის ძალა: -",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV1Toggle": "SF1: ელექტრომომარაგება ვაგონების კონტროლის სქემებისთვის",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV2Toggle": "SF2: კვება БУВ",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV3Toggle": "SF3: კვება БУТП",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV4Toggle": "SF4: БУТП მართვა",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV5Toggle": "SF5: БУТП ავარიული მართვა",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV6Toggle": "SF6: БУТП კვება",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV7Toggle": "SF7: ББЭ",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV8Toggle": "SF8: БВ მართვა",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV9Toggle": "SF9: БВ კვება",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV10Toggle": "SF10: ППО",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV11Toggle": "SF11: მოტორ–კოპრესორი",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV12Toggle": "SF12: კარების დაკეტვა",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV13Toggle": "SF13: მარცხენა კარები გაღება",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV14Toggle": "SF14: მარჯვენა კარების გაღება",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV15Toggle": "SF15: კიდური კარები",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV16Toggle": "SF16: შეტყობინება",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV17Toggle": "SF17: გადაუდებელი კავშირი",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV18Toggle": "SF18: საავარიო",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV19Toggle": "SF19: სალონის განათების კვება",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV20Toggle": "SF20: სალონის ავარიული განათება",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV21Toggle": "SF21: სენსორის სიჩქარე",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV22Toggle": "SF22: დგომის მუხრუჭი",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV23Toggle": "SF23: ვენტილაციის მართვა 1-ლი ჯგუფი",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV24Toggle": "SF24: ვენტილაციის მართვა მე–2 ჯგუფი",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV25Toggle": "SF25: ვენტილაციის კვება 1-ლი ჯგუფი",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV26Toggle": "SF26: ვენტილაციის კვება მე–2 ჯგუფი",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV27Toggle": "SF27: გამაღვიძებელის კვება FIXME",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV28Toggle": "SF28: კვება ЗКК FIXME",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV29Toggle": "SF29: ელექტრომიმღები",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV30Toggle": "SF30: ტაბლო",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV31Toggle": "SF31: საავარიო",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV32Toggle": "SF32: საავარიო",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV33Toggle": "SF33: საავარიო",
  "Entities.gmod_subway_81-720.Buttons.ASNP.R_ASNPMenuSet": "АСНП: მენიუ",
  "Entities.gmod_subway_81-720.Buttons.ASNP.R_ASNPUpSet": "АСНП: ზემოთ",
  "Entities.gmod_subway_81-720.Buttons.ASNP.R_ASNPDownSet": "АСНП: ქვემოთ",
  "Entities.gmod_subway_81-720.Buttons.ASNP.R_ASNPOnToggle": "АСНП: ჩართვა",
  "Entities.gmod_subway_81-720.Buttons.PneumoHelper1.!BrakeCylinder": "სამუხრუჭე ცილინდრი",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF1Toggle": "SF1: საერთო კვება",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF2Toggle": "SF2: მთავარი მართვა",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF3Toggle": "SF3: ავარიული მართვა",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF4Toggle": "SF4: БАРС",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF5Toggle": "SF5: БУП",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF6Toggle": "SF6: БКЦУ",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF7Toggle": "SF7: ППО",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF8Toggle": "SF8: შეტყობინება",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF9Toggle": "SF9: რადიოკავშირი",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF10Toggle": "SF10: ვაგონის ორეინტაცია",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF11Toggle": "SF11: გადაადგილების მიმართულება",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF12Toggle": "SF12: ფარები 1-ლი ჯგუფი",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF13Toggle": "SF13: ფარები მე–2 ჯგუფი",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF14Toggle": "SF14: საგაბარატო განათება",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF15Toggle": "SF15: კაბინის განათება",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF16Toggle": "SF16: გათბობა",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF17Toggle": "SF17: კაბინის განათება",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF18Toggle": "SF18: Гребнесмазыватель",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF19Toggle": "SF19: კვება КРМ მთავარი",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF20Toggle": "SF20: კვება КРМ საავარიო",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF21Toggle": "SF21: კარები გაღებულო",
  "Entities.gmod_subway_81-720.Buttons.BackPPZ.SF22Toggle": "SF22: კარები დაკეტილი",
  "Entities.gmod_subway_81-720.Buttons.BTO.K29Toggle": "КРМШ",
  "Entities.gmod_subway_81-720.Buttons.PassengerDoor2.PassengerDoor": "კარები მემანქანის კაბინაში სალონიდან\nPass door",
  "Entities.gmod_subway_81-720.Buttons.VoltHelper2.!HV": "მაღალი ძაბვის კილოვოლტმეტრი(კონტაქტური რელსი)",
  "Entities.gmod_subway_81-720.Buttons.VoltHelper2.!I1_3": "ძაბვა 1–ლი ჯგუფები წევის ძრავები",
  "Entities.gmod_subway_81-720.Buttons.VoltHelper2.!I2_4": "ძაბვა მე–2 ჯგუფები წევის ძრავები",
  "Entities.gmod_subway_81-720.Buttons.GV.GVToggle": "Разъединитель БРУ (ГВ)",
  "Entities.gmod_subway_81-720.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "სამუხრუჭე მაგისრალის კიდური კრანი",
  "Entities.gmod_subway_81-720.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "ზეწოლის მაგისრალის კიდური კრანი",
  "Entities.gmod_subway_81-720.Buttons.RearDoor1.RearDoor": "წინა კარები\nFront door",
  "Entities.gmod_subway_81-720.Buttons.RearDoor.RearDoor": "წინა კარები\nFront door",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Pant1Toggle": "პანტოგრამების დაჭერა 1-ლი ჯგუფები",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Pant2Toggle": "პანტოგრამების დაჭერა მე–2 ჯგუფები",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Vent1Toggle": "ვენტილაცია 1-я ჯგუფი",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Vent2Toggle": "ვენტილაცია მე–2 ჯგუფი",
  "Entities.gmod_subway_81-720.Buttons.BackDown.VentToggle": "",
  "Entities.gmod_subway_81-720.Buttons.BackDown.PassLightToggle": "სალონის განათება",
  "Entities.gmod_subway_81-720.Buttons.BackDown.CabLightToggle": "კაბინის განათება",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Headlights1Toggle": "ფარები 1–ლი ჯგუფი",
  "Entities.gmod_subway_81-720.Buttons.BackDown.Headlights2Toggle": "ფარები მე–2 ჯგუფი",
  "Entities.gmod_subway_81-720.Buttons.BackDown.ParkingBrakeToggle": "ავტოდგომის მუხრუჭი",
  "Entities.gmod_subway_81-720.Buttons.BackDown.TorecDoorsToggle": "კარები торцевые",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BBERToggle": "ББЭ საავარიო ჩართვა",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BBEToggle": "ББЭ",
  "Entities.gmod_subway_81-720.Buttons.BackDown.CompressorToggle": "კომპრესორი",
  "Entities.gmod_subway_81-720.Buttons.BackDown.CabLightStrengthToggle": "სიძლიერე კაბინის განათების",
  "Entities.gmod_subway_81-720.Buttons.BackDown.AppLights1Toggle": "განათების აპარატის განყოფილების",
  "Entities.gmod_subway_81-720.Buttons.BackDown.AppLights2Toggle": "",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BARSBlock-": "დაბლოკვა გაუმართავი БАРС: -",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BARSBlock+": "დაბლოკვა გაუმართავი БАРС: +",
  "Entities.gmod_subway_81-720.Buttons.BackDown.BatteryToggle": "ბატარეის გამომრთველი",
  "Entities.gmod_subway_81-720.Buttons.BackDown.ALSFreqToggle": "დეკოდერი ასს",
  "Entities.gmod_subway_81-720.Buttons.VoltHelper1.!Battery": "საბორტო ქსელის ვოლტმეტრი(მტარეა)",
  "Entities.gmod_subway_81-720.Buttons.PassengerDoor.PassengerDoor": "კარები მემანქანის კაბინაში სალონიდან\nPass\nPass door",
  "Entities.gmod_subway_81-720.Buttons.CabinDoorR.CabinDoorRight": "კარები მემანქანის კაბინაში\nCabin door",
  "Entities.gmod_subway_81-720.Buttons.CabinDoorL.CabinDoorLeft": "კარები მემანქანის კაბინაში\nCabin door",
  "Entities.gmod_subway_81-720.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "სამუხრუჭე მაგისრალის კიდური კრანი",
  "Entities.gmod_subway_81-703.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "ზეწოლის მაგისრალის კიდური კრანი",
  "Entities.gmod_subway_81-720.Buttons.PUL.DoorSelectLToggle": "მარცხენა კარების არჩევა",
  "Entities.gmod_subway_81-720.Buttons.PUL.DoorSelectRToggle": "მარჯვენა კარების არჩევა",
  "Entities.gmod_subway_81-720.Buttons.PUL.DoorBlockToggle": "კარების დაბლოკვა",
  "Entities.gmod_subway_81-720.Buttons.PUL.!DoorLeftLamp": "მარცხენა კარების მუშამობის ღილაკი",
  "Entities.gmod_subway_81-720.Buttons.PUL.DoorLeftSet": "მარცხენა კარები",
  "Entities.gmod_subway_81-720.Buttons.PUU.!DoorsClosed": "დაკეტილი კარები",
  "Entities.gmod_subway_81-720.Buttons.PUU.StandToggle": "გაჩერება",
  "Entities.gmod_subway_81-720.Buttons.PUU.TickerToggle": "მორბენალი ხაზი",
  "Entities.gmod_subway_81-720.Buttons.PUU.KAHToggle": "КАХ",
  "Entities.gmod_subway_81-720.Buttons.PUU.ALSToggle": "ასს",
  "Entities.gmod_subway_81-720.Buttons.PUU.FDepotToggle": "დეპოდან გამოსვლა",
  "Entities.gmod_subway_81-720.Buttons.PUU.!HVoltage": "კონტაქტური ხაზი",
  "Entities.gmod_subway_81-720.Buttons.PUU.PassSchemeToggle": "კარებსზედა ტაბლო",
  "Entities.gmod_subway_81-720.Buttons.PUU.EmergencyCompressorSet": "კომპრესორი საავარიო",
  "Entities.gmod_subway_81-720.Buttons.PUU.EnableBVSet": "დაცვის ჩართვა",
  "Entities.gmod_subway_81-720.Buttons.PUU.DisableBVSet": "გამორთვა БВ",
  "Entities.gmod_subway_81-720.Buttons.PUU.RingSet": "მართვის გადაცემა(ზარი)",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_Program2Set": "პროგრამა 2",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_AnnouncerToggle": "ინფორმატორი",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_LineToggle": "ხაზი",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_EmerSet": "გადაუდებელი ურთიერთობა",
  "Entities.gmod_subway_81-720.Buttons.PUU.R_Program1Set": "ჩაწერის გაშევება",
  "Entities.gmod_subway_81-720.Buttons.PUU.EnableBVEmerSet": "БВ–ს საავარიო დაბრუნება",
  "Entities.gmod_subway_81-720.Buttons.PUU.EmergencyControlsToggle": "საავარიო მართვა",
  "Entities.gmod_subway_81-720.Buttons.PUU.WiperToggle": "მინის საწმენდი",
  "Entities.gmod_subway_81-720.Buttons.PUU.!VDop": "დასაშვები სიჩქარე",
  "Entities.gmod_subway_81-720.Buttons.PUU.!VFact": "ფაქტობრივი სიჩქარე",
  "Entities.gmod_subway_81-720.Buttons.PUU.!VPred": "სიფრთხილის სიჩქარე",
  "Entities.gmod_subway_81-720.Buttons.PUU.!VDop2": "დასაშვები სიჩქარე",
  "Entities.gmod_subway_81-720.Buttons.PUU.!Acc": "აჩქარება",
  "Entities.gmod_subway_81-720.Buttons.PUU.!Forw": "სვლა წინ,
  "Entities.gmod_subway_81-720.Buttons.PUU.!Back": "სვლა უკან",
  "Entities.gmod_subway_81-720.Buttons.PUR.EmerBrakeAddSet": "(ავარიული) მუხრუჭი",
  "Entities.gmod_subway_81-720.Buttons.PUR.EmerBrakeReleaseSet": "(ავარიული) აშვება",
  "Entities.gmod_subway_81-720.Buttons.PUR.EmerBrakeToggle": "საავარიო მუხრუჭი",
  "Entities.gmod_subway_81-720.Buttons.PUR.EmergencyBrakeToggle": "საავარიო მუხრუჭი,
  "Entities.gmod_subway_81-720.Buttons.PUR.DoorCloseToggle": "დაკეტილი კარები",
  "Entities.gmod_subway_81-720.Buttons.PUR.AttentionMessageSet": "მესიჯის გახმოვანება",
  "Entities.gmod_subway_81-720.Buttons.PUR.AttentionSet": "სიფხიზლე",
  "Entities.gmod_subway_81-720.Buttons.PUR.AttentionBrakeSet": "მუხრუჭის მიღება",
  "Entities.gmod_subway_81-720.Buttons.PUR.HornBSet": "სიგნალი",
  "Entities.gmod_subway_81-720.Buttons.PUR.DoorRightSet": "მარჯვენა კარები",
  "Entities.gmod_subway_81-720.Buttons.PUR.!DoorRightLamp": "მარჯვენა კარების მუშამობის ღილაკი",
  "Entities.gmod_subway_81-720.Buttons.PneumoHelper2.!BrakeTrainLine": "წითელი- სამუხრუჭე, შავი - ზეწოლის",

  "Entities.gmod_subway_81-720.Buttons.GV.GVToggle": "განმაშორებელი БРУ (ГВ)",
  "Entities.gmod_subway_81-720.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "სამუხრუჭე მაგისრალის კიდური კრანი",
  "Entities.gmod_subway_81-720.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "ზეწოლის მაგისრალის კიდური კრანი",,
  "Entities.gmod_subway_81-720.Buttons.FrontDoor.FrontDoor": "წინა კარი\nFront door",
  "Entities.gmod_subway_81-720.Buttons.RearDoor.RearDoor": "უკანა კარი\nRear door",
  "Entities.gmod_subway_81-720.Buttons.Battery.BatteryToggle": "ბატარეა",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV1Toggle": "SF1: ელექტრომომარაგება ვაგონების კონტროლის სქემებისთვის",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV2Toggle": "SF2: კვება БУВ",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV3Toggle": "SF3: კვება БУТП",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV4Toggle": "SF4: БУТП მართვა",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV5Toggle": "SF5: БУТП ავარიული მართვა",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV6Toggle": "SF6: БУТП კვება",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV7Toggle": "SF7: ББЭ",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV8Toggle": "SF8: БВ მართვა",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV9Toggle": "SF9: БВ კვება",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV10Toggle": "SF10: ППО",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV11Toggle": "SF11: მოტორ–კოპრესორი",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV12Toggle": "SF12: კარების დაკეტვა",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV13Toggle": "SF13: მარცხენა კარები გაღება",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV14Toggle": "SF14: მარჯვენა კარების გაღება",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV15Toggle": "SF15: კიდური კარები",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV16Toggle": "SF16: შეტყობინება",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV17Toggle": "SF17: გადაუდებელი კავშირი",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV18Toggle": "SF18: საავარიო",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV19Toggle": "SF19: სალონის განათების კვება",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV20Toggle": "SF20: სალონის ავარიული განათება",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV21Toggle": "SF21: სენსორის სიჩქარე",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV22Toggle": "SF22: დგომის მუხრუჭი",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV23Toggle": "SF23: ვენტილაციის მართვა 1-ლი ჯგუფი",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV24Toggle": "SF24: ვენტილაციის მართვა მე–2 ჯგუფი",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV25Toggle": "SF25: ვენტილაციის კვება 1-ლი ჯგუფი",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV26Toggle": "SF26: ვენტილაციის კვება მე–2 ჯგუფი",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV27Toggle": "SF27: გამაღვიძებელის კვება FIXME",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV28Toggle": "SF28: კვება ЗКК FIXME",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV29Toggle": "SF29: ელექტრომიმღები",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV30Toggle": "SF30: ტაბლო",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV31Toggle": "SF31: საავარიო",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV32Toggle": "SF32: საავარიო",
  "Entities.gmod_subway_81-720.Buttons.PVZ.SFV33Toggle": "SF33: საავარიო",
  "Entities.gmod_subway_81-720.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "სამუხრუჭე მაგისრალის კიდური კრანი",
  "Entities.gmod_subway_81-720.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "ზეწოლის მაგისრალის კიდური კრანი",

  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.IGLA1USet": "ИГЛА: პირველი ღილაკი ზევით",
  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.IGLA1Set": "ИГЛА: პირველი ღილაკი",
  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.IGLA1DSet": "ИГЛА: პირველი ღილაკი ქვემოთ",
  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.IGLA2USet": "ИГЛА: მეორე ღილაკი ზევით",
  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.IGLA2Set": "ИГЛА: მეორე ღილაკი",
  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.IGLA2DSet": "ИГЛА: მეორე ღილაკი ქვემოთ",
  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.!IGLASR": "ИГЛА: SR",
  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.!IGLARX": "ИГЛА: RX",
  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.!IGLAErr": "ИГЛА: უარყოფა",
  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.!IGLAOSP": "ИГЛА: ОСП(ცეცხლმაქრის ამოქმედება)",
  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.!IGLAPI": "ИГЛА: ПИ(ხანძარი)",
  "Entities.gmod_subway_81-720.Buttons.IGLAButtons.!IGLAOff": "ИГЛА: გამორთ",
  "Entities.gmod_subway_81-720.Buttons.PUU.KAHkToggle": "КАХ–ი ღილაკის სახურავი",
  "Entities.gmod_subway_81-720.Buttons.PUU.ALSkToggle": "ასს ღილაკის სახურავი",
  "Entities.gmod_subway_81-720.Buttons.PUR.AccelRateSet": "აჩქარების ტემპი(ასვლის რეჟიმი)"
}
]]
