return [[
{
    "Lang": "geo",
    "Name": "Georgian",


    "Entities.gmod_subway_81-717_lvz.Buttons.HelperPanel.VUD2Toggle": "კმგ2: კარების მართვის გამომრთველი",
    "Entities.gmod_subway_81-717_lvz.Buttons.HelperPanel.VDLSet": "მკგ: მარცხენა კარების გამომრთველი",
    "Entities.gmod_subway_81-717_lvz.Buttons.Battery_2.1:RC1Toggle": "РЦ-1: სარ სქემების გამაწინებელი",
    "Entities.gmod_subway_81-717_lvz.Buttons.Battery_2.1:VBToggle": "ბგ: ბატარეის გამომრთველი",
    "Entities.gmod_subway_81-717_lvz.Buttons.Battery_2.1:BPSToggle": "РЦ-БПС: ანტი–დაგორების ბლოკი",
    "Entities.gmod_subway_81-717_lvz.Buttons.Battery_2.1:BUDToggle": "კმბ: კარების მართვის ბლოკი",
    "Entities.gmod_subway_81-717_lvz.Buttons.Battery_2.1:VRDToggle": "მდგ: მოძრაობის დამრთველის გამომრთველი (0–ზე)",
    "Entities.gmod_subway_81-717_lvz.Buttons.VRD1.VRDToggle": "მდგ: მოძრაობის დამრთველის გამომრთველი (0-ზე)",
    "Entities.gmod_subway_81-717_lvz.Buttons.Wiper.WiperToggle": "შუშისზმენდავი",
    "Entities.gmod_subway_81-717_lvz.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "სამუხრუჭე მაგისრალის კიდური კრანი",
    "Entities.gmod_subway_81-717_lvz.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "ზეწოლის მაგისრალის კიდური კრანი",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.R_UNchToggle": "დსგ: დაბალი სიხშირის გამაძლიერებელი",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.R_ZSToggle": "სხ: საავარიო ხაზის კონტროლი",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.R_GToggle": "ხმამაღლამოლაპარაკე",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.R_UPOToggle": "УПО: ინფორმატორი",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.2:KVTSet": "სღ: სიფხიზლის ღილაკი",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.VZ1Set": "ჩქ311: ჩანაცვლების სარქველი №1",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.VUD1Toggle": "კმგ: კარების მართვის გამომრთველი",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.KDLSet": "მკღ: მარცხენა კარების ღილაკი",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.KDLKToggle": "სახურავი მკღ ღილაკის",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.KDLRSet": "მკგ: მარცხენა კარების გამომრთველი",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.KDLRKToggle": "სახურავი მკგ ღილაკის",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.DoorSelectToggle": "კარების გაღების მხარის არჩევა",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.KRZDSet": "სკდღ: საავარიო კარების დაკეტვის ღილაკი",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.VozvratRPSet": "გადატვითვის დაბრუნება",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.GreenRPLight": "მნგდ: მწვანე ნათურა გადატვითვის დაბრუნების",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.AVULight": "მაგ: მართვის ავტომატური გამორთვა",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.LKVPLight": "მძკკ: მაღალი ძაბვის კონვენტორის კონტროლი",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.SPLight": "ცსნ: ცეცხლის სიგნალიზაციის ნათურა",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.ConverterProtectionSet": "კონვენტორის დაცვა",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.KSNSet": "გღ: გამართავობის ღილაკი",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.DIPoffSet": "სიგნალი",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.ARSToggle": "სარ: სიჩქარის ავტომატური რეგულაცია",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.ALSToggle": "ალს: ავტომატური ლოკომოტივის სიჩქარე",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.TormATToggle": "(placeholder)",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.OtklAVUToggle": "გამორთ.გამ: გამორთვა ავტომატური მართვის (გაუმართავობა გამ)",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.L_1Toggle": "სალონის განათება",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.L_2Toggle": "კაბინის განათება",
    "Entities.gmod_subway_81-717_lvz.Buttons.Main.L_3Toggle": "პულტის განათება",
    "Entities.gmod_subway_81-717_lvz.Buttons.PassengerDoor.PassengerDoor": "კარები მემანქანის კაბინაში სალონიდან",
    "Entities.gmod_subway_81-717_lvz.Buttons.IGLAButtons.IGLA1Set": "ИГЛА: პირველი ღილაკი",
    "Entities.gmod_subway_81-717_lvz.Buttons.IGLAButtons.IGLA2Set": "ИГЛА: მეორე ღილაკი",
    "Entities.gmod_subway_81-717_lvz.Buttons.IGLAButtons.IGLA23": "ИГЛА: მეორე და მესამე ღილაკი",
    "Entities.gmod_subway_81-717_lvz.Buttons.IGLAButtons.IGLA3Set": "ИГЛА: მესამე ღილაკი",
    "Entities.gmod_subway_81-717_lvz.Buttons.IGLAButtons.IGLA4Set": "ИГЛА: მეოთხე ღილაკი",
    "Entities.gmod_subway_81-717_lvz.Buttons.IGLAButtons.!IGLAFire": "ИГЛА: ცეცხლი",
    "Entities.gmod_subway_81-717_lvz.Buttons.IGLAButtons.!IGLAErr": "ИГЛА: გაუმართავობა",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A61Toggle": "A61 6–ე სამატარებლო მავთულის მართვა",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A55Toggle": "A55 10АС მავთულის მართვა",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A54Toggle": "A54 10АК მავთულის მართვა",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A56Toggle": "A56 ბატარეის ჩართვა",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A27Toggle": "A27 ჩართვა კდწ და განათება",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A21Toggle": "A21 კარებების მართვა",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A10Toggle": "A10 მოტორ–კომპრესორის მართვა",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A53Toggle": "A53 კვება КВЦ",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A43Toggle": "A43 სარ 12ვ კვება",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A45Toggle": "A45 სარ მავთული 10АУ",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A42Toggle": "A42 სარ 75ვ კვება",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A41Toggle": "A41 სარ მუხრუჭი",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:VUToggle": "მმ  მატარებლის მართვა",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A64Toggle": "A64 კაბინის განთების ჩართვა",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A63Toggle": "A63 ИГЛА/БИС",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A50Toggle": "A50 კდწ და განათების ჩართვა",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A51Toggle": "A51 კდწ და განათების გამორთვა",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A23Toggle": "A23 ავარიული მოტორ–კომპრესორის ჩართვა",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A14Toggle": "A14 18 მავთული",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A75Toggle": "A75 კაბინის გათბობა",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A1Toggle": "A1  სვლა 1",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A2Toggle": "A2  სვლა 2",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A3Toggle": "A3  სვლა 3",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A17Toggle": "A17 დაბრუნება გდ",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A62Toggle": "A62 რადიოკავშირი",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A29Toggle": "A29 რადიო ხმოვანება",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A5Toggle": "A5 ",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A6Toggle": "A6  მუხრუჭი 1",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A8Toggle": "A8  სარქველი #1, #2",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A20Toggle": "A20 სვლა 1, 20 მავთული",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A25Toggle": "A25 ხელის მუხრუჭი",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A22Toggle": "A22 ჩართვა КК",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A30Toggle": "A30 საერო ძრავის რიტორიტის კონტროლერი",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A39Toggle": "A39 ავარიული მართვა",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A44Toggle": "A44 მატარებლის ავარიული მართვა",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A80Toggle": "A80 საერო ძრავის გადამრთველის მდგომარეობები",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A65Toggle": "A65 სალონის განათება",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:L_5Toggle": "А49 ავარიული განათება",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A24Toggle": "A24 ბატარეის მუხტი",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A32Toggle": ""A13 კარებების სიგნალიზაცია",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A31Toggle": "A31 მარცხენა კარების გაღება",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A16Toggle": "A16 კაბინის დაკეტვა",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A13Toggle": "A13 კარებების სიგნალიზაცია",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A12Toggle": "A12 ავარიული კარების დაკეტვა",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A7Toggle": "A7  წითელი ფანარი",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A9Toggle": "A9  წითელი ფანარი",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A46Toggle": "A46 თეთრი ფარები",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A47Toggle": "A47 თეთრი ფარები",
    "Entities.gmod_subway_81-717_lvz.Buttons.Schedule.!RouteNum": "М №\nRoute number",
    "Entities.gmod_subway_81-717_lvz.Buttons.Schedule.!PathNum": "П №\nPath number",
    "Entities.gmod_subway_81-717_lvz.Buttons.Schedule.!SchTime": "ВРЕМЯ ХОДА\nTotal schedule time",
    "Entities.gmod_subway_81-717_lvz.Buttons.Schedule.!SchInterval": "ИНТ\nTrain interval",
    "Entities.gmod_subway_81-717_lvz.Buttons.Schedule.!SchHour": "ЧАС\nHour",
    "Entities.gmod_subway_81-717_lvz.Buttons.Schedule.!SchMin": "МИН\nMinute",
    "Entities.gmod_subway_81-717_lvz.Buttons.Schedule.!SchSec": "СЕК\nSecond",
    "Entities.gmod_subway_81-717_lvz.Buttons.Schedule.!SchArrival": "Arrival times",
    "Entities.gmod_subway_81-717_lvz.Buttons.Schedule.!SchStations": "Station name",
    "Entities.gmod_subway_81-717_lvz.Buttons.Stopkran.EmergencyBrakeValveToggle": "ვარიული გაჩერება",
    "Entities.gmod_subway_81-717_lvz.Buttons.PneumaticPanels.!CylinderPressure": "წნევა სამუხრუჭე მაგისტრალში (ТЦ)",
    "Entities.gmod_subway_81-717_lvz.Buttons.PneumaticPanels.!LinePressure": "წნევა მაგისტრალში (წითელი: სამუხრუჭე, შავი: ზეწოლის)",
    "Entities.gmod_subway_81-717_lvz.Buttons.Battery.RC1Toggle": "РЦ-1: სარ ქსელის გამომრთველი",
    "Entities.gmod_subway_81-717_lvz.Buttons.Battery.UOSToggle": "РЦ-УОС: სიჩქრის შემზღვედელი მოწყობილობა",
    "Entities.gmod_subway_81-717_lvz.Buttons.Battery.BUDToggle": "კმბ: კარების მართვის ბლოკი",
    "Entities.gmod_subway_81-717_lvz.Buttons.Battery.VBToggle": "ბგ: ბატარეის გამომრთველი",
    "Entities.gmod_subway_81-717_lvz.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "სამუხრუჭე მაგისრალის კიდური კრანი",
    "Entities.gmod_subway_81-717_lvz.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "ზეწოლის მაგისრალის კიდური კრანი",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!Speedometer1": "სიჩქარის ინდიკატორი",
    "Entities.gmod_subway_81-717_lvz.Buttons.KiyvARS.!Speedometer2": "სიჩქარის ინდიკატორი",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!ARSOch": "НЧ: სარ სიხშირის არ არსებობა",
    "Entities.gmod_subway_81-717_lvz.Buttons.RoundARS.!ARS0": "0: სარ სიგნალი გაჩერება",
    "Entities.gmod_subway_81-717_lvz.Buttons.RoundARS.!ARS40": "40: სიჩქარის შეზღუდვა 40კმ/ჩ",
    "Entities.gmod_subway_81-717_lvz.Buttons.RoundARS.!ARS60": "60: სიჩქარის შეზღუდვა 60 კმ/ჩ",
    "Entities.gmod_subway_81-717_lvz.Buttons.RoundARS.!ARS70": "70: სიჩქარის შეზღუდვა 70 კმ/ჩ",
    "Entities.gmod_subway_81-717_lvz.Buttons.RoundARS.!ARS80": "80: სიჩქარის შეზღუდვა 80 კმ/ჩ",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!LampLSD1": "კს: კარებების სიგნალიზაცია",
    "Entities.gmod_subway_81-717_lvz.Buttons.KiyvARS.!LampLSD2": "კს: კარების სიგნალიზაცია",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!LampLVD": "1: ძრავის ჩართვის ნათურა",
    "Entities.gmod_subway_81-717_lvz.Buttons.KiyvARS.!LampLHRK": "2: რეოსტატურო კონტროლის სვლის ნათურა",
    "Entities.gmod_subway_81-717_lvz.Buttons.KiyvARS.!LampLST": "6: მუხრუჭის სიგნალიზაციის ნათურა",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!LampLRD": "ЛРД",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!LampRP": "გდ: წითელი ნათურა გადატვითვის დაბრუნება",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!LampLSN": "გსნ: გაუმართავობის სიგნალიზაციის ნათურა",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!LampLKVD": "ზგკ: ძრავის გამომრთვის კონტროლი",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!LampLKT": "მკ: მუხრუჭის კონტროლი",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!LampDV": "ბს: ბრუნვის სენსორი",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!SpeedFact1": "სიჩქარე",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!SpeedFact2": "სიჩქარე",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!ARSL20": "НЧ: სარ სიხშირის არ არსებობა",
    "Entities.gmod_subway_81-717_lvz.Buttons.SPBARS.!ARSL40": "40: სიჩქარის შეზღუდვა 40კმ/ჩ",
    "Entities.gmod_subway_81-717_lvz.Buttons.RoundARS.!ARS60": "60: სიჩქარის შეზღუდვა 60 კმ/ჩ",
    "Entities.gmod_subway_81-717_lvz.Buttons.RoundARS.!ARS70": "70: სიჩქარის შეზღუდვა 70 კმ/ჩ",
    "Entities.gmod_subway_81-717_lvz.Buttons.RoundARS.!ARS80": "80: სიჩქარის შეზღუდვა 80 კმ/ჩ",
    "Entities.gmod_subway_81-717_lvz.Buttons.ParkingBrake2.1:ParkingBrakeToggle": "პარკინგის მუხრუჭი",
    "Entities.gmod_subway_81-717_lvz.Buttons.RearDoor.RearDoor": "წინა კარი",
    "Entities.gmod_subway_81-717_lvz.Buttons.GV.GVToggle": "მთავარი გამომრთველი",
    "Entities.gmod_subway_81-717_lvz.Buttons.Meters.!TotalVoltmeter": "ვოლტმეტრი მაღალი ძაბვის (кВ)",
    "Entities.gmod_subway_81-717_lvz.Buttons.Meters.!TotalAmpermeter": "ამპერმეტრი (А)",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A61Toggle": "A61 6–ე სამატარებლო მავთულის მართვა",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A55Toggle": "A55 10АС მავთულის მართვა",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A54Toggle": "A54 10АК მავთულის მართვა",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A56Toggle": "A56 ბატარეის ჩართვა",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A27Toggle": "A27 ჩართვა კდწ და განათება",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A21Toggle": "A21 კარების მართვა",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A10Toggle": "A10 მოტორ–კომპრესორის მართვა",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A53Toggle": "A53 КВЦ კვება",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A43Toggle": "A43 სარ 12ვ კვება",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A45Toggle": "A45 სარ მავთული 10АU",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A42Toggle": "A42 სარ კვება 75ვ",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A41Toggle": "A41 სარ მუხრუჭი",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.VUToggle": "მმ  მატარებლის მართვა",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A64Toggle": "A64 კაბინის განთების ჩართვა",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A63Toggle": "A63 ИГЛА/БИС",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A50Toggle": "A50 კდწ და განთების ჩართვა",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A51Toggle": "A51 კდწ და განთების გამორთვა",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A23Toggle": "A23 საავარიო ჩართვა მოტორ–კომპრესორის",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A14Toggle": "A14 18 მავთული",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A75Toggle": "A75 კაბინის გათბობა",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A1Toggle": "A1  სვლა 1",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A2Toggle": "A2  სვლა 2",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A3Toggle": "A3  სვლა 3",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A17Toggle": "A17 დაბრუნება გდ",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A62Toggle": "A62 რადიოკავშირი",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A29Toggle": "A29 რადიო ხმოვანება",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A5Toggle": "A5 ",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A6Toggle": "A6  მუხრიჭი 1",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A8Toggle": "A8  სარქველი #1, #2",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A20Toggle": "A20 სვლა 1, 20 მავთული",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A25Toggle": "A25 ხელის მუხრჭი",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A22Toggle": "A22 ჩართვა КК",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A30Toggle": "A30 საერო ძრავის რიტორიტის კონტროლერი",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A39Toggle": "A39 ავარიული მართვა",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A44Toggle": "A44 მატარებლის ავარიული მართვა",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A80Toggle": "A80 საერო ძრავის გადამრთველის მდგომარეობები",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A65Toggle": "A65 სალონის განათება",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.L_5Toggle": "А49 ავარიული განათება",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A24Toggle": "A24 ბატარეის მუხტი",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A32Toggle": "A32 მარჯვენა კარების გაღება",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A31Toggle": "A31 მარცხენა კარების გაღება",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A16Toggle": "A16 კარების დაკეტვავა",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A13Toggle": "A13 კარების სიგნალიზაცია",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A12Toggle": "A12 ავარიული კარების დაკეტვა,
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A7Toggle": "A7  წითელი ფარი ",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A9Toggle": "A9  წითელი ფარი",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A46Toggle": "A46 ფარები თეთრი",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV.A47Toggle": "A47 ფარები თეთრი",
    "Entities.gmod_subway_81-717_lvz.Buttons.Front.L_4Toggle": "ფარნების გათიშვა",
    "Entities.gmod_subway_81-717_lvz.Buttons.Front.VUSToggle": "გგფ: გამორთვა გაძლიერებული ფარების",
    "Entities.gmod_subway_81-717_lvz.Buttons.Front.VADToggle": "აკდ: ავარიული კარების დაკეტვის ჩართვა (გაუმართავობათავობა კარების კონტროლის)
    "Entities.gmod_subway_81-717_lvz.Buttons.Front.VAHToggle": "ასჩ: ავარიული სვლის ჩართვა (გაუმართავობა დაცვის პედლის)",
    "Entities.gmod_subway_81-717_lvz.Buttons.Front.KRPSet": "ასჩღ: ავარიული სვლის ჩართვის ღილაკი",
    "Entities.gmod_subway_81-717_lvz.Buttons.Front.RezMKSet": "ავარიული ჩართვა მოტორ–კომპრესორის",
    "Entities.gmod_subway_81-717_lvz.Buttons.Front.KDPSet": "მკღ: მარჯვენა კარების ღილაკი",
    "Entities.gmod_subway_81-717_lvz.Buttons.Front.KDPKToggle": "სახურავი მკღ ღილაკის",
    "Entities.gmod_subway_81-717_lvz.Buttons.Front.PN": "საჰაერო მუხრუჭის კონტროლი",
    "Entities.gmod_subway_81-717_lvz.Buttons.BPSNFront.!Voltage": "ძაბვის წრის კონტროლი",
    "Entities.gmod_subway_81-717_lvz.Buttons.BPSNFront.VMKToggle": "მოტორ–კომპრესორის ჩართვა",
    "Entities.gmod_subway_81-717_lvz.Buttons.BPSNFront.BPSNonToggle": "სსკბ: საკუთარი საჭიროების კვების ბლოკი",
    "Entities.gmod_subway_81-717_lvz.Buttons.BPSNFront.ARS13Set": "სარ 13ვ: შემოწმება საბილური ძაბვის სარ",
    "Entities.gmod_subway_81-717_lvz.Buttons.ParkingBrake.ParkingBrakeToggle": "პარკინგის მუხრუჭი",
    "Entities.gmod_subway_81-717_lvz.Buttons.ParkingBrake.DriverValveTLDisconnectToggle": "ორმაგი ზეწოლის მაგისრალის კრანი",
    "Entities.gmod_subway_81-717_lvz.Buttons.CabinDoor.CabinDoor": "კარები მემანქანის კაბინაში",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.!K16": "НЧ: სარ სიხშირის არ არსებობა",
    "Entities.gmod_subway_81-717_lvz.Buttons.RoundARS.!ARS0": "0: სარ სიგნალი გაჩერება",
    "Entities.gmod_subway_81-717_lvz.Buttons.RoundARS.!ARS40": "40: სიჩქარის შეზღუდვა 40კმ/ჩ",
    "Entities.gmod_subway_81-717_lvz.Buttons.RoundARS.!ARS60": "60: სიჩქარის შეზღუდვა 60 კმ/ჩ",
    "Entities.gmod_subway_81-717_lvz.Buttons.RoundARS.!ARS70": "70: სიჩქარის შეზღუდვა 70 კმ/ჩ",
    "Entities.gmod_subway_81-717_lvz.Buttons.RoundARS.!ARS80": "80: სიჩქარის შეზღუდვა 80 კმ/ჩ",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.!ARSOch": "НЧ: სარ სიხშირის არ არსებობა",
    "Entities.gmod_subway_81-717_lvz.Buttons.RoundARS.!ARS0": "0: სარ სიგნალი გაჩერება",
    "Entities.gmod_subway_81-717_lvz.Buttons.RoundARS.!ARS40": "40: სიჩქარის შეზღუდვა 40კმ/ჩ",
    "Entities.gmod_subway_81-717_lvz.Buttons.RoundARS.!ARS60": "60: სიჩქარის შეზღუდვა 60 კმ/ჩ",
    "Entities.gmod_subway_81-717_lvz.Buttons.RoundARS.!ARS70": "70: სიჩქარის შეზღუდვა 70 კმ/ჩ",
    "Entities.gmod_subway_81-717_lvz.Buttons.RoundARS.!ARS80": "80: სიჩქარის შეზღუდვა 80 კმ/ჩ",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.KHSet": "",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.KSZDSet": "",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.VAVToggle": "",
    "Entities.gmod_subway_81-717_lvz.Buttons.PUAVN.VZPToggle": "",
    "Entities.gmod_subway_81-717_lvz.Buttons.PassengerDoor1.PassengerDoor": "კარები მემანქანის კაბინაში სალონიდან",
    "Entities.gmod_subway_81-717_lvz.Buttons.Reverser.KVReverserDown": "რევერსი უკან",
    "Entities.gmod_subway_81-717_lvz.Buttons.Reverser.KVReverserUp": "რევერსი წინ",
    "Entities.gmod_subway_81-717_lvz.Buttons.EPKDisconnect.EPKToggle": "კრანი ЭПВ",
    "Entities.gmod_subway_81-717_lvz.Buttons.Help.ShowHelp": "მატარებლის ტარების დახმარება",
    "Entities.gmod_subway_81-717_lvz.Buttons.UAVAPanel.UAVAToggle": "უაგგ: ენივერსალური ავტომატური გაჩერების გამომრთველი (ავტომატური გაჩერების გამომრთვა)",
    "Entities.gmod_subway_81-717_lvz.Buttons.UAVAPanel.UAVAContactSet": "უაგგ: ენივერსალური ავტომატური გაჩერების გამომრთველი (კონტაქტის დაბრუნება)",
    "Entities.gmod_subway_81-717_lvz.Buttons.DriverValveDisconnect.DriverValveDisconnectToggle": "დაშორიშორების სარქველი",
    "Entities.gmod_subway_81-717_lvz.Buttons.DriverValveDisconnect.DriverValveBLDisconnectToggle": "კრანი ორმაგი სამუხრუჭე მაგისრალი",
    "Entities.gmod_subway_81-717_lvz.Buttons.AirDistributor.AirDistributorDisconnectToggle": "ჰაერის გამნაწილებლის გამორთვა",




    "Entities.gmod_subway_81-714_lvz.Buttons.GV.GVToggle": "მთავარი გამომრთველ",
    "Entities.gmod_subway_81-714_lvz.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "სამუხრუჭე მაგისრალის კიდური კრანი",
    "Entities.gmod_subway_81-717_lvz.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "ზეწოლის მაგისრალის კიდური კრანი",
    "Entities.gmod_subway_81-714_lvz.Buttons.RearDoor.RearDoor": "უკანა კარი",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Left.DriverValveBLDisconnectToggle": "კრანი ორმაგი სამუხრუჭე მაგისრალი",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Left.DriverValveTLDisconnectToggle": "ორმაგი ზეწოლის მაგისრალის კრანი",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Left.A65Toggle": "A65 A65 სალონის განათებ",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Left.A56Toggle": "A56 ბატარეის ჩართვა",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Left.A63Toggle": "A63 IGLA/BIS",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Left.A10Toggle": "A10 მოტორ–კომპრესორის მართვა",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Left.A30Toggle": "A30 საერო ძრავის რიტორიტის კონტროლერი",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Left.A80Toggle": "A80 საერო ძრავის გადამრთველის მდგომარეობები",
    "Entities.gmod_subway_81-714_lvz.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "სამუხრუჭე მაგისრალის კიდური კრანი",
    "Entities.gmod_subway_81-714_lvz.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "Кზეწოლის მაგისრალის კიდური კრანი",
    "Entities.gmod_subway_81-714_lvz.Buttons.FrontPneumatic.ParkingBrakeToggle": "პარკინგის მუხრუჭი",
    "Entities.gmod_subway_81-714_lvz.Buttons.AirDistributor.AirDistributorDisconnectToggle": "ჰაერის გამნაწილებლის გამორთვა",
    "Entities.gmod_subway_81-714_lvz.Buttons.FrontDoor.FrontDoor": "წინა კარი",
    "Entities.gmod_subway_81-714_lvz.Buttons.Battery.VBToggle": "ბგ: ბატარეის გამომრთველი",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A54Toggle": "A54 10АК მავთულის მართვა",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A27Toggle": "A27 ჩართვა კდწ და განათება",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A24Toggle": "A24 ბატარეის მუხტი",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A53Toggle": "A53 კვება КВЦ",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A13Toggle": "A13 კარებების სიგნალიზაცია",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A32Toggle": "A13 კარებების სიგნალიზაცია",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A31Toggle": "A31 მარცხენა კარების გაღება",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A16Toggle": "A16 კაბინის დაკეტვა",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A12Toggle": "A12 ავარიული კარების დაკეტვა",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A50Toggle": "A50 კდწ და განათების ჩართვა",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A51Toggle": "A51 კდწ და განათების გამორთვა",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A1Toggle": "A1  სვლა 1",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.KRPSet": "დაწყება:დაწყების ღილაკი",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.VozvratRPSet": "გადატვითვის დაბრუნება",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.RezMKSet": "ავარიული ჩართვა მოტორ–კომპრესორის,
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.VMKToggle": "მოტორ–კომპრესორის ჩართვა",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.BPSNonToggle": "სსკბ: საკუთარი საჭიროების კვების ბლოკი",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A2Toggle": "A2  სვლა 2",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A3Toggle": "A3  სვლა 3",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A17Toggle": "A17 დაბრუნება გდ",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A5Toggle": "A5  ",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A6Toggle": "A6  მუხრუჭი 1",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A8Toggle": "A8  სარქველი #1, #2",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A20Toggle": "A20 სვლა 1, 20 მავთული",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A25Toggle": "A25 ხელის მუხრუჭი",
    "Entities.gmod_subway_81-717_lvz.Buttons.AV_1.1:A22Toggle": "A22 ჩართვა КК",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A23Toggle": "A23 ავარიული მოტორ–კომპრესორის ჩართვა",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A39Toggle": "A39 ავარიული მართვა",
    "Entities.gmod_subway_81-714_lvz.Buttons.AV_Right.A14Toggle": "A14 18 მავთული",
}
]]
