return [[
{
    "Lang": "geo",
    "Name": "Goergian",

    "Entities.gmod_subway_ezh.Buttons.HelperPanel.VDLSet": "მკგ: მარცხენა კარების გამომრთველი",
    "Entities.gmod_subway_ezh.Buttons.HelperPanel.VUD2Toggle": "კმგ2: კარების მართვის გამომრთველი",
    "Entities.gmod_subway_ezh.Buttons.Meters.!TotalVoltmeter": "ვოლტმეტრი მაღალი ძაბვის (кВ)",
    "Entities.gmod_subway_ezh.Buttons.Meters.!TotalAmpermeter": "ამპერმეტრი (А)",
    "Entities.gmod_subway_ezh.Buttons.AV2.R_RadioToggle": "+50ვ: ბლოკი მართვის РРИ и ПНМ (რადიოინფორმატორის ჩართვა)",
    "Entities.gmod_subway_ezh.Buttons.AV2.RSTToggle": "რს: რადიოსადგური",
    "Entities.gmod_subway_ezh.Buttons.AV2.UOSToggle": "УОС: სიჩქარის შემზღვუდელი რუმბლერი ",
    "Entities.gmod_subway_ezh.Buttons.AB1.AB1Set": "სარ სისტემის გადასვლა АБ(მემანქანის კნოპკა)",
    "Entities.gmod_subway_ezh.Buttons.KAH.KAHToggle": "ТАХ: ავარიული სვლის ტუმბლერი ",
    "Entities.gmod_subway_ezh.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "ზეწოლის მაგისრალის კიდური კრანი",
    "Entities.gmod_subway_ezh_2.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "სამუხრუჭე მაგისრალის კიდური კრანი",
    "Entities.gmod_subway_ezh.Buttons.AVU.AVULight": "ნათურა:ჩართულია მაგ (მართვის ავტომატური გამომრთველი)",
    "Entities.gmod_subway_ezh.Buttons.AVU.OtklAVUToggle": "მართვის ავტომატური გამომრთვის გათიშვა (გაუმართავობა მაგ)",
    "Entities.gmod_subway_ezh.Buttons.Main.DIPonSet": "ჩრთ. განთ.: განათების ჩართვა",
    "Entities.gmod_subway_ezh.Buttons.Main.DIPoffSet": "გამრთ. განათ.: განათებუს გამორთვა (ზარი)",
    "Entities.gmod_subway_ezh.Buttons.Main.KDPSet": "მკღ: მარჯვენა კარები",
    "Entities.gmod_subway_ezh.Buttons.Main.KDLSet": "მკღ: მარცხენა კარები",
    "Entities.gmod_subway_ezh.Buttons.Main.DoorSelectToggle": "კარების მახარის არჩევის სახურავი",
    "Entities.gmod_subway_ezh.Buttons.Main.KVTSet": "მმღ: მუხრუჭის მოქმედების ღილაკი (სარ გაუქმება)",
    "Entities.gmod_subway_ezh.Buttons.Main.VUSToggle": "გადამრთველი: ახლო შუქი/დალნები",
    "Entities.gmod_subway_ezh.Buttons.Main.ALSToggle": "გადამრთველი: ასს",
    "Entities.gmod_subway_ezh.Buttons.Main.ALSFreqToggle": "გადამრთველი: დეკიპტერი (სარ 2/6 ქვემოთ, სარ 1/5 ქვემოთ)",
    "Entities.gmod_subway_ezh.Buttons.Main.ARSToggle": "გადამრთველი: სარ",
    "Entities.gmod_subway_ezh.Buttons.Main.KU1Toggle": "მჩ: მოტორ–კომპრესორის ჩართვა",
    "Entities.gmod_subway_ezh.Buttons.Main.KSNSet": "СН:გამაფრთხილებელი ჩართვა გდ–ს გაუმართავ ვაგონზე (გაუმართვაობის სიგნალიზაცია)",
    "Entities.gmod_subway_ezh.Buttons.Main.VozvratRPSet": "КУ9:დაბრუნება გდ",
    "Entities.gmod_subway_ezh.Buttons.Main.R_Program1Set": "რადიოინფორმატორი: პროგრამა 1",
    "Entities.gmod_subway_ezh.Buttons.Main.VUD1Toggle": "კდ: კარების დაკეტვა",
    "Entities.gmod_subway_ezh.Buttons.Main.KRZDSet": "კადღ: კარების ავარიული დაკეტვის ღილაკი",
    "Entities.gmod_subway_ezh.Buttons.AV1.VU3Toggle": "ВУ3: კაბინის განათება\n",
    "Entities.gmod_subway_ezh.Buttons.AV1.VU2Toggle": "ВУ2: ავარიული განათება (45ვ)\n",
    "Entities.gmod_subway_ezh.Buttons.AV1.VU1Toggle": "ВУ1: კაბინის ფეჩი (3кВт)\n",
    "Entities.gmod_subway_ezh.Buttons.Back1.!RignARS": "ტონალური მოწყობილობა სარ",
    "Entities.gmod_subway_ezh.Buttons.Back1.!USPM": "მმგკ (მოწყობილობა მემანქანე–მგზავრის კავშირი)",
    "Entities.gmod_subway_ezh.Buttons.Back1.!AK": "წნევის რეგულაცია",
    "Entities.gmod_subway_ezh.Buttons.Back1.!LVP": "ფარი დაბალვოლტიანი დამცველით",
    "Entities.gmod_subway_ezh.Buttons.RC1.RC1Toggle": "РЦР: Кулачковый разъединитель цепей АРС",
    "Entities.gmod_subway_ezh.Buttons.Lamp.L_3Toggle": "ნათურა: ინსტრუმენტის განათება",
    "Entities.gmod_subway_ezh.Buttons.DriverValveTLDisconnect.DriverValveTLDisconnectToggle": "ორმაგი ზეწოლის მაგისრალის კრანი",
    "Entities.gmod_subway_ezh.Buttons.VU.VUToggle": "მგ: მართვის გამომრთველი",
    "Entities.gmod_subway_ezh.Buttons.VU.RezMKSet": "КУ15:ავარიული მოტორ–კომპრესორის ჩართვა",
    "Entities.gmod_subway_ezh.Buttons.VU.KRPSet": "ავარიული ჩართვა ",
    "Entities.gmod_subway_ezh.Buttons.FrontDoor.FrontDoor": "წინა კარი",
    "Entities.gmod_subway_ezh.Buttons.AB2.AB2Set": "სარ სისტემის გადასვლა რეჟიმში АБ(დამხმარე მემანქანის ღილაკი)",
    "Entities.gmod_subway_ezh.Buttons.PneumaticManometer.!LinesPressure": "წნევა მაგისრალში (წითელი: სამუხრუჭე, შავი: ზეწოლა)",
    "Entities.gmod_subway_ezh.Buttons.Stopkran.EmergencyBrakeValveToggle": "სტოპკრანი",
    "Entities.gmod_subway_ezh.Buttons.UAVAPanel.UAVAToggle": "უაგგ: უნივერსალური ავარიული გაჩერების გამომრთველი (ავტოსოპის გამორთვა)",
    "Entities.gmod_subway_ezh.Buttons.UAVAPanel.UAVAContactSet": "უაგგ: უნივერსალური ავარიული გაჩერების გამომრთველი (კონტაქტების აღდგენა)",
    "Entities.gmod_subway_ezh.Buttons.PneumaticPanels.!BrakeCylinder": "სამუხრუჭე ცილინდრი: წნევა სამუხრუჭე მაგისრალში (ТЦ)",
    "Entities.gmod_subway_ezh.Buttons.Battery.VBToggle": "ბგ: ბატარეების გამომრთველი(დამხმარე სქემები დაბალი ძაბვის)",
    "Entities.gmod_subway_ezh.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "სამუხრუჭე მაგისრალის კიდური კრანი",
    "Entities.gmod_subway_ezh.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "ზეწოლის მაგისრალის კიდური კრანი",
    "Entities.gmod_subway_ezh.Buttons.ASNP.R_ASNPMenuSet": "ინფორმატორი: მენიუ",
    "Entities.gmod_subway_ezh.Buttons.ASNP.R_ASNPUpSet": "ინფორმატორი: ზემოთ",
    "Entities.gmod_subway_ezh.Buttons.ASNP.R_ASNPDownSet": "ინფორმატორი: ქვემოთ",
    "Entities.gmod_subway_ezh.Buttons.ASNP.R_ASNPOnToggle": "ინფორმატორი: ჩართვა",
    "Entities.gmod_subway_ezh.Buttons.Tsepi.!BatteryVoltage": "ძაბვა მართვის სქემებზე",
    "Entities.gmod_subway_ezh.Buttons.PassengerDoor1.PassengerDoor": "კარები მემანქანის კაბინაში",
    "Entities.gmod_subway_ezh.Buttons.PassengerDoor.PassengerDoor": "კარი სალონიდან",
    "Entities.gmod_subway_ezh.Buttons.GV.GVToggle": "მთავარი ჩამრთველი",
    "Entities.gmod_subway_ezh.Buttons.LampsALS.!L80": "80: სიჩქარის შეზღუდვა 80 კმ/სთ",
    "Entities.gmod_subway_ezh.Buttons.LampsALS.!L70": "70: სიჩქარის შეზღუდვა 70 კმ/სთ",
    "Entities.gmod_subway_ezh.Buttons.LampsALS.!L60": "60: სიჩქარის შეზღუდვა 60 კმ/სთ",
    "Entities.gmod_subway_ezh.Buttons.LampsALS.!L40": "40: სიჩქარის შეზღუდვა 40კმ/სთ",
    "Entities.gmod_subway_ezh.Buttons.LampsALS.!L0": "0: სიჩქარის შეზღუდვა 0კმ/სთ",
    "Entities.gmod_subway_ezh.Buttons.LampsALS.!LNF": "ОЧ: სარ სიგნალის არ არსებობა",
    "Entities.gmod_subway_ezh.Buttons.DriverValveBLDisconnect.DriverValveBLDisconnectToggle": "ორმაგი მუხრუჭის მაგისტრალის კრანი",
    "Entities.gmod_subway_ezh.Buttons.CabinDoor.CabinDoor": "კარები მემანქანის კაბინაში",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.IGLA1USet": "ИГЛА: პრიველი ღილაკი ზემოთ",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.IGLA1Set": "ИГЛА: პირველი ღილაკი",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.IGLA1DSet": "ИГЛА: პირველი ღილაკი ქვემოთ",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.IGLA2USet": "ИГЛА: მეორე ღილაკი ზემოთ",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.IGLA2Set": "ИГЛА: მეორე ღილაკი",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.IGLA2DSet": "ИГЛА: მეორე ღილაკი ქვემოთ",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.!IGLASR": "ИГЛА: SR",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.!IGLARX": "ИГЛА: RX",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.!IGLAErr": "ИГЛА: გაუმართავობა",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.!IGLAOSP": "ИГЛА: ОСП",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.!IGLAPI": "ИГЛА: ПИ",
    "Entities.gmod_subway_ezh.Buttons.IGLAButtons.!IGLAOff": "ИГЛА: გამრთ",
    "Entities.gmod_subway_ezh.Buttons.Lamps.!RedRP": "დდ: წითელი ღილაკი დატვირთვის დაბრუნება",
    "Entities.gmod_subway_ezh.Buttons.Lamps.!LPU": "თანმიმდევრობა (მაღალი ძაბვის არარსებობისას ტრაქტაციისა და დამუხრუჭების რეჟიმებში გადართვის სისწორე)",
    "Entities.gmod_subway_ezh.Buttons.Lamps.!VD": "ძგ: ძრავის გამორთვა კონტროლი LED (ЛКВД)",
    "Entities.gmod_subway_ezh.Buttons.Lamps.!KT": "მკ: მუხრუჭის კონტროლი(ეფექტური მუხრუჭი)",
    "Entities.gmod_subway_ezh.Buttons.Lamps.!AB": "მწვანე AБ: ავტობლოკირებულ გადასრბენზე ნებისდამრთველი (არარეკომენდირებული გადასრბენი).",
    "Entities.gmod_subway_ezh.Buttons.Lamps.!Doors": "კარები: მატარებლის კარების სიგნალიზაცია",
    "Entities.gmod_subway_ezh.Buttons.Lamps.!LN": "მნ: მიმართულების ნათურა",
    "Entities.gmod_subway_ezh.Buttons.Lamps.!Sbor": "ნათურა შედგენა: შეცდომა ელექტრული სქემები შედგენისას (გაუმართვაობის სიგნალიზაცია)",
    "Entities.gmod_subway_ezh.Buttons.EPKDisconnect.EPKToggle": "კრანი ЭПК",
    "Entities.gmod_subway_ezh.Buttons.AVMain.AV8BToggle": "АВ-8Б: ავტომატური გამომრთველი (მაღალი ძაბვის დამხმარე სქემები)",
    "Entities.gmod_subway_ezh.Buttons.KRR.KRRToggle": "რდღ: რევერსორის დაბრუნების ღილაკი",
    "Entities.gmod_subway_ezh.Buttons.ParkingBrake.ParkingBrakeLeft": "ხელის მუხრუჭის მობრუნება",
    "Entities.gmod_subway_ezh.Buttons.ParkingBrake.ParkingBrakeRight": "ხელის მუხრუჭის მობრუნება",
    "Entities.gmod_subway_ezh.Buttons.AirDistributor.AirDistributorDisconnectToggle": "დისტრიბუტორის ჩართვა",



    "Entities.gmod_subway_ezh1.Buttons.Stopkran.EmergencyBrakeValveToggle": "სტოპკრანი",
    "Entities.gmod_subway_ezh1.Buttons.DriverValveBLTLDisconnect.DriverValveBLDisconnectToggle": "ორმაგი მუხრუჭის მაგისტრალის კრანი",
    "Entities.gmod_subway_ezh1.Buttons.DriverValveBLTLDisconnect.DriverValveTLDisconnectToggle": "ორმაგი ზეწოლის მაგისრალის კრანი",
    "Entities.gmod_subway_ezh1.Buttons.PneumaticPanels.!CylinderPressure": "სამუხრუჭე ცილინდრი: წნევა სამუხრუჭე მაგისრალში (ТЦ)",
    "Entities.gmod_subway_ezh1.Buttons.Battery.VBToggle": "ბგ: ბატარეების გამომრთველი(დამხმარე სქემები დაბალი ძაბვის)",
    "Entities.gmod_subway_ezh1.Buttons.Meters.!TotalVoltmerer": "ვოლტმეტრი მაღალი ძაბვის (кВ)",
    "Entities.gmod_subway_ezh.Buttons.Meters.!TotalAmpermeter": "ამპერმეტრი (А)",
    "Entities.gmod_subway_ezh1.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "სამუხრუჭე მაგისრალის კიდური კრანი",
    "Entities.gmod_subway_ezh.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "ზეწოლის მაგისრალის კიდური კრანი",
    "Entities.gmod_subway_ezh1.Buttons.RearDoor.RearDoor": "კარები სალონიდან",
    "Entities.gmod_subway_ezh1.Buttons.Tsepi.!BatteryVoltage": "ძაბვა მართვის სქემებზე",
    "Entities.gmod_subway_ezh1.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "სამუხრუჭე მაგისრალის კიდური კრანი",
    "Entities.gmod_subway_ezh.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "ზეწოლის მაგისრალის კიდური კრანი",
    "Entities.gmod_subway_ezh1.Buttons.PassengerDoor.PassengerDoor": "კარი სალონიდან",
    "Entities.gmod_subway_ezh1.Buttons.Back2.!HVFuses": "მაღალი ძაბვის ბლოკი",
    "Entities.gmod_subway_ezh1.Buttons.Back2.!Relays": "ყუთი ბატარეის დამტენით და ჰაერის დისტრიბუტორით",
    "Entities.gmod_subway_ezh1.Buttons.Back2.!Heater": "ღუმელი",
    "Entities.gmod_subway_ezh1.Buttons.Main.RedRP": "დდ: წითელი ღილაკი დატვირთვის დაბრუნება",
    "Entities.gmod_subway_ezh1.Buttons.Main.GreenRP": "მწვანე დდ: მწვანე ღილაკი დატვირთვის დაბრუნება (დატვირთვის სიგნალიზაცია)",
    "Entities.gmod_subway_ezh1.Buttons.Main.SD": "ლურჯი ნათურა კს: მატარებლის კარების სიგნალიზაცია",
    "Entities.gmod_subway_ezh1.Buttons.Main.DIPonSet": "КУ4: განათების ჩართვა",
    "Entities.gmod_subway_ezh1.Buttons.Main.DIPoffSet": "КУ5:განათების გამორთვა",
    "Entities.gmod_subway_ezh1.Buttons.Main.VozvratRPSet": "გადამრთველი: დატვირთვის დაბრუნება",
    "Entities.gmod_subway_ezh1.Buttons.Main.KSNSet": "გადამრთველი: გამაფრთხილებელი ჩართვა გდ–ს გაუმართავ ვაგონზე (გაუმართვაობის სიგნალიზაცია)",
    "Entities.gmod_subway_ezh1.Buttons.Main.KDPSet": "მკღ: მარჯვენა კარები",
    "Entities.gmod_subway_ezh1.Buttons.Main.KRZDSet": "კადღ: კარების ავარიული დაკეტვის ღილაკი",
    "Entities.gmod_subway_ezh1.Buttons.Main.KDLSet": "КУ12: მარცხენა კარები",
    "Entities.gmod_subway_ezh1.Buttons.Main.KU1Toggle": "გადამრთველი:მოტორ–კომპრესორის ჩართვა",
    "Entities.gmod_subway_ezh1.Buttons.Main.VUD1Toggle": "გადამრთველი: კარების დაკეტვა",
    "Entities.gmod_subway_ezh1.Buttons.AV1.VU3Toggle": "ВУ3: კაბინის განათება",
    "Entities.gmod_subway_ezh1.Buttons.AV1.VU2Toggle": "ВУ2: ავარიული განათება (45ვ)",
    "Entities.gmod_subway_ezh1.Buttons.AV1.VU1Toggle": "ВУ1: კაბინის ფეჩი (3კილოვოლტი)",
    "Entities.gmod_subway_ezh1.Buttons.AVMain.AV8BToggle": "АВ-8Б: ავტომატური გამომრთველი (მაღალი ძაბვის დამხმარე სქემები)",
    "Entities.gmod_subway_ezh1.Buttons.CabinDoor.CabinDoor1": "კარები მემანქანის კაბინაში",
    "Entities.gmod_subway_ezh1.Buttons.Front.FrontDoor": "წნა კარები",
    "Entities.gmod_subway_ezh1.Buttons.PassengerDoor1.PassengerDoor": "კარები სალონიდან",
    "Entities.gmod_subway_ezh1.Buttons.AirDistributor.AirDistributorDisconnectToggle": "ჰაერის დისტრიბუტორის გამორთვა",
    "Entities.gmod_subway_ezh1.Buttons.GV.GVToggle": "მთავარი გამომრთველი",
    "Entities.gmod_subway_ezh1.Buttons.VU.VUToggle": "მგ: მართვის გამომრთველი",
    "Entities.gmod_subway_ezh1.Buttons.HelperPanel.VUD2Toggle": "კმგ2: კარების მართვის გამომრთველი",
    "Entities.gmod_subway_ezh1.Buttons.HelperPanel.VDLSet": "მკგ: მარცხენა კარების გამომრთველი",
    "Entities.gmod_subway_ezh1.Buttons.ParkingBrake.ParkingBrakeLeft": "ხელის მუხრუჭის მობრუნება",
    "Entities.gmod_subway_ezh.Buttons.ParkingBrake.ParkingBrakeRight": "ხელის მუხრუჭის მობრუნება",
    "Entities.gmod_subway_ezh1.Buttons.PneumaticManometer.!LinesPressure": "წნევა მაგისრალში (წითელი: სამუხრუჭე, შავი: ზეწოლა)"
}
]]
