return [[
{
	"Lang": "geo",
	"Name": "Georgian",

	"Spawner.Title": "მატარებლების შემქმნელი",
	"Spawner.Trains1": "მატარებლების",
	"Spawner.Trains2": "მაქსმალური",
	"Spawner.WagNum": "ვაგონები",
	"Spawner.AutoCouple": "ვაგონების ავტომატიური მიერთება",

	"Entities.gmod_subway_81-717_mvm.Spawner.Texture.Name": "კორპუსის ფერი",
	"Entities.gmod_subway_81-717_mvm.Spawner.PassTexture.Name": "სალონის ფერი",
	"Entities.gmod_subway_81-717_mvm.Spawner.CabTexture.Name": "კაბინის ფერი",
	"Entities.gmod_subway_81-717_mvm.Spawner.Announcer.Name": "ინფორმატორის ხმა",
	"Entities.gmod_subway_81-717_mvm.Spawner.Lighter.Name": "სანთებელას ქონა",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.Name": "ტიპი სარ პანელის",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.1": "სტანდარტული(ოთხკუთხედი ნათურები)",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.2": "სტანდარტული(მრგვალი ნათურები)",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.3": "კიევური/სპბ",
	"Entities.gmod_subway_81-717_mvm.Spawner.ARSType.4": "სარ ძველი პანელი",
	"Entities.gmod_subway_81-717_mvm.Spawner.Cran.Name": "კრანის ტიპი",
	"Entities.gmod_subway_81-717_mvm.Spawner.Cran.1": "334",
	"Entities.gmod_subway_81-717_mvm.Spawner.Cran.2": "013",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.Name": "მასკის ტიპი",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.1": "2-2",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.2": "2-2-2",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.3": "1-4-1 ტიპი ბამპერის 1",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.4": "1-4-1 ტიპი ბამპერის 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.5": "1-1",
	"Entities.gmod_subway_81-717_mvm.Spawner.MaskType.6": "რეტრო",
	"Entities.gmod_subway_81-717_mvm.Spawner.LED.Name": "ქსენონური ფარები",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.Name": "სსკბ ტიპი",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.1": "ძველი ხმა მაღალი ტონით",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.2": "ძველი ხმა საშუალო ტონით",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.3": "სტანდარტული(სპგ–დან)",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.4": "სტანდარტული(ТКЛ)",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.5": "სტანდარტული",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.6": "კიევის",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.7": "ძველი",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.8": "სტანდარტული 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.9": "სტანდარტული 3",
	"Entities.gmod_subway_81-717_mvm.Spawner.BPSNType.10": "უხმო(БПН-115)",
	"Entities.gmod_subway_81-717_mvm.Spawner.NewKV.Name": "ახალი მოდელი ГРКВ",
	"Entities.gmod_subway_81-717_mvm.Spawner.HornType.Name": "პეტერბურგული ტიფონი",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.Name": "ხმა სიგნალის",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.1": "ძველი",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.2": "სტანდარტული დაბალი ტონით",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.3": "სტანდარტული მაღალი ტონით",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.4": "სტანდარტული შუალედური დაბალი ტონით",
	"Entities.gmod_subway_81-717_mvm.Spawner.RingType.5": "სტანდარტული შუალედური მაღალი ტონით",
	"Entities.gmod_subway_81-717_mvm.Spawner.NM.Name": "წნევა ზეწოლის მაგისრალიში",
	"Entities.gmod_subway_81-717_mvm.Spawner.Battery.Name": "ჩრთ. ბატარეა",
	"Entities.gmod_subway_81-717_mvm.Spawner.Switches.Name": "ჩრთ. ყველა ავტომატები",
	"Entities.gmod_subway_81-717_mvm.Spawner.SwitchesR.Name": "ავტომატები იქნება ჩართული შემთხვევით",
	"Entities.gmod_subway_81-717_mvm.Spawner.DoorsL.Name": "მარცხენა კარების გაღება",
	"Entities.gmod_subway_81-717_mvm.Spawner.DoorsR.Name": "მარჯვენა კარების გაღება",
	"Entities.gmod_subway_81-717_mvm.Spawner.GV.Name": "ჩრთ. მთავარი ჩამრთველი",
	"Entities.gmod_subway_81-717_mvm.Spawner.PB.Name": "ჩრთ. პარკინგის მუხრუჭი",
	"Entities.gmod_subway_81-717_mvm.Spawner.BortLampType.Name": "საბორტო ნათურების ტიპი",
	"Entities.gmod_subway_81-717_mvm.Spawner.BortLampType.1": "ჰორიზონტალური",
	"Entities.gmod_subway_81-717_mvm.Spawner.BortLampType.2": "ვერტიკალური",
	"Entities.gmod_subway_81-717_mvm.Spawner.MVM.Name": "ნიშანი МВМ",
	"Entities.gmod_subway_81-717_mvm.Spawner.HandRail.Name": "ხელის მოსაკიდის ტიპი",
	"Entities.gmod_subway_81-717_mvm.Spawner.HandRail.1": "ძველი",
	"Entities.gmod_subway_81-717_mvm.Spawner.HandRail.2": "ახალი",
	"Entities.gmod_subway_81-717_mvm.Spawner.SeatType.Name": "სკამების ტიპი",
	"Entities.gmod_subway_81-717_mvm.Spawner.SeatType.1": "ძველი",
	"Entities.gmod_subway_81-717_mvm.Spawner.SeatType.2": "ახალი",
	"Entities.gmod_subway_81-717_mvm.Spawner.LampType.Name": "ნათურების ტიპი",
	"Entities.gmod_subway_81-717_mvm.Spawner.LampType.1": "ტიპი 1",
	"Entities.gmod_subway_81-717_mvm.Spawner.LampType.2": "ტიპი 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.LampType.3": "ტიპი 3",
	"Entities.gmod_subway_81-717_mvm.Spawner.Breakers.Name": "ავტომატები მარჯვნივ",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.Name": "რეკლამა",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.1": "ტიპი 1",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.2": "ტიპი 2",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.3": "ტიპი 3",
	"Entities.gmod_subway_81-717_mvm.Spawner.Adverts.4": "რეკლამის გარეშე",

	"Entities.gmod_subway_81-720.Spawner.Texture.Name": "კორპუსის ფერი",
	"Entities.gmod_subway_81-720.Spawner.PassTexture.Name": "სალონის ფერი",
	"Entities.gmod_subway_81-720.Spawner.CabTexture.Name": "კაბინის ფერი",
	"Entities.gmod_subway_81-720.Spawner.Announcer.Name": "ინფორმატორი",
	"Entities.gmod_subway_81-720.Spawner.Scheme.Name": "კარებზემო სქემა",
	"Entities.gmod_subway_81-720.Spawner.PassSchemesInvert.Name": "ინვერტული კარებზემო სქემები",
	"Entities.gmod_subway_81-720.Spawner.NM.Name": "წნევა ზეწოლის მაგისრალიში",
	"Entities.gmod_subway_81-720.Spawner.Battery.Name": "ჩრთ. ბატარეა",
	"Entities.gmod_subway_81-720.Spawner.BRU.Name": "ჩრთ. БРУ(მმ)",
	"Entities.gmod_subway_81-720.Spawner.PVZR.Name": "ავტომატები ПВЗ–ზე იქნება შემთხვევით ჩართული",
	"Entities.gmod_subway_81-720.Spawner.PPZ.Name": "ჩრთ. ყველა მატარებლების ავტომატები",
	"Entities.gmod_subway_81-720.Spawner.PPZDepot.Name": "გამორთ. ავტომატები როგორც დეპოში",
	"Entities.gmod_subway_81-720.Spawner.PPZR.Name": "ავტომატები ППЗ-ზე იქნება ჩართული შემთხვევით",
	"Entities.gmod_subway_81-720.Spawner.DoorsL.Name": "მარცხენა კარების გაღება",
	"Entities.gmod_subway_81-720.Spawner.DoorsR.Name": "მარჯვენა კარების გაღება",

	"Entities.gmod_subway_81-722.Spawner.Texture.Name": "კორპუსის ფერი",
	"Entities.gmod_subway_81-722.Spawner.PassTexture.Name": "სალონის ფერი",
	"Entities.gmod_subway_81-722.Spawner.CabTexture.Name": "კაბინის ფერი",
	"Entities.gmod_subway_81-722.Spawner.Announcer.Name": "ინფორმატორი",
	"Entities.gmod_subway_81-722.Spawner.Scheme.Name": "კარებზემო სქემა",
	"Entities.gmod_subway_81-722.Spawner.SarmatInvert.Name": "ინვერტული კარებზემო სქემები",",
	"Entities.gmod_subway_81-722.Spawner.NM.Name": "წნევა ზეწოლის მაგისრალიში",
	"Entities.gmod_subway_81-722.Spawner.Battery.Name": "ჩრთ. ბატარეა",
	"Entities.gmod_subway_81-722.Spawner.Switches.Name": "ჩრთ. ყველა ავტომატები",
	"Entities.gmod_subway_81-722.Spawner.SwitchesR.Name": "ავტომატები იქნება ჩართული შემთხვევით",
	"Entities.gmod_subway_81-722.Spawner.DoorsL.Name": "მარცხენა კარების გაღება",
	"Entities.gmod_subway_81-722.Spawner.DoorsR.Name": "მარჯვენა კარების გაღება",


	"Entities.gmod_subway_ezh.Spawner.Texture.Name": "კორპუსის ფერი",
	"Entities.gmod_subway_ezh.Spawner.PassTexture.Name": "სალონის ფერი",
	"Entities.gmod_subway_ezh.Spawner.CabTexture.Name": "კაბინის ფერი",
	"Entities.gmod_subway_ezh.Spawner.Announcer.Name": "ინფორმატორი",
	"Entities.gmod_subway_ezh.Spawner.HornType.Name": "პეტერბურგული ტიფონი",
	"Entities.gmod_subway_ezh.Spawner.NM.Name": "წნევა ზეწოლის მაგისრალიში",
	"Entities.gmod_subway_ezh.Spawner.Battery.Name": "ჩრთ. ბატარეა",
	"Entities.gmod_subway_ezh.Spawner.AV8B.Name": "ჩრთ. АВ8Б",
	"Entities.gmod_subway_ezh.Spawner.DoorsL.Name": "მარცხენა კარების გაღება",
	"Entities.gmod_subway_ezh.Spawner.DoorsR.Name": "მარჯვენა კარების გაღება",
	"Entities.gmod_subway_ezh.Spawner.GV.Name": "ჩრთ. მთავარი ჩამრთველი",

	"Entities.gmod_subway_em508.Spawner.Texture.Name": "კორპუსის ფერი",
	"Entities.gmod_subway_em508.Spawner.PassTexture.Name": "სალონის ფერი",
	"Entities.gmod_subway_em508.Spawner.CabTexture.Name": "კაბინის ფერი",
	"Entities.gmod_subway_em508.Spawner.Announcer.Name": "ინფორმატორი",
	"Entities.gmod_subway_em508.Spawner.HornType.Name": "პეტერბურგული ტიფონი",
	"Entities.gmod_subway_em508.Spawner.NM.Name": "წნევა ზეწოლის მაგისრალიში",
	"Entities.gmod_subway_em508.Spawner.Battery.Name": "ჩრთ. ბატარეა",
	"Entities.gmod_subway_em508.Spawner.AV8B.Name": "ჩრთ. АВ8Б",
	"Entities.gmod_subway_em508.Spawner.DoorsL.Name": "მარცხენა კარების გაღება",
	"Entities.gmod_subway_em508.Spawner.DoorsR.Name": "მარჯვენა კარების გაღება",
	"Entities.gmod_subway_em508.Spawner.GV.Name": "ჩრთ. მთავარი ჩამრთველი",

	"Entities.gmod_subway_ezh3.Spawner.Texture.Name": "კორპუსის ფერი",
	"Entities.gmod_subway_ezh3.Spawner.PassTexture.Name": "სალონის ფერი",
	"Entities.gmod_subway_ezh3.Spawner.CabTexture.Name": "კაბინის ფერი",
	"Entities.gmod_subway_ezh3.Spawner.Announcer.Name": "ინფორმატორი",
	"Entities.gmod_subway_ezh3.Spawner.HornType.Name": "პეტერბურგული ტიფონი",
	"Entities.gmod_subway_ezh3.Spawner.NM.Name": "წნევა ზეწოლის მაგისრალიში",
	"Entities.gmod_subway_ezh3.Spawner.Battery.Name": "ჩრთ. ბატარეა",
	"Entities.gmod_subway_ezh3.Spawner.AV8B.Name": "ჩრთ. АВ8Б",
	"Entities.gmod_subway_ezh3.Spawner.DoorsL.Name": "მარცხენა კარების გაღება",
	"Entities.gmod_subway_ezh3.Spawner.DoorsR.Name": "მარჯვენა კარების გაღება",
	"Entities.gmod_subway_ezh3.Spawner.GV.Name": "ჩრთ. მთავარი ჩამრთველი",

	"Entities.gmod_subway_81-717_lvz.Spawner.Texture.Name": "კორპუსის ფერი",
	"Entities.gmod_subway_81-717_lvz.Spawner.PassTexture.Name": "სალონის ფერი",
	"Entities.gmod_subway_81-717_lvz.Spawner.CabTexture.Name": "კაბინის ფერი",
	"Entities.gmod_subway_81-717_lvz.Spawner.Announcer.Name": "ინფორმატორი",
	"Entities.gmod_subway_81-717_lvz.Spawner.Lighter.Name": "სანთებელას ქონა",
	"Entities.gmod_subway_81-717_lvz.Spawner.Cran.Name": "კრანის ტიპი",
	"Entities.gmod_subway_81-717_lvz.Spawner.Cran.1": "334",
	"Entities.gmod_subway_81-717_lvz.Spawner.Cran.2": "013",
	"Entities.gmod_subway_81-717_lvz.Spawner.MaskType.Name": "მასკის ტიპი",
	"Entities.gmod_subway_81-717_lvz.Spawner.MaskType.1": "1-4-1",
	"Entities.gmod_subway_81-717_lvz.Spawner.MaskType.2": "Spawner.717.MaskType.4L",
	"Entities.gmod_subway_81-717_lvz.Spawner.MaskType.3": "2-2",
	"Entities.gmod_subway_81-717_lvz.Spawner.MaskType.4": "2-2-2",
	"Entities.gmod_subway_81-717_lvz.Spawner.MaskType.5": "1-3-1",
	"Entities.gmod_subway_81-717_lvz.Spawner.LED.Name": "ქსენონური ფარები",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.Name": "სსკბ ტიპი",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.1": "ძველი ხმა მაღალი ტონით",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.2": "ძველი ხმა საშუალო ტონით",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.3": "სტანდარტული(სპგ–დან)",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.4": "სტანდარტული(ТКЛ)",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.5": "სტანდარტული",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.6": "კიევის",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.7": "ძველი",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.8": "სტანდარტული 2",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.9": "სტანდარტული 3",
	"Entities.gmod_subway_81-717_lvz.Spawner.BPSNType.10": "უხმო(БПН-115)",
    "Entities.gmod_subway_81-717_lvz.Spawner.NewKV.Name": "ახალი მოდელი ГРКВ",
    "Entities.gmod_subway_81-717_lvz.Spawner.HornType.Name": "პეტერბურგული ტიფონი",
    "Entities.gmod_subway_81-717_lvz.Spawner.RingType.Name": "ხმა სიგნალის",
    "Entities.gmod_subway_81-717_lvz.Spawner.RingType.1": "ძველი",
    "Entities.gmod_subway_81-717_lvz.Spawner.RingType.2": "სტანდარტული დაბალი ტონით",
    "Entities.gmod_subway_81-717_lvz.Spawner.RingType.3": "სტანდარტული მაღალი ტონით",
    "Entities.gmod_subway_81-717_lvz.Spawner.RingType.4": "სტანდარტული შუალედური დაბალი ტონით",
    "Entities.gmod_subway_81-717_lvz.Spawner.RingType.5": "სტანდარტული შუალედური მაღალი ტონით",
    "Entities.gmod_subway_81-717_lvz.Spawner.NM.Name": "წნევა ზეწოლის მაგისრალიში",
    "Entities.gmod_subway_81-717_lvz.Spawner.Battery.Name": "ჩრთ. ბატარეა",
    "Entities.gmod_subway_81-717_lvz.Spawner.Switches.Name": "ჩრთ. ყველა ავტომატები",
    "Entities.gmod_subway_81-717_lvz.Spawner.SwitchesR.Name": "ავტომატები იქნება შემთხვევით ჩართული",
    "Entities.gmod_subway_81-717_lvz.Spawner.DoorsL.Name": "მარცხენა კარების გაღება",
    "Entities.gmod_subway_81-717_lvz.Spawner.DoorsR.Name": "მარჯვენა კარების გაღება",
    "Entities.gmod_subway_81-717_lvz.Spawner.GV.Name": "ჩრთ. მთავარი ჩამრთველი",
    "Entities.gmod_subway_81-717_lvz.Spawner.PB.Name": "ჩრთ. პარკინგის მუხრუჭი",
    "Entities.gmod_subway_81-717_lvz.Spawner.BortLampType.Name": "საბორტო ნათურების ტიპი",
    "Entities.gmod_subway_81-717_lvz.Spawner.BortLampType.1": "ჰორიზონტალური",
    "Entities.gmod_subway_81-717_lvz.Spawner.BortLampType.2": "ვერტიკალური",
    "Entities.gmod_subway_81-717_lvz.Spawner.HandRail.Name": "ხელის მოსაკიდის ტიპი",
    "Entities.gmod_subway_81-717_lvz.Spawner.HandRail.1": "ძველი",
    "Entities.gmod_subway_81-717_lvz.Spawner.HandRail.2": "ახალი",
    "Entities.gmod_subway_81-717_lvz.Spawner.SeatType.Name": "სკამების ტიპი",
    "Entities.gmod_subway_81-717_lvz.Spawner.SeatType.1": "ძველი",
    "Entities.gmod_subway_81-717_lvz.Spawner.SeatType.2": "ახალი",
    "Entities.gmod_subway_81-717_lvz.Spawner.LampType.Name": "ნათურების ტიპი",
    "Entities.gmod_subway_81-717_lvz.Spawner.LampType.1": "ტიპი 1",
    "Entities.gmod_subway_81-717_lvz.Spawner.LampType.2": "ტიპი 2",
    "Entities.gmod_subway_81-717_lvz.Spawner.LampType.3": "ტიპი 3",
    "Entities.gmod_subway_81-717_lvz.Spawner.Breakers.Name": "ავტომატები მარჯვნივ",
    "Entities.gmod_subway_81-717_lvz.Spawner.Adverts.Name": "რეკლამა",
    "Entities.gmod_subway_81-717_lvz.Spawner.Adverts.1": "ტიპი 1",
    "Entities.gmod_subway_81-717_lvz.Spawner.Adverts.2": "ტიპი 2",
    "Entities.gmod_subway_81-717_lvz.Spawner.Adverts.3": "ტიპი 3",
    "Entities.gmod_subway_81-717_lvz.Spawner.Adverts.4": "რეკლამის გარეშე",

	"Entities.gmod_subway_81-703.Spawner.Texture.Name": "კორპუსის ფერი",
	"Entities.gmod_subway_81-703.Spawner.PassTexture.Name": "სალონის ფერი",
	"Entities.gmod_subway_81-703.Spawner.CabTexture.Name": "კაბინის ფერი",
	"Entities.gmod_subway_81-703.Spawner.Announcer.Name": "ინფორმატორი",
	"Entities.gmod_subway_81-703.Spawner.HornType.Name": "პეტერბურგული ტიფონი",
	"Entities.gmod_subway_81-703.Spawner.NM.Name": "წნევა ზეწოლის მაგისრალიში",
	"Entities.gmod_subway_81-703.Spawner.Battery.Name": "ჩრთ. ბატარეა",
	"Entities.gmod_subway_81-703.Spawner.AV8B.Name": "ჩრთ. АВ8Б",
	"Entities.gmod_subway_81-703.Spawner.DoorsL.Name": "მარცხენა კარების გაღება",
	"Entities.gmod_subway_81-703.Spawner.DoorsR.Name": "მარჯვენა კარების გაღება",
	"Entities.gmod_subway_81-703.Spawner.GV.Name": "ჩრთ. მთავარი მჩართველი",



	"Spawner.Close": დახურვა",
	"Spawner.Spawn": "მზადაა"
}
]]
