return [[
{
	"Lang": "geo",
	"Name": "Georgian",
	"Panel.Admin": "ადმინი",
	"Panel.Client": "კლიენტი",
	"Panel.DrawDebugInfo": "გამოჩენა გამართვის ინფორმაცია",
	"Panel.DisableCamAccel": "გამორთ. სიმულაცია თავის ქნევის",
	"Panel.DisableHoverText": "გამორთ. ამომსვლელი ტექსტი",
	"Panel.DrawCams": "კამაერების განაწილება",
	"Panel.FOV": "მხედველების ზონა",

	"Train.Common.Camera0": "მემანქანის ადგილი",

	"Train.Buttons.Sealed": "პლომბირებული",

	"Entities.gmod_subway_base.Name": "ბაზა მეტრო მატატარებლების",
	"Entities.gmod_subway_81-703.Name": "E",
	"Entities.gmod_subway_81-703_2.Name": "E (შუალედური)",
	"Entities.gmod_subway_81-717_mvm.Name": "81-717(МВМ თავი)",
	"Entities.gmod_subway_81-717_lvz.Name": "81-717(ЛВЗ თავი)",
	"Entities.gmod_subway_81-714_mvm.Name": "81-714(МВМ შუალედური)",
	"Entities.gmod_subway_81-714_lvz.Name": "81-714(ЛВЗ შუალედური)",
	"Entities.gmod_subway_81-7036.Name": "81-7036 (არ მუშაობს)",
	"Entities.gmod_subway_81-7037.Name": "81-7037 (არ მუშაობს)",
	"Entities.gmod_subway_81-720.Name": "81-720 (თავი)",
	"Entities.gmod_subway_81-721.Name": "81-721 (შუალედური)",
	"Entities.gmod_subway_81-722.Name": "81-722 (თავი)",
	"Entities.gmod_subway_81-723.Name": "81-723 (შუალედური ძრავიანი)",
	"Entities.gmod_subway_81-724.Name": "81-724 (შუალედური უძრავო)",
	"Entities.gmod_subway_e.Name": "Е (ძველ)",
	"Entities.gmod_subway_em.Name": "Ем",
	"Entities.gmod_subway_ema.Name": "Ема",
	"Entities.gmod_subway_ezh.Name": "Еж",
	"Entities.gmod_subway_ezh1.Name": "Еж1",
	"Entities.gmod_subway_em508.Name": "Ем-508",
	"Entities.gmod_subway_em508_int.Name": "Ем-508 *შუალედური)",
	"Entities.gmod_subway_ezh3.Name": "Еж3",
	"Entities.gmod_subway_ezh3ru1.Name": "Еж3 РУ1",
	"Entities.gmod_subway_ema508t.Name": "Ем-508Т",
	"Entities.gmod_subway_tatra_t3.Name": "Татра Т3",
	"Entities.gmod_subway_ai.Name": "მატარებელი კგ–თი",

	"Entities.gmod_train_bogey.Name": "ვაგონი ტროილერი",
	"Entities.gmod_train_couple.Name": "მისაბმელი",

	"Entities.gmod_track_pui.Name": "ПУИ",
	"Entities.gmod_track_mus_elektronika7.Name": "საათი \"ელექტრონიკა\"",
	"Entities.gmod_mus_clock_analog.Name": "Сისრიანი საათი",
	"Entities.gmod_track_clock_time.Name": "დიდი ინტერვალიანი საათი(დრო)",
	"Entities.gmod_track_clock_small.Name": "პატარა ინტერვალიანი საათი",
	"Entities.gmod_track_clock_interval.Name": "დიდი ინტერვალიანი საათი(ინტერვალი)",
	"Entities.gmod_track_switch.Name": "ისარი",
	"Entities.gmod_track_powermeter.Name": "ზაბვის შემცვლელი",
	"Entities.gmod_track_controller.Name": "დისპეჩერის პულტი(არ მუშაობს)",
	"Entities.gmod_track_udochka.Name": "ანკესი",
	"Entities.gmod_train_spawner.Name": "მატატარებლების შემქმნელი",

	"Train.703.VU": "მართვის გამომრთველი",
	"Train.703.Breakers1" : "ბატარეა",
	"Train.703.Breakers2" : "ავტომატები",
	"Train.703.RCARS" : "РЦ-АРС",
	"Train.703.Left" : "დამხმარეს პანელი",
	"Train.703.Parking" : "უაგგ და ხელის მუხრჭი",
	"Train.703.ASNP" : "АСНП",
	"Train.703.IGLA" : "ИГЛА",
	"Train.717.Breakers1": "ცენტრალური ავტომატები",
	"Train.717.VB1": "პანელი РЦ–თი",
	"Train.717.Breakers2": "მარჯვენა ავტომატები",
	"Train.717.VB2": "ქვედა პანელი РЦ–თი",
	"Train.717.UAVA": "უაგგ",
	"Train.717.Pneumo": "პნევმატური კრანები",
	"Train.717.Helpers": "პულტი დამხმარესი",
	"Train.717.Block4": "4 ბლოკი",
	"Train.717.IGLA": "ИГЛА",
	"Train.717.ASNP" : "АСНП",
	"Train.720.CameraCond": "კონდიციონერების პანელი",
	"Train.720.CameraPPZ": "პანელი მატარებლების დაცვის",
	"Train.720.CameraPV": "პანელი დამხმარე ღილაკების",
	"Train.720.CameraASNP": "АСНП",
	"Train.720.CameraVityaz": "САУ კავშირი",
	"Train.720.CameraKRMH": "კრანი КРМШ",
	"Train.720.CameraPVZ": "პანელი ვაგონის დაცვის",
	"Train.722.Breakers": "ავტომატები მატარებელის დაცვის",
	"Train.722.PU2_1": "პანელი ღილაკების",
	"Train.722.PU2_2": "პანელი გამომრთველების",
	"Train.722.Vityaz": "ეკრანი САУ კავშირი",
	"Train.722.SARMAT": "ეკრანი БМ ЦИК САРМАТ",
	"Train.722.CabLights": "პანელი კაბინის განება",
	"Train.722.Route": "მარშრუტის ნომრის დაყენება",
	"Train.722.Disconnects": "კიდური კრანები",
	"Train.722.KRMH": "გამომრთველი КРМШ и РВТБ"
}
]]
