return [[
{
    "Lang": "geo",
    "Name": "Georgian",


    "Entities.gmod_subway_em508.Buttons.Back.BackDoor": "უკანა კარი",
    "Entities.gmod_subway_em508.Buttons.HelperPanel.R_Program1Set": "პროგრამა 1",
    "Entities.gmod_subway_em508.Buttons.HelperPanel.R_Program2Set": "პროგრამა 2",
    "Entities.gmod_subway_em508.Buttons.HelperPanel.VDLSet": "მკგ: მარცხენა კარების გამომრთველი",
    "Entities.gmod_subway_em508.Buttons.HelperPanel.VUD2Toggle": "კმგ2: კარების მართვის გამომრთველი",
    "Entities.gmod_subway_em508.Buttons.AV2.RSTToggle": "რს: რადიოსადგური",
    "Entities.gmod_subway_em508.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "ზეწოლის მაგისრალის კიდური კრანი",
    "Entities.gmod_subway_em508_2.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "სამუხრუჭე მაგისრალის კიდური კრანი",
    "Entities.gmod_subway_em508.Buttons.AVU.AVULight": "ნათურა:ჩართულია მაგ (მართვის ავტომატური გამომრთველი)",
    "Entities.gmod_subway_em508.Buttons.AVU.OtklAVUToggle": "მართვის ავტომატური გამომრთვის გათიშვა (გაუმართავობა მაგ)",
    "Entities.gmod_subway_em508.Buttons.Back2.!HVFuses": "მაღალი ძაბვის ბლოკი",
    "Entities.gmod_subway_em508.Buttons.Back2.!Relays": "ყუთი ბატარეის დამტენით და ჰაერის დისტრიბუტორით",
    "Entities.gmod_subway_em508.Buttons.Back2.!Heater": "ფეჩი",
    "Entities.gmod_subway_em508.Buttons.Main.DoorSelectToggle": "გადამრთველი: კარების მახარის არჩევის",
    "Entities.gmod_subway_em508.Buttons.Main.DIPonSet": "ჩრთ. განთ.: განათების ჩართვა",
    "Entities.gmod_subway_em508.Buttons.Main.DIPoffSet": "გამრთ. განათ.: განათებუს გამორთვა",
    "Entities.gmod_subway_em508.Buttons.Main.VozvratRPSet": "დდგ: დაბრუნება დგ",
    "Entities.gmod_subway_em508.Buttons.Main.KSNSet": "ღგს:გამაფრთხილებელი ჩართვა გდ–ს გაუმართავ ვაგონზე (გაუმართვაობის სიგნალიზაცია)",
    "Entities.gmod_subway_em508.Buttons.Main.KRZDSet": "კადღ: კარების ავარიული დაკეტვის ღილაკი",
    "Entities.gmod_subway_em508.Buttons.Main.KSDSet": "კსკ: კარების სიგნალიზაციის კონტროლი(კს შემოწმება)",
    "Entities.gmod_subway_em508.Buttons.Main.KDPSet": "მკღ: მარჯვენა კარები",
    "Entities.gmod_subway_em508.Buttons.Main.KDLSet": "მკღ: მარცხენა კარები",
    "Entities.gmod_subway_em508.Buttons.Main.RezMKSet": "ამკ: ავარიული მოტორ–კომპრესორის ჩართვაа",
    "Entities.gmod_subway_em508.Buttons.Main.KU1Toggle": "მჩ: მოტორ–კომპრესორის ჩართვა",
    "Entities.gmod_subway_em508.Buttons.Main.VUD1Toggle": "კდ: კარების დაკეტვა",
    "Entities.gmod_subway_em508.Buttons.AV1.VU3Toggle": "ВУ3: კაბინის განათება\n",
    "Entities.gmod_subway_em508.Buttons.AV1.VU2Toggle": "ВУ2: ავარიული განათება\n",
    "Entities.gmod_subway_em508.Buttons.AV1.VU1Toggle": "ВУ1: კაბინის ფეჩი\n",
    "Entities.gmod_subway_em508.Buttons.Back1.!ULSPM": "УЭСПМ (მოწყობილობა კავშირი მგზავრი–მემანქანე)",
    "Entities.gmod_subway_em508.Buttons.Back1.!TonalARS": "ტონური მოწყობილობა - ზარი",
    "Entities.gmod_subway_em508.Buttons.Back1.!PressureRelay": "წნევის რეგულატორი",
    "Entities.gmod_subway_em508.Buttons.Back1.!Reproductor": "ხმამაღლამოლაპარაკე",
    "Entities.gmod_subway_em508.Buttons.Back1.!LVFuses": "დაბალი ძაბვის მექანიზმის დაცვა",
    "Entities.gmod_subway_em508.Buttons.Back1.R_UNchToggle": "კვება статива РРИ",
    "Entities.gmod_subway_em508.Buttons.Lamp.L_3Toggle": "ნათურა: პანელის განათება",
    "Entities.gmod_subway_em508.Buttons.DriverValveTLDisconnect.DriverValveTLDisconnectToggle": "ორმაგი ზეწოლის მაგისრალის კრანი",
    "Entities.gmod_subway_em508.Buttons.VU.VUToggle": "მგ: მართვის გამომრთველი",
    "Entities.gmod_subway_em508.Buttons.PneumaticManometer.!LinesPressure": "წნევა მაგისრალში (წითელი: სამუხრუჭე, შავი: ზეწოლა)",
    "Entities.gmod_subway_em508.Buttons.Stopkran.EmergencyBrakeValveToggle": "სტოპკრანი",
    "Entities.gmod_subway_em508.Buttons.LAMPS.SN": "ინიდიკატორი: გაუმართვაობის სიგნალიზაცია",
    "Entities.gmod_subway_em508.Buttons.LAMPS.RedRP": "ინიდიკატორი: წითელი ნართურა დატვირთვის დაბრუნება",
    "Entities.gmod_subway_em508.Buttons.LAMPS.SD": "ინიდიკატორი: კარების სიგნალიზაცია",
    "Entities.gmod_subway_em508.Buttons.LAMPS.GreenRP": "ინიდიკატორი: მწვანე ნართურა დატვირთვის დაბრუნება",
    "Entities.gmod_subway_em508.Buttons.LAMPS.UKS": "ინიდიკატორი: სიჩქარის კონტროლის მოწყობილობა УКС-20М",
    "Entities.gmod_subway_em508.Buttons.LAMPS.Red": "ინიდიკატორი: კაბინის გათბობა",
    "Entities.gmod_subway_em508.Buttons.LAMPS.AGS": "ნათურა: აშ მუშაობა (ავტომატური შუშისწმენდავი)",
    "Entities.gmod_subway_em508.Buttons.UAVAPanel.UAVAToggle": "უაგგ: უნივერსალური ავარიული გაჩერების გამომრთველი (ავტოსოპის გამორთვა)",
    "Entities.gmod_subway_em508.Buttons.UAVAPanel.UAVAContactSet": "უაგგ: უნივერსალური ავარიული გაჩერების გამომრთველი (კონტაქტების აღდგენა)",
    "Entities.gmod_subway_em508.Buttons.PneumaticPanels.!CylinderPressure": "სამუხრუჭე მანომეტრი: წნევა სამუხრუჭე მაგისრალში (ТЦ)",
    "Entities.gmod_subway_em508.Buttons.Battery.VBToggle": "ბგ: ბატარეების გამომრთველი(დამხმარე სქემები დაბალი ძაბვის)",
    "Entities.gmod_subway_em508.Buttons.Battery.R_RadioToggle": "რადიოინფორმატპორის კვება +50ვ",
    "Entities.gmod_subway_em508.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "სამუხრუჭე მაგისრალის კიდური კრანი",
    "Entities.gmod_subway_em508.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "ზეწოლის მაგისრალის კიდური კრანი",
    "Entities.gmod_subway_em508.Buttons.ASNP.R_ASNPMenuSet": "ინფორმატორი: მენიუ",
    "Entities.gmod_subway_em508.Buttons.ASNP.R_ASNPUpSet": "ინფორმატორი: ზემოთ",
    "Entities.gmod_subway_em508.Buttons.ASNP.R_ASNPDownSet": "ინფორმატორი: ქვემოთ",
    "Entities.gmod_subway_em508.Buttons.ASNP.R_ASNPOnToggle": "ინფორმატორი: ჩართვა",
    "Entities.gmod_subway_em508.Buttons.VU1.KRPSet": "РРП: საავარიო ჩართვა ",
    "Entities.gmod_subway_em508.Buttons.GV.GVToggle": "მთავარი მჩამრთველი",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.IGLA1USet": "ИГЛА: პრიველი ღილაკი ზემოთ",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.IGLA1Set": "ИГЛА: პირველი ღილაკი",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.IGLA1DSet": "ИГЛА: პირველი ღილაკი ქვემოთ",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.IGLA2USet": "ИГЛА: მეორე ღილაკი ზემოთ",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.IGLA2Set": "ИГЛА: მეორე ღილაკი",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.IGLA2DSet": "ИГЛА: მეორე ღილაკი ქვემოთ",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.!IGLASR": "ИГЛА: SR",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.!IGLARX": "ИГЛА: RX",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.!IGLAErr": "ИГЛА: გაუმართავობა",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.!IGLAOSP": "ИГЛА: ОСП",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.!IGLAPI": "ИГЛА: ПИ",
    "Entities.gmod_subway_em508.Buttons.IGLAButtons.!IGLAOff": "ИГЛА: გამრთ",
    "Entities.gmod_subway_em508.Buttons.PassengerDoor.PassengerDoor": "კარი სალონიდან მემანქანის კაბინაში",
    "Entities.gmod_subway_em508.Buttons.InfoTableSelect.PrevSign": "წინა წარწერა",
    "Entities.gmod_subway_em508.Buttons.InfoTableSelect.NextSign": "შემდეგი წარწერა",
    "Entities.gmod_subway_em508.Buttons.InfoTableSelect.Num2P": "მარშრუტი: რიცხვის გაზრდა 2",
    "Entities.gmod_subway_em508.Buttons.InfoTableSelect.Num2M": "მარშრუტი: რიცხვის შემცირება 2",
    "Entities.gmod_subway_em508.Buttons.InfoTableSelect.Num1P": "მარშრუტი: რიცხვის გაზრდა 1",
    "Entities.gmod_subway_em508.Buttons.InfoTableSelect.Num1M": "მარშრუტი: რიცხვის შემცირება 1",
    "Entities.gmod_subway_em508.Buttons.Front.FrontDoor": "წინა კარი",
    "Entities.gmod_subway_em508.Buttons.KRR.KRRSet": "KРР: ვერესორიბის მობრუნების ღილაკი",
    "Entities.gmod_subway_em508.Buttons.AGS.VUSToggle": "გადამრთველი: ახლო შუქი/დალნები",
    "Entities.gmod_subway_em508.Buttons.CabinDoor.CabinDoor": "კარები მემანქანის კაბინაში",
    "Entities.gmod_subway_em508.Buttons.PassengerDoor1.PassengerDoor": "კარები სალონიდან მემანქანის კაბინაში",
    "Entities.gmod_subway_em508.Buttons.ParkingBrake.ParkingBrakeLeft": "ხელის მუხრუჭის მობრუნება",
    "Entities.gmod_subway_em508.Buttons.ParkingBrake.ParkingBrakeRight": "ხელის მუხრუჭის მობრუნება",
    "Entities.gmod_subway_em508.Buttons.AVMain.AV8BToggle": "АВ-8Б: ავტომატური გამომრთველი (მაღალი ძაბვის დამხმარე სქემები)\n",
    "Entities.gmod_subway_em508.Buttons.Back3.!RTM": "სადისპეჩერო კავშირის პანელი",
    "Entities.gmod_subway_em508.Buttons.Back3.!ULSPMSpeaker": "ხმამაღლამოლაპარაკე ბლოკი კავშირი მგზავრი–მემანქანეს",
    "Entities.gmod_subway_em508.Buttons.Back3.!Amplifier": "ბლოკი სადისპეჩერო კავშირის გაძლიერების",
    "Entities.gmod_subway_em508.Buttons.DriverValveBLDisconnect.DriverValveBLDisconnectToggle": "ორმაგი მუხრუჭის მაგისტრალის კრანი",
    "Entities.gmod_subway_em508.Buttons.AirDistributor.AirDistributorDisconnectToggle": "ჰაერის დისტრიბუტორის ჩართვა",



    "Entities.gmod_subway_em508_int.Buttons.Stopkran.EmergencyBrakeValveToggle": "სტოპკრანი",
    "Entities.gmod_subway_em508_int.Buttons.Back.BackDoor": "უკანა კარი",
    "Entities.gmod_subway_em508_int.Buttons.HelperPanel.R_Program1Set": "პროგრამა 1",
    "Entities.gmod_subway_em508.Buttons.HelperPanel.R_Program2Set": "პროგრამა 2",
    "Entities.gmod_subway_em508.Buttons.HelperPanel.VDLSet": "მკგ: მარცხენა კარების გამომრთველი",
    "Entities.gmod_subway_em508.Buttons.HelperPanel.VUD2Toggle": "კმგ2: კარების მართვის გამომრთველი",
    "Entities.gmod_subway_em508_int.Buttons.DriverValveBLDisconnect.DriverValveBLDisconnectToggle": "ორმაგი მუხრუჭის მაგისტრალის კრანი",
    "Entities.gmod_subway_em508_int.Buttons.Battery.VBToggle": "ბგ: ბატარეების გამომრთველი(დამხმარე სქემები დაბალი ძაბვის)",
    "Entities.gmod_subway_em508_int.Buttons.Battery.R_RadioToggle": "რადიოინფორმატპორის კვება +50ვ",
    "Entities.gmod_subway_em508_int.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "სამუხრუჭე მაგისრალის კიდური კრანი",
    "Entities.gmod_subway_em508.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "ზეწოლის მაგისრალის კიდური კრანი",
    "Entities.gmod_subway_em508_int.Buttons.AirDistributor.AirDistributorDisconnectToggle": "ჰაერის დისტრიბუტორის ჩართვა",
    "Entities.gmod_subway_em508_int.Buttons.PassengerDoor.PassengerDoor": "კარები სალონიდან მემანქანის კაბინაში",
    "Entities.gmod_subway_em508_int.Buttons.VU1.KRPSet": "РРП: საავარიო ჩართვა ",
    "Entities.gmod_subway_em508_int.Buttons.UAVAPanel.UAVAToggle": "უაგგ: უნივერსალური ავარიული გაჩერების გამომრთველი (ავტოსოპის გამორთვა)",
    "Entities.gmod_subway_em508.Buttons.UAVAPanel.UAVAContactSet": "უაგგ: უნივერსალური ავარიული გაჩერების გამომრთველი (კონტაქტების აღდგენა)",
    "Entities.gmod_subway_em508_int.Buttons.Front.FrontDoor": "წინა კარი",
    "Entities.gmod_subway_em508_int.Buttons.Tsepi.!BatteryVoltage": "საკონტროლო წრე ძაბვა",
    "Entities.gmod_subway_em508_int.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "ზეწოლის მაგისრალის კიდური კრანი",
    "Entities.gmod_subway_em508_2.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "სამუხრუჭე მაგისრალის კიდური კრანი",
    "Entities.gmod_subway_em508_int.Buttons.InfoTableSelect.PrevSign": "წინა წარწერა",
    "Entities.gmod_subway_em508.Buttons.InfoTableSelect.NextSign": "შემდეგი წარწერა",
    "Entities.gmod_subway_em508.Buttons.InfoTableSelect.Num2P": "მარშრუტი: რიცხვის გაზრდა 2",
    "Entities.gmod_subway_em508.Buttons.InfoTableSelect.Num2M": "მარშრუტი: რიცხვის შემცირება 2",
    "Entities.gmod_subway_em508.Buttons.InfoTableSelect.Num1P": "მარშრუტი: რიცხვის გაზრდა 1",
    "Entities.gmod_subway_em508.Buttons.InfoTableSelect.Num1M": "მარშრუტი: რიცხვის შემცირება 1",
    "Entities.gmod_subway_em508_int.Buttons.Back2.!HVFuses": "მაღალი ძაბვის ბლოკი",
    "Entities.gmod_subway_em508_int.Buttons.Back2.!Relays": "ყუთი ბატარეის დამტენით და ჰაერის დისტრიბუტორით",
    "Entities.gmod_subway_em508_int.Buttons.Back2.!Heater": "ფეჩი",
    "Entities.gmod_subway_em508_int.Buttons.Main.GreenRP": "ნათურა: მწვანე ნართურა დატვირთვის დაბრუნება",
    "Entities.gmod_subway_em508_int.Buttons.Main.RedRP": "ნათურა: წითელი ნართურა დატვირთვის დაბრუნება",
    "Entities.gmod_subway_em508_int.Buttons.Main.SD": "ნათურა: კარების სიგნალიზაცია",
    "Entities.gmod_subway_em508_int.Buttons.Main.DIPonSet": "ჩრთ. განთ.: განათების ჩართვა",
    "Entities.gmod_subway_em508.Buttons.Main.DIPoffSet": "გამრთ. განათ.: განათებუს გამორთვა",
    "Entities.gmod_subway_em508_int.Buttons.Main.VozvratRPSet": "დდგ: დაბრუნება დგ",
    "Entities.gmod_subway_em508_int.Buttons.Main.KSNSet": "ღგს:გამაფრთხილებელი ჩართვა გდ–ს გაუმართავ ვაგონზე (გაუმართვაობის სიგნალიზაცია)",
    "Entities.gmod_subway_em508_int.Buttons.Main.KRZDSet": "კადღ: კარების ავარიული დაკეტვის ღილაკი",
    "Entities.gmod_subway_em508_int.Buttons.Main.KDPSet": "მკღ: მარჯვენა კარები",
    "Entities.gmod_subway_em508_int.Buttons.Main.KDLSet": "მკღ: მარცხენა კარები",
    "Entities.gmod_subway_em508_int.Buttons.Main.KU1Toggle": "მჩ: მოტორ–კომპრესორის ჩართვა",
    "Entities.gmod_subway_em508_int.Buttons.Main.VUD1Toggle": "კდ: კარების დაკეტვა",
    "Entities.gmod_subway_em508_int.Buttons.AV1.VU3Toggle": "ВУ3: კაბინის განათება",
    "Entities.gmod_subway_em508_int.Buttons.AV1.VU2Toggle": "ВУ2: ავარიული განათება",
    "Entities.gmod_subway_em508_int.Buttons.AV1.VU1Toggle": "ВУ1: კაბინის ფეჩი",
    "Entities.gmod_subway_em508_int.Buttons.AVMain.AV8BToggle": "АВ-8Б: ავტომატური გამომრთველი (მაღალი ძაბვის დამხმარე სქემები)\n",
    "Entities.gmod_subway_em508_int.Buttons.CabinDoor.CabinDoor": "კარები მემანქანის კაბინაში",
    "Entities.gmod_subway_em508_int.Buttons.Lamp.L_3Toggle": "ნათურა: პანელის განათება",
    "Entities.gmod_subway_em508_int.Buttons.PassengerDoor1.PassengerDoor": "კარი სალონიდან მემანქანის კაბინაში",
    "Entities.gmod_subway_em508_int.Buttons.DriverValveTLDisconnect.DriverValveTLDisconnectToggle": "ორმაგი ზეწოლის მაგისრალის კრანი",
    "Entities.gmod_subway_em508_int.Buttons.GV.GVToggle": "მთავარი მჩამრთველი",
    "Entities.gmod_subway_em508_int.Buttons.VU.VUToggle": "მგ: მართვის გამომრთველი",
    "Entities.gmod_subway_em508_int.Buttons.PneumaticPanels.!CylinderPressure": "სამუხრუჭე მანომეტრი: წნევა სამუხრუჭე მაგისრალში (ТЦ)",
    "Entities.gmod_subway_em508_int.Buttons.ParkingBrake.ParkingBrakeLeft": "ხელის მუხრუჭის მობრუნება",
    "Entities.gmod_subway_em508.Buttons.ParkingBrake.ParkingBrakeRight": "ხელის მუხრუჭის მობრუნება",
    "Entities.gmod_subway_em508_int.Buttons.PneumaticManometer.!LinesPressure": "წნევა მაგისრალში (წითელი: სამუხრუჭე, შავი: ზეწოლა)"
}
]]
