return [[
{
    "Lang": "geo",
    "Name": "Georgian",


    "Entities.gmod_subway_81-703.Buttons.HelperPanel.R_Program1Set": "პროგრამა 1",
    "Entities.gmod_subway_81-703.Buttons.HelperPanel.R_Program2Set": "პროგრამა 2",
    "Entities.gmod_subway_81-703.Buttons.HelperPanel.VDLSet": "მკგ: მარცხენა კარების გამომრთველი",
    "Entities.gmod_subway_81-703.Buttons.HelperPanel.VUD2Toggle": "კმგ2: კარების მართვის გამომრთველი",
    "Entities.gmod_subway_81-703.Buttons.Meters.!TotalVoltmeter": "ვოლტმეტრი მაღალი ძაბვის (кВ)",
    "Entities.gmod_subway_81-703.Buttons.Meters.!TotalAmpermeter": "ამპერმეტრი (А)",
    "Entities.gmod_subway_81-703.Buttons.AV2.RSTToggle": "რს: რადიოსადგური",
    "Entities.gmod_subway_81-703.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "ზეწოლის მაგისრალის კიდური კრანი",
    "Entities.gmod_subway_81-703.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "სამუხრუჭე მაგისრალის კიდური კრანი",
    "Entities.gmod_subway_81-703.Buttons.Back2.!HVFuses": "მაღალი ძაბვის ბლოკი",
    "Entities.gmod_subway_81-703.Buttons.Back2.!DVR": "კარის საჰაერო დისტრიბუტორი",
    "Entities.gmod_subway_81-703.Buttons.Main.RK": "ნათურა: როსტატიკური კონტროლერის როტაცია)",
    "Entities.gmod_subway_81-703.Buttons.Main.GreenRP": "ნათურა: მწვანე გდ (სიგნალიზაცია გადატვირთვა მატარებელზე)",
    "Entities.gmod_subway_81-703.Buttons.Main.RedRP": "ნათურა: წითელი გდ",
    "Entities.gmod_subway_81-703.Buttons.Main.Blue": "ნათურა: კარების სიგნალიზაცია",
    "Entities.gmod_subway_81-703.Buttons.Main.DIPonSet": "ჩრთ. განთ.: განათების ჩართვა",
    "Entities.gmod_subway_81-703.Buttons.Main.DIPoffSet": "გამრთ. განთ.: განათების გამორთვა (სიგნალი)",
    "Entities.gmod_subway_81-703.Buttons.Main.VozvratRPSet": "დგდ: დაბრუნება გდ",
    "Entities.gmod_subway_81-703.Buttons.Main.KSNSet": "КСН: გამაფრთხილებელი ჩართვა გდ–ს გაუმართავ ვაგონზე (გაუმართვაობის სიგნალიზაცია)",
    "Entities.gmod_subway_81-703.Buttons.Main.KRZDSet": "სკდღ: საავარიო კარების დაკეტვის ღილაკი",
    "Entities.gmod_subway_81-703.Buttons.Main.KSDSet": "კსკ: კარების სიგნალიზაციის კონტროლი(შემოწმება კს)",
    "Entities.gmod_subway_81-703.Buttons.Main.KDPSet": "მკღ: მარჯვენა კარები",
    "Entities.gmod_subway_81-703.Buttons.Main.KDLSet": "მკღ: მარცხენა კარების ღილაკი",
    "Entities.gmod_subway_81-703.Buttons.Main.KU1Toggle": "მჩ: მოტორ–კომპრესორის ჩართვა",
    "Entities.gmod_subway_81-703.Buttons.Main.VUD1Toggle": "კდ: კარების დაკეტვა",
    "Entities.gmod_subway_81-703.Buttons.Main.KRPSet": "აჩღ: ავარიული ჩართვა (ხელით კონტროლი)",
    "Entities.gmod_subway_81-703.Buttons.AV1.VU3Toggle": "ВУ3: კაბინის განათება\n",
    "Entities.gmod_subway_81-703.Buttons.AV1.VU2Toggle": "ВУ2: ავარიული განათება (45ვ)\n",
    "Entities.gmod_subway_81-703.Buttons.AV1.VU1Toggle": "ВУ1: კაბინის ფეჩი (3кВт)\n",
    "Entities.gmod_subway_81-703.Buttons.AVMain.AV8BToggle": "АВ-8Б: ავტომატური გამომრთველი (მაღალი ძაბვის დამხმარე სქემები)\n",
    "Entities.gmod_subway_81-703.Buttons.Lamp.L_3Toggle": "ნათურა: ინსტრუმენტის განათება",
    "Entities.gmod_subway_81-703.Buttons.DriverValveTLDisconnect.DriverValveTLDisconnectToggle": "ორმაგი ზეწოლის მაგისრალის კრანი",
    "Entities.gmod_subway_81-703.Buttons.VU.VUToggle": "მგ: მართვის გამომრთველი",
    "Entities.gmod_subway_81-703.Buttons.FrontDoor.FrontDoor": "წინა კარი",
    "Entities.gmod_subway_81-703.Buttons.PneumaticManometer.!LinesPressure": "წნევა მაგისრალში (წითელი: სამუხრუჭე, შავი: ზეწოლა)",
    "Entities.gmod_subway_81-703.Buttons.Stopkran.EmergencyBrakeValveToggle": "სტოპკრანი",
    "Entities.gmod_subway_81-703.Buttons.UAVAPanel.UAVAToggle": "უაგგ: უნივერსალური ავარიული გაჩერების გამომრთველი (ავტოსოპის გამორთვა)",
    "Entities.gmod_subway_81-703.Buttons.UAVAPanel.UAVAContactSet": "უაგგ: უნივერსალური ავარიული გაჩერების გამომრთველი (კონტაქტების აღდგენა)",
    "Entities.gmod_subway_81-703.Buttons.PneumaticPanels.!CylinderPressure": "სამუხრუჭე მანომეტრი: წნევა სამუხრუჭე მაგისრალში (სმ)",
    "Entities.gmod_subway_81-703.Buttons.Battery.VBToggle": "ბგ: ბატარეების გამომრთველი(დამხმარე სქემები დაბალი ძაბვის)",
    "Entities.gmod_subway_81-703.Buttons.Battery.R_RadioToggle": "რადიოინფომატორის ზვება +50ვ",
    "Entities.gmod_subway_81-703.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "სამუხრუჭე მაგისრალის კიდური კრანი",
    "Entities.gmod_subway_81-703.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "ზეწოლის მაგისრალის კიდური კრანი",
    "Entities.gmod_subway_81-703.Buttons.ASNP.R_ASNPMenuSet": "ინფორმატორი: მენიუ",
    "Entities.gmod_subway_81-703.Buttons.ASNP.R_ASNPUpSet": "ინფორმატორი: ზემოთ",
    "Entities.gmod_subway_81-703.Buttons.ASNP.R_ASNPDownSet": "ინფორმატორი: ქვემოთ",
    "Entities.gmod_subway_81-703.Buttons.ASNP.R_ASNPOnToggle": "ინფორმატორი: ჩართვა",
    "Entities.gmod_subway_81-703.Buttons.GV.GVToggle": "მთავარი ჩამრთველი",
    "Entities.gmod_subway_81-703.Buttons.PassengerDoor.PassengerDoor": "კარები სალონიდან",
    "Entities.gmod_subway_81-703.Buttons.KRR.KRRToggle": "რმღ: რევერსორი მობრუნების ღილაკი",
    "Entities.gmod_subway_81-703.Buttons.VU4.VUSToggle": "გადამრთველი: ახლო შუქი/დალნები",
    "Entities.gmod_subway_81-703.Buttons.CabinDoor.CabinDoor1": "კარები მემანქანის კაბინაში",
    "Entities.gmod_subway_81-703.Buttons.Tsepi.!BatteryVoltage": "ძაბვა მართვის სქემებზე",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.IGLA1USet": "ИГЛА: პირველი ღილაკი ზემოთ",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.IGLA1Set": "ИГЛА: პრიველი ღილაკი",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.IGLA1DSet": "ИГЛА: პირველი ღილაკი ქვემოთ",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.IGLA2USet": "ИГЛА: მეორე ღილაკი ზემოთ",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.IGLA2Set": "ИГЛА: მეორე ღილაკი",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.IGLA2DSet": "ИГЛА: მეორე ღილაკი ქვემოთ",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.!IGLASR": "ИГЛА: SR",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.!IGLARX": "ИГЛА: RX",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.!IGLAErr": "ИГЛА: Отказ",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.!IGLAOSP": "ИГЛА: ОСП",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.!IGLAPI": "ИГЛА: ПИ",
    "Entities.gmod_subway_81-703.Buttons.IGLAButtons.!IGLAOff": "ИГЛА: გამრთ",
    "Entities.gmod_subway_81-703.Buttons.Back1.R_UNchToggle": "დსგ: დაბალი სიხშირის გამაძლიერებელი(სალონის ხმა)",
    "Entities.gmod_subway_81-703.Buttons.Back1.IGLAToggle": "АСОТП: ИГЛА",
    "Entities.gmod_subway_81-703.Buttons.Back1.RezMKSet": "ავარიული ჩართვა მოტორ–კომპრესორის",
    "Entities.gmod_subway_81-703.Buttons.ParkingBrake.ParkingBrakeLeft": "ხელის მუხრუჭის მობრუნება",
    "Entities.gmod_subway_81-703.Buttons.ParkingBrake.ParkingBrakeRight": "ხელის მუხრუჭის მობრუნება",
    "Entities.gmod_subway_81-703.Buttons.DriverValveBLDisconnect.DriverValveBLDisconnectToggle": "ორმაგი მუხრუჭის მაგისრალის კრანი",
    "Entities.gmod_subway_81-703.Buttons.Speedometer.!Speedometer": "სპიდომეტრი",
    "Entities.gmod_subway_81-703.Buttons.AirDistributor.AirDistributorDisconnectToggle": "დისტრიბუტორის გამორთვა",



    "Entities.gmod_subway_81-703_2.Buttons.Stopkran.EmergencyBrakeValveToggle": "სტოპკრანი",
    "Entities.gmod_subway_81-703_2.Buttons.HelperPanel.R_Program1Set": "პროგრამა 1",
    "Entities.gmod_subway_81-703_2.Buttons.HelperPanel.R_Program2Set": "პროგრამა 2",
    "Entities.gmod_subway_81-703_2.Buttons.HelperPanel.VDLSet": "მკგ: მარცხენა კარების გამომრთველი",
    "Entities.gmod_subway_81-703_2.Buttons.HelperPanel.VUD2LToggle": "ჩაკეტვა კმგ2",
    "Entities.gmod_subway_81-703_2.Buttons.HelperPanel.VUD2Toggle": "კმგ22: კარების მართვის გამომრთველი",
    "Entities.gmod_subway_81-703_2.Buttons.PneumaticPanels.!CylinderPressure": "სამუხრუჭე მანომეტრი: წნევა სამუხრუჭე მაგისრალში (სმ)",
    "Entities.gmod_subway_81-703_2.Buttons.Battery.VBToggle": "ბგ: ბატარეების გამომრთველი(დამხმარე სქემები დაბალი ძაბვის)",
    "Entities.gmod_subway_81-703_2.Buttons.Battery.R_RadioToggle": "რადიოინფომატორის ზვება +50ვ",
    "Entities.gmod_subway_81-703_2.Buttons.Meters.!TotalVoltmeter": "ვოლტმეტრი მაღალი ძაბვის (кВ)",
    "Entities.gmod_subway_81-703_2.Buttons.Meters.!TotalAmpermeter": "ამპერმეტრი (А)",
    "Entities.gmod_subway_81-703_2.Buttons.AV2.RSTToggle": "რს: რადიოსადგური",
    "Entities.gmod_subway_81-703_2.Buttons.PassengerDoor.PassengerDoor": "კარი სალონიდან",
    "Entities.gmod_subway_81-703_2.Buttons.VU4.VUSToggle": "გადამრთველი: ახლო შუქი/დალნები",
    "Entities.gmod_subway_81-703_2.Buttons.AV1.VU3Toggle": "ВУ3: კაბინის განათება\n",
    "Entities.gmod_subway_81-703.Buttons.AV1.VU2Toggle": "ВУ2: ავარიული განათება (45ვ)\n",
    "Entities.gmod_subway_81-703.Buttons.AV1.VU1Toggle": "ВУ1: კაბინის ფეჩი (3кВт)\n",
    "Entities.gmod_subway_81-703_2.Buttons.UAVAPanel.UAVAToggle": "უაგგ: უნივერსალური ავარიული გაჩერების გამომრთველი (ავტოსოპის გამორთვა)",
    "Entities.gmod_subway_81-703_2.Buttons.UAVAPanel.UAVAContactSet": "უაგგ: უნივერსალური ავარიული გაჩერების გამომრთველი (კონტაქტების აღდგენა)",
    "Entities.gmod_subway_81-703_2.Buttons.AirDistributor.AirDistributorDisconnectToggle": "დისტრიბუტორის ჩართვა",
    "Entities.gmod_subway_81-703_2.Buttons.GV.GVToggle": "მთავარი ჩამრთველი",
    "Entities.gmod_subway_81-703_2.Buttons.FrontPneumatic.FrontBrakeLineIsolationToggle": "სამუხრუჭე მაგისრალის კიდური კრანი",
    "Entities.gmod_subway_81-703_2.Buttons.FrontPneumatic.FrontTrainLineIsolationToggle": "ზეწოლის მაგისრალის კიდური კრანი",
    "Entities.gmod_subway_81-703_2.Buttons.Tsepi.!BatteryVoltage": "ძაბვა მართვის სქემებზე",
    "Entities.gmod_subway_81-703_2.Buttons.RearPneumatic.RearTrainLineIsolationToggle": "ზეწოლის მაგისრალის კიდური კრანი",
    "Entities.gmod_subway_81-703_2.Buttons.RearPneumatic.RearBrakeLineIsolationToggle": "სამუხრუჭე მაგისრალის კიდური კრანი",
    "Entities.gmod_subway_81-703_2.Buttons.ParkingBrake.ParkingBrakeLeft": "ხელის მუხრუჭის მობრუნება",
    "Entities.gmod_subway_81-703_2.Buttons.ParkingBrake.ParkingBrakeRight": "ხელის მუხრუჭის მობრუნება",
    "Entities.gmod_subway_81-703_2.Buttons.Back2.!HVFuses": "მაღალი ძაბვის ბლოკი",
    "Entities.gmod_subway_81-703_2.Buttons.Back2.!DVR": "კარების ჰაერის დისტრიბუტორი",
    "Entities.gmod_subway_81-703_2.Buttons.Main.RK": "ნათურა: რეოსტატური კონტროლერის ბრუნვა)",
    "Entities.gmod_subway_81-703_2.Buttons.Main.GreenRP": "ნათურა: მწვანე დგ (დატვირთვის სიგნალიზაცია მატარებელზე)",
    "Entities.gmod_subway_81-703_2.Buttons.Main.RedRP": "ნათურა: წითელი დგ",
    "Entities.gmod_subway_81-703_2.Buttons.Main.Blue": "ნათურა: კარების სიგნალიზაცია",
    "Entities.gmod_subway_81-703_2.Buttons.Main.DIPonSet": "ჩრთ. განათ.: განათების ჩართვა",
    "Entities.gmod_subway_81-703_2.Buttons.Main.DIPoffSet": "გამრთ. განათ.: განათებუს გამორთვა",
    "Entities.gmod_subway_81-703_2.Buttons.Main.VozvratRPSet": "დდგ: დაბრუნება დგ",
    "Entities.gmod_subway_81-703_2.Buttons.Main.KSNSet": "КСН: გამაფრთხილებელი ჩართვა დგ გაუმართავ ვაგონზე (გაუმართავობის სიგნალიზაცია)",
    "Entities.gmod_subway_81-703_2.Buttons.Main.KRZDSet": "კადღ: კარების ავარიული დაკეტვის ღილაკი",
    "Entities.gmod_subway_81-703_2.Buttons.Main.KSDSet": "КСД: კარების სიგნალიზახიის კონტროლი(შემოწმება კს)",
    "Entities.gmod_subway_81-703_2.Buttons.Main.KDPSet": "მკღ: მარჯვენა კარები",
    "Entities.gmod_subway_81-703_2.Buttons.Main.KDLSet": "მკღ: მარცხენა კარების ღილაკი",
    "Entities.gmod_subway_81-703_2.Buttons.Main.KU1Toggle": "მკჩ: მოტორ–კომპრესორის ჩართვა",
    "Entities.gmod_subway_81-703_2.Buttons.Main.VUD1Toggle": "კდ: კარების დაკეტვა",
    "Entities.gmod_subway_81-703_2.Buttons.Main.KRPSet": "აჩ: ავარიული ჩართვა (ხელის მართვა)",
    "Entities.gmod_subway_81-703_2.Buttons.KRR.KRRToggle": "რდღ: რევერსორის დაბრუნების ღილაკი",
    "Entities.gmod_subway_81-703_2.Buttons.Back1.R_ZSToggle": "ხს: ხმამაღლამოლაპარაკეს გამომრთველი, ხმა სალონში",
    "Entities.gmod_subway_81-703_2.Buttons.Back1.IGLAToggle": "АСОТП: ИГЛА ჩრთ. (ზემოთ)/გამრთ. (ქვემოთ)",
    "Entities.gmod_subway_81-703_2.Buttons.Back1.RezMKSet": "ავარიული მოტორ–კომპრესორის ჩართვა",
    "Entities.gmod_subway_81-703_2.Buttons.CabinDoor.CabinDoor1": "კარები მემანქანის კაბინაში",
    "Entities.gmod_subway_81-703_2.Buttons.Lamp.L_3Toggle": "ნათურა: პანელის განათება",
    "Entities.gmod_subway_81-703_2.Buttons.DriverValveBLDisconnect.DriverValveBLDisconnectToggle": "ორმაგი მუხრუჭის მაგისტრალის კრანი ",
    "Entities.gmod_subway_81-703_2.Buttons.DriverValveTLDisconnect.DriverValveTLDisconnectToggle": "ორმაგი ზეწოლის მაგისრალის კრანი",
    "Entities.gmod_subway_81-703_2.Buttons.AVMain.AV8BToggle": "АВ-8Б: ავტომატური გამომრთველი (მაღალი ძაბვის დამხმარე სქემები))\n",
    "Entities.gmod_subway_81-703_2.Buttons.VU.VUToggle": "მგ: მართვის გამომრთველი",
    "Entities.gmod_subway_81-703_2.Buttons.FrontDoor.FrontDoor": "წინა კარი",
    "Entities.gmod_subway_81-703_2.Buttons.Speedometer.!Speedometer": "სპიდომეტრი",
    "Entities.gmod_subway_81-703_2.Buttons.PneumaticManometer.!LinesPressure": "წნევა მაგისრალში (წითელი: სამუხრუჭე, შავი: ზეწოლა)"
}
]]
